import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import vm from "node:vm";
import { build } from "vite";
import { beforeAll, describe, expect, it } from "vitest";
import { splitSqliteDistribution } from "../config/shared-sqlite-runtime.mjs";
import { sqliteRegistrationSections } from "../config/sqlite-api-trace.mjs";

const require = createRequire(new URL("../../kernel/package.json", import.meta.url));
const dist = join(dirname(require.resolve("@sqlite.org/sqlite-wasm/package.json")), "dist");
const index = readFileSync(join(dist, "index.mjs"), "utf8");
const worker = readFileSync(join(dist, "sqlite3-worker1.mjs"), "utf8");
const wasm = readFileSync(join(dist, "sqlite3.wasm"));
const codes = new Map();

beforeAll(async () => {
  const split = splitSqliteDistribution(index, worker);
  // Independent oracle: original package entry, NOT generated by the gate.
  // Negative mutants are test-only AST statement removal. None is exported,
  // written to disk, accepted by the generator, or reachable from a Vite config.
  for (const kind of ["original", "retained", "without-kvvfs", "without-vtab"]) {
    let source = kind === "retained" ? split.initializer : index;
    if (kind.startsWith("without-")) {
      const section = sqliteRegistrationSections(index).find(row => row.id === kind.slice(8));
      expect(section).toBeDefined();
      source = index.slice(0, section.start) + index.slice(section.end);
    }
    const entry = join(dist, "index.mjs").replaceAll("\\", "/");
    const result = await build({ configFile: false, logLevel: "silent",
      plugins: [{ name: "owned-trace-fixture", enforce: "pre",
        load: id => id.replaceAll("\\", "/") === entry ? source : undefined }],
      build: { write: false, minify: false, target: "es2022",
        lib: { entry, name: "OwnedSqlite", formats: ["iife"] } } });
    codes.set(kind, (Array.isArray(result) ? result[0] : result).output.find(item => item.type === "chunk").code);
  }
}, 30_000);

async function realm(kind) {
  const network = [];
  const context = vm.createContext({ URL, URLSearchParams, TextEncoder, TextDecoder, Blob, performance,
    setTimeout, clearTimeout, console: { log() {}, warn() {}, error() {}, debug() {} },
    location: { href: "https://owned.invalid/sqlite.js" },
    document: { currentScript: { src: "https://owned.invalid/sqlite.js", tagName: "SCRIPT" }, baseURI: "https://owned.invalid/" },
    fetch: url => { network.push(url); throw new Error("Fixture network forbidden"); } });
  vm.runInContext(codes.get(kind), context);
  const init = context.OwnedSqlite.default ?? context.OwnedSqlite;
  const sqlite = await init({ wasmBinary: wasm });
  const messages = [];
  context.postMessage = message => messages.push(message);
  vm.runInContext("globalThis.WorkerGlobalScope = function OwnedWorkerScope() {};", context);
  sqlite.initWorker1API();
  let sequence = 0;
  return { sqlite, context, network, async call(type, args, dbId) {
    const messageId = `owned-${++sequence}`;
    await context.onmessage({ data: { type, args, dbId, messageId } });
    return messages.find(message => message.messageId === messageId);
  } };
}

function descriptors(object) {
  return Reflect.ownKeys(object).map(key => {
    const value = Object.getOwnPropertyDescriptor(object, key);
    return [String(key), { configurable: value.configurable, enumerable: value.enumerable,
      writable: value.writable, get: typeof value.get, set: typeof value.set, value: typeof value.value }];
  }).sort(([left], [right]) => left.localeCompare(right));
}
function apiShape(sqlite) {
  const namespaces = [sqlite, sqlite.capi, sqlite.wasm, sqlite.oo1, sqlite.vfs, sqlite.vtab, sqlite.kvvfs,
    sqlite.capi.sqlite3_index_info.prototype, sqlite.capi.sqlite3_vfs.prototype, sqlite.capi.sqlite3_io_methods.prototype];
  return namespaces.map(descriptors);
}

describe("pinned SQLite independent initialization oracle", () => {
  it("retains exported names/descriptors, struct helpers, callback registration and required startup side effects", async () => {
    const original = await realm("original"), retained = await realm("retained");
    expect(apiShape(retained.sqlite)).toEqual(apiShape(original.sqlite));
    expect(retained.sqlite.capi.sqlite3_js_vfs_list()).toEqual(original.sqlite.capi.sqlite3_js_vfs_list());
    expect(retained.sqlite.capi.sqlite3_kvvfs_methods).toBeUndefined();
    expect(retained.sqlite.capi.KVVfsFile).toBeUndefined();
    expect(typeof retained.sqlite.vtab.setupModule).toBe("function");
    expect(typeof retained.sqlite.installOpfsSAHPoolVfs).toBe("function");
    expect(original.network).toEqual([]); expect(retained.network).toEqual([]);
  });

  it.each(["original", "retained"])("%s supports memory SQL, attached atomic rollback, export/deserialize, errors and close", async kind => {
    const { sqlite, context, network } = await realm(kind), db = new sqlite.oo1.DB(":memory:");
    let copy;
    try {
      db.exec("CREATE TABLE owned(id INTEGER PRIMARY KEY, value TEXT NOT NULL); INSERT INTO owned VALUES (1,'before'); ATTACH ':memory:' AS sys; ATTACH ':memory:' AS catalog; CREATE TABLE sys.owned(value); CREATE TABLE catalog.owned(value); INSERT INTO sys.owned VALUES (1); INSERT INTO catalog.owned VALUES (1);");
      db.exec("BEGIN; UPDATE owned SET value='lost'; UPDATE sys.owned SET value=2; UPDATE catalog.owned SET value=2; ROLLBACK;");
      expect(db.selectObjects("SELECT * FROM owned")).toEqual([{ id: 1, value: "before" }]);
      expect(["sys", "catalog"].map(name => db.selectValue(`SELECT value FROM ${name}.owned`))).toEqual([1, 1]);
      const bytes = sqlite.capi.sqlite3_js_db_export(db.pointer);
      // SDK typed-array checks must use intrinsics from the owned WASM realm.
      context.ownedBytes = bytes;
      const copied = vm.runInContext("new Uint8Array(ownedBytes)", context);
      const pointer = sqlite.wasm.allocFromTypedArray(copied);
      copy = new sqlite.oo1.DB(":memory:");
      const rc = sqlite.capi.sqlite3_deserialize(copy.pointer, "main", pointer, copied.length, copied.length,
        sqlite.capi.SQLITE_DESERIALIZE_FREEONCLOSE | sqlite.capi.SQLITE_DESERIALIZE_RESIZEABLE);
      copy.checkRc(rc);
      expect(copy.selectValue("SELECT value FROM owned")).toBe("before");
      expect(Array.from(sqlite.capi.sqlite3_js_db_export(copy.pointer))).toEqual(Array.from(bytes));
      expect(() => copy.exec("INSERT INTO owned VALUES(1, NULL)")).toThrow();
      expect(() => db.exec("SELECT missing FROM absent")).toThrow();
      expect(sqlite.capi.sqlite3_get_autocommit(db.pointer)).toBe(1);
    } finally { copy?.close(); db.close(); }
    expect(db.pointer).toBeUndefined(); expect(network).toEqual([]);
  });

  it.each(["original", "retained"])("%s keeps Worker1 open/query/export/errors/close and named-memory KVVFS", async kind => {
    const { call, network } = await realm(kind);
    expect((await call("config-get")).result.vfsList).toContain("kvvfs");
    for (const args of [{ filename: ":memory:" }, { filename: "owned-sqlite-trace", vfs: "kvvfs" }]) {
      const opened = await call("open", args);
      expect(opened.type).toBe("open"); const id = opened.dbId;
      try {
        expect((await call("exec", { sql: "CREATE TABLE owned(value); INSERT INTO owned VALUES(17); SELECT value FROM owned", rowMode: "array", resultRows: [] }, id)).result.resultRows).toEqual([[17]]);
        expect((await call("exec", { sql: "SELECT missing FROM absent" }, id)).type).toBe("error");
        const exported = await call("export", {}, id);
        expect(exported.result.byteArray.byteLength).toBeGreaterThan(512);
      } finally { expect((await call("close", {}, id)).type).toBe("close"); }
    }
    expect(network).toEqual([]);
  });

  it("detects unsafe KVVFS omission: Worker1 still advertises a VFS whose callback initialization no longer works", async () => {
    const original = await realm("original"), mutant = await realm("without-kvvfs");
    expect(apiShape(original.sqlite)).not.toEqual([
      mutant.sqlite, mutant.sqlite.capi, mutant.sqlite.wasm, mutant.sqlite.oo1, mutant.sqlite.vfs,
      mutant.sqlite.vtab, mutant.sqlite.kvvfs ?? {}, mutant.sqlite.capi.sqlite3_index_info.prototype,
      mutant.sqlite.capi.sqlite3_vfs.prototype, mutant.sqlite.capi.sqlite3_io_methods.prototype,
    ].map(descriptors));
    expect((await mutant.call("config-get")).result.vfsList).toContain("kvvfs");
    const opened = await original.call("open", { filename: "owned-omission-proof", vfs: "kvvfs" });
    expect(opened.type).toBe("open"); await original.call("close", {}, opened.dbId);
    expect((await mutant.call("open", { filename: "owned-omission-proof", vfs: "kvvfs" })).type).toBe("error");
  });

  it("detects unsafe vtab omission: public struct methods and module helpers disappear", async () => {
    const original = await realm("original"), mutant = await realm("without-vtab");
    expect(typeof original.sqlite.capi.sqlite3_index_info.prototype.nthConstraint).toBe("function");
    expect(mutant.sqlite.capi.sqlite3_index_info.prototype.nthConstraint).toBeUndefined();
    expect(mutant.sqlite.vtab).toBeUndefined();
    expect(typeof original.sqlite.vtab.setupModule).toBe("function");
    const first = new original.sqlite.capi.sqlite3_index_info();
    try {
      expect(first.nthConstraint(0)).toBe(false);
      expect(first.nthConstraintUsage(0)).toBe(false);
      expect(first.nthOrderBy(0)).toBe(false);
    } finally { first.dispose(); }
  });
});
