import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: c3fce0a7c2672c1e6b6abcde3572a9d3857234b231ad43579fe49206d35bb815; closed parse program v1.
import { standalone } from './runtime.mjs';
import { Sha256 as __ref0 } from './index.mjs';
import { CanonicalInstant as __ref1 } from './catalog.mjs';
import { OperationId as __ref2 } from './index.mjs';
import { UInt64Decimal as __ref3 } from './index.mjs';
import { LeaseId as __ref4 } from './index.mjs';
import { AuthorityIncarnationId as __ref5 } from './index.mjs';
import { ReleaseId as __ref6 } from './index.mjs';
import { ImmutableAppGenerationV1 as __ref7 } from './catalog.mjs';
import { AppInstanceId as __ref8 } from './index.mjs';
import { GenerationId as __ref9 } from './index.mjs';
import { ProductionRequestReceiptV1 as __ref10 } from './catalog.mjs';
import { NamespaceId as __ref11 } from './index.mjs';
import { WriteFenceV1 as __ref12 } from './catalog.mjs';
import { RequestId as __ref13 } from './index.mjs';
import { TargetEvidenceV1 as __ref14 } from './catalog.mjs';
import { AuthenticatedFormat5RestoreGrantV1 as __ref15 } from './restore.mjs';
import { AppLifecycleReceiptV1 as __ref16 } from './catalog.mjs';
import { AppCatalogEntryV1 as __ref17 } from './catalog.mjs';
import { CatalogRevisionReservationV1 as __ref18 } from './catalog.mjs';
import { CatalogGenerationEventV1 as __ref19 } from './catalog.mjs';
import { BackupRecordV1 as __ref20 } from './backup.mjs';
import { BackupRetentionHistoryV1 as __ref21 } from './backup.mjs';
import { TargetAuthorityHeaderV1 as __ref22 } from './catalog.mjs';
export const ArchiveCatalogDisplayName = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[6], value => value === value.trim(), "canonical display name required"]))();
export const ArchiveCatalogShellId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^[a-z0-9_-]{1,64}$/, "regex"]]]))();
export const ArchiveFileBytes = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([1, [[5], [0, 0, true], __standalonePrograms[7], [1, 9007199254740991, true], [1, 402653184, true]]]))();
export const ArchiveCount = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[8]))();
export const ArchiveAttachmentsV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "count": ArchiveCount, "bytes": ArchiveCount }, 1]))();
export const ArchiveFileDigestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "bytes": ArchiveFileBytes, "sha256": __ref0 }, 1]))();
export const ArchiveManifestV5 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "format": [4, 5], "app": __standalonePrograms[9], "exported_at": __ref1, "tables": __standalonePrograms[10], "versions": __standalonePrograms[11], "attachments": ArchiveAttachmentsV1, "files": [6, { "userDb": ArchiveFileDigestV1, "systemDb": ArchiveFileDigestV1, "authority": ArchiveFileDigestV1 }, 1] }, 1]))();
export const MAX_ARCHIVE_AUTHORITY_HISTORY_ENTRIES = 50_000;
export const MAX_ARCHIVE_AUTHORITY_TOTAL_ENTRIES = 100_000;
export const ArchiveTargetRevisionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "operationId": __ref2, "revision": __ref3, "expectedProtectionRevision": __ref3, "expectedStateSha256": __ref0, "requestSha256": __ref0, "state": [5, ["reserved", "committed", "abandoned"]], "reservedAt": __ref1, "finalizedAt": [13, __ref1], "stateSha256": [13, __ref0] }, 1], (value, context) => {
        if (value.revision === "0"
            || BigInt(value.expectedProtectionRevision) >= BigInt(value.revision))
            context.addIssue({ code: "custom", message: "target revision must advance its predecessor" });
        if ((value.state === "reserved" && (value.finalizedAt !== null || value.stateSha256 !== null))
            || (value.state === "committed" && (value.finalizedAt === null || value.stateSha256 === null))
            || (value.state === "abandoned" && (value.finalizedAt === null || value.stateSha256 !== null)))
            context.addIssue({ code: "custom", message: "target revision finalization is invalid" });
        if (value.finalizedAt !== null && value.finalizedAt < value.reservedAt)
            context.addIssue({ code: "custom", message: "target revision finalization precedes reservation" });
    }]))();
export const ArchiveCatalogLeaseV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "leaseId": __ref4, "authorityIncarnationId": __ref5, "writeEpoch": __ref3, "releaseId": __ref6, "issuedAtMs": __ref3, "expiresAtMs": __ref3, "revoked": [2] }, 1], (value, context) => {
        const issued = BigInt(value.issuedAtMs);
        const expires = BigInt(value.expiresAtMs);
        if (expires <= issued || expires - issued > 300000n
            || expires > BigInt(Number.MAX_SAFE_INTEGER))
            context.addIssue({ code: "custom", message: "archive catalog lease interval is invalid" });
    }]))();
export const ArchiveGenerationEvidenceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "operationId": __ref2, "storageKey": [0, [[3, /^[a-zA-Z0-9_-]{1,80}$/, "regex"]]], "descriptor": __ref7 }, 1]))();
export const ArchiveCatalogEntryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "appInstanceId": __ref8, "displayName": ArchiveCatalogDisplayName, "shellId": ArchiveCatalogShellId, "activeGenerationId": __ref9, "journalGenesisGenerationId": __ref9, "journalGenesisLineageEpoch": __ref3, "journalGenesisProtectionRevision": __ref3, "journalGenesisStateSha256": __ref0, "currentLineageEpoch": __ref3, "lineageEpochHighWater": __ref3, "currentProtectionRevision": __ref3, "revisionHighWater": __ref3, "digestSchema": [4, 1], "stateSha256": __ref0, "tombstoned": [2] }, 1], (value, context) => {
        if (BigInt(value.currentLineageEpoch) > BigInt(value.lineageEpochHighWater))
            context.addIssue({ code: "custom", message: "lineage epoch exceeds high-water mark" });
        if (BigInt(value.currentProtectionRevision) > BigInt(value.revisionHighWater))
            context.addIssue({ code: "custom", message: "protection revision exceeds high-water mark" });
        if (BigInt(value.journalGenesisLineageEpoch) > BigInt(value.currentLineageEpoch)
            || BigInt(value.journalGenesisProtectionRevision) > BigInt(value.currentProtectionRevision))
            context.addIssue({ code: "custom", message: "journal genesis exceeds current target" });
    }]))();
export const ArchiveCatalogSchemaObjectV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "type": [4, "table"], "name": __standalonePrograms[12], "tableName": __standalonePrograms[12], "sql": [0, [[0, 1, true], [1, 16384, true]]] }, 1], (value, context) => {
        if (value.name !== value.tableName)
            context.addIssue({ code: "custom", message: "catalog table object must name itself" });
    }]))();
export const ArchiveCatalogIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "idValue": __standalonePrograms[13], "idKind": [5, ["authority", "app", "generation", "namespace", "lease", "operation", "job"]], "retainedAt": __ref1 }, 1]))();
export const ArchiveTargetRequestReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "receipt": __ref10, "responseJson": [13, [0, [[1, 2000000, true]]]] }, 1], (value, context) => {
        if ((value.receipt.responseSha256 === null) !== (value.responseJson === null))
            context.addIssue({ code: "custom", message: "target request response mirror is incomplete" });
    }]))();
export const ArchiveBootstrapEntryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "storageKey": [0, [[3, /^[a-zA-Z0-9_-]{1,80}$/, "regex"]]], "userFile": __standalonePrograms[13], "systemFile": __standalonePrograms[13], "storageKind": [5, ["legacy", "generation"]], "appInstanceId": __ref8, "generationId": __ref9, "namespaceId": __ref11, "operationId": __ref2, "displayName": ArchiveCatalogDisplayName, "shellId": ArchiveCatalogShellId, "selected": [2], "declaredAt": __ref1 }, 1]))();
export const ArchivePendingJobV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "jobId": __standalonePrograms[14], "authorityIncarnationId": __ref5, "appInstanceId": [13, __ref8], "generationId": __ref9, "namespaceId": __ref11, "kind": __standalonePrograms[15], "state": __standalonePrograms[15], "operationId": __ref2, "sourceArchiveSha256": __ref0, "sourceProvenanceId": __standalonePrograms[16], "createdAt": __ref1, "updatedAt": __ref1 }, 1]))();
export const CatalogRestoreJobV2 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 2], "jobId": __standalonePrograms[14], "authorityIncarnationId": __ref5, "appInstanceId": [13, __ref8], "generationId": __ref9, "namespaceId": __ref11, "kind": [4, "restore_as_new"], "state": [4, "prepared"], "operationId": __ref2, "sourceArchiveSha256": __ref0, "sourceProvenanceId": __standalonePrograms[16], "createdAt": __ref1, "updatedAt": __ref1, "phase": [5, ["install", "cleanup"]], "fence": __ref12, "intent": [12, [6, { "requestId": __ref13, "requestSha256": __ref0, "sourceTarget": __ref14, "sourceCatalogGeneration": __ref3, "grant": __ref15 }, 1]] }, 1], (value, context) => {
        const intent = value.intent;
        if (value.appInstanceId === null || (value.phase === "install" && !intent)
            || value.authorityIncarnationId !== value.fence.authorityIncarnationId
            || (intent && (intent.grant.destinationAppInstanceId !== value.appInstanceId
                || intent.grant.preservedAppInstanceId !== intent.sourceTarget.appInstanceId
                || intent.grant.archiveSha256 !== value.sourceArchiveSha256
                || intent.grant.validationId !== value.sourceProvenanceId)))
            context.addIssue({ code: "custom", message: "restore intent binding is invalid" });
    }]))();
export const ArchiveLineageReservationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "appInstanceId": __ref8, "lineageEpoch": __ref3, "operationId": __ref2, "state": __standalonePrograms[15] }, 1]))();
export const ArchiveRestoreAsNewIdentityV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "appInstanceId": __ref8, "generationId": __ref9, "namespaceId": __ref11, "operationId": __ref2, "restoredAt": __ref1 }, 1]))();
export const ArchiveAuthorityBindingV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "format": [4, 5], "app": __standalonePrograms[9], "exportedAt": __ref1, "tables": __standalonePrograms[10], "versions": __standalonePrograms[11], "attachments": ArchiveAttachmentsV1, "userDb": ArchiveFileDigestV1, "systemDb": ArchiveFileDigestV1 }, 1]))();
export const ArchiveLifecycleReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "receipt": __ref16, "generationId": __ref9, "namespaceId": __ref11 }, 1]))();
export const ArchiveCatalogAuthorityV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "schemaObjects": [7, ArchiveCatalogSchemaObjectV1, undefined, [64]], "authorityIncarnationId": __ref5, "catalogGeneration": __ref3, "writeEpoch": __ref3, "selectedAppInstanceId": __ref8, "entry": __ref17, "entries": [7, ArchiveCatalogEntryV1, undefined, [1000]], "generations": [7, ArchiveGenerationEvidenceV1, undefined, [50000]], "idRegistry": [7, ArchiveCatalogIdV1, undefined, [50000]], "leases": [7, ArchiveCatalogLeaseV1, undefined, [50000]], "requestReceipts": [7, __ref10, undefined, [50000]], "revisionReservations": [7, __ref18, undefined, [50000]], "bootstrapManifest": [7, ArchiveBootstrapEntryV1, undefined, [1000]], "pendingJobs": [7, ArchivePendingJobV1, undefined, [50000]], "lineageReservations": [7, ArchiveLineageReservationV1, undefined, [50000]], "generationEvents": [7, __ref19, undefined, [50000]], "backupRecords": [7, __ref20, undefined, [50000]] }, 1]))();
export const ArchiveCatalogAuthorityV2 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 2], "schemaObjects": [7, ArchiveCatalogSchemaObjectV1, undefined, [64]], "authorityIncarnationId": __ref5, "catalogGeneration": __ref3, "writeEpoch": __ref3, "selectedAppInstanceId": __ref8, "entry": __ref17, "entries": [7, ArchiveCatalogEntryV1, undefined, [1000]], "generations": [7, ArchiveGenerationEvidenceV1, undefined, [50000]], "idRegistry": [7, ArchiveCatalogIdV1, undefined, [50000]], "leases": [7, ArchiveCatalogLeaseV1, undefined, [50000]], "requestReceipts": [7, __ref10, undefined, [50000]], "revisionReservations": [7, __ref18, undefined, [50000]], "bootstrapManifest": [7, ArchiveBootstrapEntryV1, undefined, [1000]], "pendingJobs": [7, ArchivePendingJobV1, undefined, [50000]], "lineageReservations": [7, ArchiveLineageReservationV1, undefined, [50000]], "generationEvents": [7, __ref19, undefined, [50000]], "backupRecords": [7, __ref20, undefined, [50000]], "lifecycleReceipts": [7, ArchiveLifecycleReceiptV1, undefined, [50000]] }, 1]))();
export const ArchiveCatalogAuthorityV3 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 3], "schemaObjects": [7, ArchiveCatalogSchemaObjectV1, undefined, [64]], "authorityIncarnationId": __ref5, "catalogGeneration": __ref3, "writeEpoch": __ref3, "selectedAppInstanceId": __ref8, "entry": __ref17, "entries": [7, ArchiveCatalogEntryV1, undefined, [1000]], "generations": [7, ArchiveGenerationEvidenceV1, undefined, [50000]], "idRegistry": [7, ArchiveCatalogIdV1, undefined, [50000]], "leases": [7, ArchiveCatalogLeaseV1, undefined, [50000]], "requestReceipts": [7, __ref10, undefined, [50000]], "revisionReservations": [7, __ref18, undefined, [50000]], "bootstrapManifest": [7, ArchiveBootstrapEntryV1, undefined, [1000]], "pendingJobs": [7, ArchivePendingJobV1, undefined, [50000]], "lineageReservations": [7, ArchiveLineageReservationV1, undefined, [50000]], "generationEvents": [7, __ref19, undefined, [50000]], "backupRecords": [7, __ref20, undefined, [50000]], "lifecycleReceipts": [7, ArchiveLifecycleReceiptV1, undefined, [50000]], "retentionHistory": __ref21 }, 1]))();
export const ArchiveAuthorityEvidenceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "binding": ArchiveAuthorityBindingV1, "target": __ref14, "merkle": [6, { "schema": [4, 1], "stateSha256": __ref0, "leafCount": ArchiveCount, "bucketRoots": [7, __ref0, undefined, undefined, [1024]] }, 1], "targetAuthority": [6, { "schema": [4, 1], "header": __ref22, "revisions": [7, ArchiveTargetRevisionV1, undefined, [50000]], "requestReceipts": [7, ArchiveTargetRequestReceiptV1, undefined, [50000]] }, 1], "catalogAuthority": [11, "schema", [[1, ArchiveCatalogAuthorityV1], [2, ArchiveCatalogAuthorityV2], [3, ArchiveCatalogAuthorityV3]]] }, 1], (value, context) => {
        const authorityEntries = value.targetAuthority.revisions.length
            + value.targetAuthority.requestReceipts.length
            + value.catalogAuthority.entries.length
            + value.catalogAuthority.generations.length
            + value.catalogAuthority.idRegistry.length
            + value.catalogAuthority.leases.length
            + value.catalogAuthority.requestReceipts.length
            + value.catalogAuthority.revisionReservations.length
            + value.catalogAuthority.bootstrapManifest.length
            + value.catalogAuthority.pendingJobs.length
            + value.catalogAuthority.lineageReservations.length
            + value.catalogAuthority.generationEvents.length
            + value.catalogAuthority.backupRecords.length
            + (value.catalogAuthority.schema !== 1 ? value.catalogAuthority.lifecycleReceipts.length : 0)
            + (value.catalogAuthority.schema === 3 ? value.catalogAuthority.retentionHistory.events.length : 0);
        if (authorityEntries > MAX_ARCHIVE_AUTHORITY_TOTAL_ENTRIES)
            context.addIssue({
                code: "custom",
                message: "archive authority history exceeds the total entry limit",
            });
        const target = value.target;
        const header = value.targetAuthority.header;
        const catalog = value.catalogAuthority;
        const entry = catalog.entry;
        if (value.merkle.stateSha256 !== target.stateSha256)
            context.addIssue({ code: "custom", message: "Merkle root does not match the canonical target" });
        if (header.appInstanceId !== target.appInstanceId
            || header.activeGenerationId !== target.activeGenerationId
            || header.lineageEpoch !== target.lineageEpoch
            || header.protectionRevision !== target.protectionRevision
            || header.digestSchema !== target.digestSchema)
            context.addIssue({ code: "custom", message: "target authority header does not match the canonical target" });
        if (catalog.selectedAppInstanceId !== target.appInstanceId
            || entry.appInstanceId !== target.appInstanceId
            || entry.activeGenerationId !== target.activeGenerationId
            || entry.currentLineageEpoch !== target.lineageEpoch
            || entry.currentProtectionRevision !== target.protectionRevision
            || entry.digestSchema !== target.digestSchema
            || entry.stateSha256 !== target.stateSha256)
            context.addIssue({ code: "custom", message: "catalog selection does not match the canonical target" });
        const selectedEntries = catalog.entries.filter(candidate => candidate.appInstanceId === catalog.selectedAppInstanceId);
        if (selectedEntries.length !== 1
            || JSON.stringify(selectedEntries[0]) !== JSON.stringify(entry)
            || new Set(catalog.entries.map(candidate => candidate.appInstanceId)).size
                !== catalog.entries.length
            || new Set(catalog.generations.map(candidate => candidate.descriptor.generationId)).size
                !== catalog.generations.length
            || new Set(catalog.generations.map(candidate => candidate.descriptor.namespaceId)).size
                !== catalog.generations.length
            || new Set(catalog.generations.map(candidate => candidate.operationId)).size
                !== catalog.generations.length
            || new Set(catalog.generations.map(candidate => candidate.storageKey)).size
                !== catalog.generations.length)
            context.addIssue({ code: "custom", message: "catalog archive inventory is ambiguous" });
        if (entry.lineageEpochHighWater !== header.lineageEpochHighWater
            || entry.revisionHighWater !== header.protectionRevisionHighWater)
            context.addIssue({ code: "custom", message: "catalog and target high-water marks disagree" });
    }]))();
