import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: de36b18d7c9b9c1c70b59199341ae5e46bbbae86a0f0e3998e65b90812050f4d; closed parse program v1.
import { standalone } from './runtime.mjs';
import { UInt64Decimal as __ref0 } from './index.mjs';
import { Sha256 as __ref1 } from './index.mjs';
import { ReleaseId as __ref2 } from './index.mjs';
import { CanonicalInstant as __ref3 } from './catalog.mjs';
import { AuthorityIncarnationId as __ref4 } from './index.mjs';
import { AppInstanceId as __ref5 } from './index.mjs';
import { GenerationId as __ref6 } from './index.mjs';
import { TargetEvidenceV1 as __ref7 } from './catalog.mjs';
import { WriteFenceV1 as __ref8 } from './catalog.mjs';
import { RequestId as __ref9 } from './index.mjs';
import { OperationId as __ref10 } from './index.mjs';
export const MAX_BACKUP_ARCHIVE_BYTES = 384 * 1024 * 1024;
export const MAX_BACKUP_ROTATION_RECORDS = 64;
const MAX_SHAPE_VERSION = 2_147_483_647;
export const BackupTargetId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^tgt_[a-z2-7]{26}$/, "regex"]]]))();
export const BackupId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^bkp_[a-z2-7]{26}$/, "regex"]]]))();
export const BackupGenerationId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^backupgen_[a-z2-7]{26}$/, "regex"]]]))();
export const BackupTargetAdapterCertificationId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^btc_[a-z2-7]{26}$/, "regex"]]]))();
export const Hex16 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^[0-9a-f]{32}$/, "regex"]]]))();
export const PositiveUInt64Decimal = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __ref0, value => BigInt(value) > 0n, "positive uint64 required"]))();
export const BackupAuthenticationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "kind": [4, "cose_mac0_hmac_256_256"], "authenticationVersion": [4, 1], "keyId": Hex16, "seriesId": Hex16, "generation": PositiveUInt64Decimal }, 1], (value, context) => {
        if (value.keyId === value.seriesId)
            context.addIssue({
                code: "custom",
                path: ["seriesId"],
                message: "key and backup-series identifiers must differ",
            });
    }]))();
export const BindingIdentifier = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[0, 1, true], [1, 64, true], [3, /^[a-z][a-z0-9._-]{0,63}$/, "regex"]]]))();
export const RuntimeVersion = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[0, 1, true], [1, 40, true], [3, /^[0-9A-Za-z](?:[0-9A-Za-z._-]{0,39})$/, "regex"]]]))();
export const BackupRuntimeBindingV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "distribution": [5, ["managed_web", "browser_pwa", "installed_native"]], "osFamily": [5, ["windows", "macos", "linux", "chromeos", "android", "ios"]], "osVersion": RuntimeVersion, "runtimeFamily": [5, ["chromium", "firefox", "webkit", "webview2", "wkwebview", "native"]], "runtimeVersion": RuntimeVersion, "architecture": [5, ["x64", "arm64", "x86", "universal", "wasm32"]] }, 1]))();
export const BackupAdapterArtifactBindingV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "implementationId": BindingIdentifier, "implementationVersion": RuntimeVersion, "codeSha256": __ref1, "releaseId": __ref2, "buildSha256": __ref1, "runtime": BackupRuntimeBindingV1, "matrixId": BindingIdentifier, "matrixSha256": __ref1, "suiteId": BindingIdentifier, "suiteSha256": __ref1 }, 1]))();
export const BackupProbeId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^probe_[a-z2-7]{26}$/, "regex"]]]))();
export const BackupTargetAdapterCertificationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "certificationId": BackupTargetAdapterCertificationId, "binding": BackupAdapterArtifactBindingV1, "adapter": [5, ["browser_directory", "native_directory"]], "issuedAt": __ref3, "expiresAt": __ref3, "verdict": [4, "pass"], "restartProbe": [6, { "probeId": BackupProbeId, "firstProcessWriteSha256": __ref1, "fullProcessExitObserved": [4, true], "freshProcessReacquiredWithoutPicker": [4, true], "permissionRechecked": [4, true], "firstFileReadBackSha256": __ref1, "secondUniqueFileReadBackSha256": __ref1, "enumerationObservedBoth": [4, true], "ownedProbeCleanupVerified": [4, true], "evidenceSha256": __ref1 }, 1] }, 1], (value, context) => {
        if (value.expiresAt <= value.issuedAt)
            context.addIssue({
                code: "custom",
                path: ["expiresAt"],
                message: "adapter certification must expire after issuance",
            });
    }]))();
export const ShapeVersion = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([1, [[5], [0, 0, true], __standalonePrograms[7], [1, 9007199254740991, true], [1, 2147483647, true]]]))();
export const ArchiveByteLength = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([1, [[5], [0, 0, false], __standalonePrograms[7], [1, 9007199254740991, true], [1, 402653184, true]]]))();
export const BackupFileLabel = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [14, __standalonePrograms[9], value => value === value.trim(), "canonical backup file label required"], value => !/[\u0000-\u001f\u007f]/.test(value), "backup file label contains control characters"]))();
export const AutomaticBackupFileName = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, [[0, 1, true], [1, 160, true], [3, /^clay-[a-z0-9](?:[a-z0-9-]{0,47})-\d{8}T\d{9}Z-backupgen_[a-z2-7]{26}\.clay$/, "regex"]]], value => !value.includes("..") && !value.includes("/") && !value.includes("\\")]))();
export const BackupSelectedTargetV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "authorityIncarnationId": __ref4, "catalogGeneration": __ref0, "writeEpoch": __ref0, "selectedAppInstanceId": __ref5, "selectedActiveGenerationId": __ref6, "target": __ref7 }, 1], (value, context) => {
        if (value.selectedAppInstanceId !== value.target.appInstanceId)
            context.addIssue({
                code: "custom",
                path: ["selectedAppInstanceId"],
                message: "selected app must equal the target app",
            });
        if (value.selectedActiveGenerationId !== value.target.activeGenerationId)
            context.addIssue({
                code: "custom",
                path: ["selectedActiveGenerationId"],
                message: "selected generation must equal the target generation",
            });
    }]))();
export const BackupTargetV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "targetId": BackupTargetId, "appInstanceId": __ref5, "adapter": [4, "browser_directory"], "adapterCertificationId": BackupTargetAdapterCertificationId, "authorizedAt": __ref3 }, 1]))();
export const BackupSnapshotV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "format": [4, 5], "byteLength": ArchiveByteLength, "archiveSha256": __ref1, "authentication": BackupAuthenticationV1, "shapeHead": ShapeVersion, "shapeCurrent": ShapeVersion }, 1], (value, context) => {
        if (value.shapeCurrent > value.shapeHead)
            context.addIssue({
                code: "custom",
                path: ["shapeCurrent"],
                message: "shape cursor exceeds shape head",
            });
    }]))();
export const BackupRunV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "backupId": BackupId, "generationId": BackupGenerationId, "target": BackupTargetV1, "expected": BackupSelectedTargetV1, "fence": __ref8, "reason": [5, ["first_meaningful_write", "meaningful_write", "deadline", "backup_now", "retry"]], "attempt": [5, ["fresh", "write_reconcile", "publication_reconcile"]], "fileLabel": BackupFileLabel, "createdAt": __ref3, "archive": BackupSnapshotV1 }, 1], (value, context) => {
        if (value.target.appInstanceId !== value.expected.selectedAppInstanceId)
            context.addIssue({
                code: "custom",
                path: ["target", "appInstanceId"],
                message: "backup destination app does not match the selected app",
            });
        if (value.fence.authorityIncarnationId !== value.expected.authorityIncarnationId)
            context.addIssue({
                code: "custom",
                path: ["fence", "authorityIncarnationId"],
                message: "write fence authority does not match the selected target",
            });
        if (value.fence.writeEpoch !== value.expected.writeEpoch)
            context.addIssue({
                code: "custom",
                path: ["fence", "writeEpoch"],
                message: "write fence epoch does not match the selected target",
            });
        if (value.createdAt < value.target.authorizedAt)
            context.addIssue({
                code: "custom",
                path: ["createdAt"],
                message: "backup run predates target authorization",
            });
    }]))();
const backupArtifactShape = { "schema": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([4, 1]))(), "backupId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(BackupId))(), "generationId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(BackupGenerationId))(), "targetId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(BackupTargetId))(), "evidence": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__ref7))(), "fileName": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(AutomaticBackupFileName))(), "createdAt": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__ref3))(), "validatedAt": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__ref3))(), "shapeHead": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(ShapeVersion))(), "shapeCurrent": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(ShapeVersion))(), "archiveFormat": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([4, 5]))(), "byteLength": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(ArchiveByteLength))(), "archiveSha256": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__ref1))(), "authentication": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(BackupAuthenticationV1))(), "adapterCertificationId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(BackupTargetAdapterCertificationId))() };
export const ValidatedBackupArtifactV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "backupId": BackupId, "generationId": BackupGenerationId, "targetId": BackupTargetId, "evidence": __ref7, "fileName": AutomaticBackupFileName, "createdAt": __ref3, "validatedAt": __ref3, "shapeHead": ShapeVersion, "shapeCurrent": ShapeVersion, "archiveFormat": [4, 5], "byteLength": ArchiveByteLength, "archiveSha256": __ref1, "authentication": BackupAuthenticationV1, "adapterCertificationId": BackupTargetAdapterCertificationId }, 1], (value, context) => {
        if (value.validatedAt < value.createdAt)
            context.addIssue({
                code: "custom",
                path: ["validatedAt"],
                message: "backup validation predates creation",
            });
        if (value.shapeCurrent > value.shapeHead)
            context.addIssue({
                code: "custom",
                path: ["shapeCurrent"],
                message: "shape cursor exceeds shape head",
            });
    }]))();
export const BackupValidationCodeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["archive_valid", "archive_invalid", "digest_mismatch", "tuple_mismatch", "generation_not_selected", "permission_lost", "target_unreachable"]]))();
export const BackupRecordV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "backupId": BackupId, "generationId": BackupGenerationId, "targetId": BackupTargetId, "evidence": __ref7, "fileName": AutomaticBackupFileName, "createdAt": __ref3, "validatedAt": __ref3, "shapeHead": ShapeVersion, "shapeCurrent": ShapeVersion, "archiveFormat": [4, 5], "byteLength": ArchiveByteLength, "archiveSha256": __ref1, "authentication": BackupAuthenticationV1, "adapterCertificationId": BackupTargetAdapterCertificationId, "publicationCatalogGeneration": __ref0, "state": [5, ["valid", "invalid", "quarantined", "deleted"]], "validationCode": BackupValidationCodeV1 }, 1], (value, context) => {
        if (value.validatedAt < value.createdAt)
            context.addIssue({ code: "custom", message: "backup validation predates creation" });
        if (value.shapeCurrent > value.shapeHead)
            context.addIssue({ code: "custom", message: "shape cursor exceeds shape head" });
        const coherent = (value.state === "valid" || value.state === "deleted")
            ? value.validationCode === "archive_valid"
            : value.state === "invalid"
                ? ["archive_invalid", "digest_mismatch", "tuple_mismatch"].includes(value.validationCode)
                : ["generation_not_selected", "permission_lost", "target_unreachable"].includes(value.validationCode);
        if (!coherent)
            context.addIssue({ code: "custom", message: "backup state and validation code disagree" });
    }]))();
export const BackupPublicationRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "expected": BackupSelectedTargetV1, "fence": __ref8, "artifact": ValidatedBackupArtifactV1 }, 1], (value, context) => {
        if (value.fence.authorityIncarnationId !== value.expected.authorityIncarnationId
            || value.fence.writeEpoch !== value.expected.writeEpoch)
            context.addIssue({ code: "custom", message: "publication fence does not match target" });
        if (value.artifact.evidence.appInstanceId !== value.expected.target.appInstanceId
            || value.artifact.evidence.activeGenerationId !== value.expected.target.activeGenerationId
            || value.artifact.evidence.lineageEpoch !== value.expected.target.lineageEpoch
            || value.artifact.evidence.protectionRevision !== value.expected.target.protectionRevision
            || value.artifact.evidence.digestSchema !== value.expected.target.digestSchema
            || value.artifact.evidence.stateSha256 !== value.expected.target.stateSha256)
            context.addIssue({ code: "custom", message: "publication artifact does not match target" });
    }]))();
export const BackupPublicationReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "publication": [5, ["published", "already_published"]], "record": BackupRecordV1, "rotate": [7, BackupRecordV1, undefined, [64]] }, 1]))();
export const BackupRetentionScopeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "appInstanceId": __ref5, "targetId": BackupTargetId, "adapterCertificationId": BackupTargetAdapterCertificationId }, 1]))();
export const BackupRemovalIntentV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "authorityIncarnationId": __ref4, "planningRevision": __ref0, "backupId": BackupId, "keeperBackupId": BackupId }, 1]))();
export const BackupRemovalAcknowledgementV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "requestId": __ref9, "intent": BackupRemovalIntentV1, "outcome": [5, ["absent", "failed"]] }, 1]))();
export const BackupRetentionReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "requestId": __ref9, "intent": BackupRemovalIntentV1, "outcome": [5, ["absent", "failed"]], "schema": [4, 1], "revision": __ref0, "operationId": __ref10, "requestSha256": __ref1, "catalogGeneration": __ref0, "fence": __ref8, "completedAt": __ref3 }, 1]))();
export const BackupRetentionHistoryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "revision": __ref0, "events": [7, BackupRetentionReceiptV1, undefined, [100000]] }, 1]))();
export const BackupRetentionPlanV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "keeper": [13, BackupRecordV1], "entries": [7, [6, { "requestId": __ref9, "intent": BackupRemovalIntentV1, "record": BackupRecordV1 }, 1], undefined, [64]], "remaining": __standalonePrograms[8] }, 1]))();
export const BackupRemovalRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "requestId": __ref9, "intent": BackupRemovalIntentV1 }, 1]))();
export const BackupRemovalAuthorizationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "status", [["recorded", [6, { "status": [4, "recorded"], "receipt": BackupRetentionReceiptV1 }, 1]], ["ready", [6, { "status": [4, "ready"], "requestId": __ref9, "intent": BackupRemovalIntentV1, "record": BackupRecordV1, "keeper": BackupRecordV1, "fence": __ref8 }, 1]]]]))();
export const BackupRemovalPendingV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "phase", [["removing", [6, { "schema": [4, 1], "scope": BackupRetentionScopeV1, "requestId": __ref9, "intent": BackupRemovalIntentV1, "phase": [4, "removing"] }, 1]], ["observed", [6, { "schema": [4, 1], "scope": BackupRetentionScopeV1, "requestId": __ref9, "intent": BackupRemovalIntentV1, "phase": [4, "observed"], "outcome": [5, ["absent", "failed"]] }, 1]]]]))();
export const BackupStageValidationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "status", [["valid", [6, { "schema": [4, 1], "status": [4, "valid"], "evidence": __ref7, "authentication": BackupAuthenticationV1 }, 1]], ["invalid", [6, { "schema": [4, 1], "status": [4, "invalid"], "evidence": [3] }, 1]]]]))();
export const BackupProtectionFailureReasonCode = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["adapter_uncertified", "target_unconfigured", "permission_required", "target_unreachable", "backup_stale", "backup_invalid", "generation_not_selected", "stale_write_epoch"]]))();
export const BackupFailureReasonCodeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [BackupProtectionFailureReasonCode, [5, ["invalid_run", "snapshot_mismatch", "unsupported_api", "quota_exceeded", "destination_collision", "operation_interrupted", "short_write", "digest_mismatch", "publication_failed"]]]]))();
export const RotationSummaryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "requested": __standalonePrograms[17], "deleted": __standalonePrograms[17], "failed": __standalonePrograms[17] }, 1], (value, context) => {
        if (value.deleted + value.failed > value.requested)
            context.addIssue({ code: "custom", message: "rotation totals exceed requested records" });
    }]))();
export const BackupResultV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "status", [["failed", [6, { "schema": [4, 1], "status": [4, "failed"], "reasonCode": BackupFailureReasonCodeV1, "historical": [13, ValidatedBackupArtifactV1] }, 1]], ["published", [6, { "schema": [4, 1], "status": [4, "published"], "publication": [5, ["published", "already_published"]], "record": BackupRecordV1, "rotation": RotationSummaryV1 }, 1]]]]))();
export const ManualDownloadFileName = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [14, [0, [[0, 1, true], [1, 160, true]]], value => !/[\\/\u0000-\u001f\u007f]/.test(value) && !value.includes("..")], value => value.endsWith(".clay")]))();
export const ManualBackupDownloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "kind": [4, "manual_download"], "archiveFormat": [4, 4], "fileName": ManualDownloadFileName, "byteLength": ArchiveByteLength, "startedAt": __ref3, "verification": [4, "unverified"] }, 1]))();
export const ManualBackupDownloadV2 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 2], "kind": [4, "manual_download"], "archiveFormat": [4, 5], "fileName": ManualDownloadFileName, "byteLength": ArchiveByteLength, "startedAt": __ref3, "verification": [4, "unverified_external_save"], "authentication": BackupAuthenticationV1, "archiveSha256": __ref1, "evidence": __ref7 }, 1]))();
export const ManualDownloadIntentV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "requestId": __ref9, "record": ManualBackupDownloadV2, "phase": [5, ["prepared", "handed_off"]] }, 1]))();
export const __hook0 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[9], value => value === value.trim(), "canonical backup file label required"]))();
export const __hook1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, [[0, 1, true], [1, 160, true]]], value => !/[\\/\u0000-\u001f\u007f]/.test(value) && !value.includes("..")]))();
