import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: ef9f4ce7923ab78d0886f366452b745f688642dd4ec02ca2eab416bebd3658a1; closed parse program v1.
import { standalone } from './runtime.mjs';
import { AppInstanceId as __ref0 } from './index.mjs';
import { GenerationId as __ref1 } from './index.mjs';
import { UInt64Decimal as __ref2 } from './index.mjs';
import { Sha256 as __ref3 } from './index.mjs';
import { RequestId as __ref4 } from './index.mjs';
import { JsonValue as __ref5 } from './index.mjs';
import { SnapshotBasisV1 as __ref6 } from './daily-home.mjs';
import { DailySourceLibraryV1 as __ref7 } from './daily-home.mjs';
import { DailyHomeSnapshotV1 as __ref8 } from './daily-home.mjs';
import { InboxItemV1 as __ref9 } from './daily-home.mjs';
import { CanonicalLocalDateV1 as __ref10 } from './daily-home.mjs';
import { InboxDispositionV1 as __ref11 } from './daily-home.mjs';
import { OperationId as __ref12 } from './index.mjs';
import { NamespaceId as __ref13 } from './index.mjs';
import { AuthorityIncarnationId as __ref14 } from './index.mjs';
import { LeaseId as __ref15 } from './index.mjs';
import { ReleaseId as __ref16 } from './index.mjs';
export const TargetEvidenceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "appInstanceId": __ref0, "activeGenerationId": __ref1, "lineageEpoch": __ref2, "protectionRevision": __ref2, "digestSchema": [4, 1], "stateSha256": __ref3 }, 1]))();
export const presentationName = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[0]))();
export const relationCount = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[18]))();
export const RelationPreviewPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "sourceTable": presentationName, "sourceField": presentationName, "targetTable": presentationName, "displayField": presentationName }, 1]))();
export const RelationKeepPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "sourceTable": presentationName, "sourceField": presentationName, "targetTable": presentationName, "displayField": presentationName, "atVersion": __standalonePrograms[8], "fingerprint": __ref3, "matchedRows": relationCount, "unmatchedRows": relationCount, "ambiguousRows": relationCount, "duplicateSourceRows": relationCount, "unmatchedSamples": [7, [0, [[1, 64000, true]]], undefined, [5]], "ambiguousSamples": [7, [0, [[1, 64000, true]]], undefined, [5]], "cardinality": [4, "one"], "authorityTarget": TargetEvidenceV1 }, 1]))();
export const RelationUndoPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "conversionRequestId": __ref4, "beforeVersion": __standalonePrograms[8], "authorityTarget": [12, TargetEvidenceV1] }, 1]))();
export const DailyCapturePayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "appInstanceId": __ref0, "table": presentationName, "tableId": __standalonePrograms[19], "row": [8, [0, []], __ref5] }, 1]))();
export const DailyCaptureUndoPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "batchId": __standalonePrograms[20], "captureRequestId": __ref4, "capturePayload": DailyCapturePayloadV1, "authorityTarget": TargetEvidenceV1 }, 1], (value, context) => {
        if (value.capturePayload.appInstanceId !== value.authorityTarget.appInstanceId)
            context.addIssue({ code: "custom", message: "Capture Undo belongs to another app" });
    }]))();
export const DailyCasReviewV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "authorityTarget": TargetEvidenceV1, "basis": __ref6, "snapshotDigest": __ref3 }, 1], (value, context) => {
        if (value.basis.appInstanceId !== value.authorityTarget.appInstanceId || value.basis.activeGenerationId !== value.authorityTarget.activeGenerationId)
            context.addIssue({ code: "custom", message: "Daily review belongs to another source" });
    }]))();
export const navigationRef = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "tableId": __standalonePrograms[19], "rowId": __standalonePrograms[20] }, 0]))();
export const navigationInstant = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, [[3, /^((\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-((0[13578]|1[02])-(0[1-9]|[12]\d|3[01])|(0[469]|11)-(0[1-9]|[12]\d|30)|(02)-(0[1-9]|1\d|2[0-8])))T([01]\d|2[0-3]):[0-5]\d(:[0-5]\d(\.\d+)?)?(Z)$/, "datetime"]]], value => new Date(value).toISOString() === value]))();
export const DailyNavigationStateV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "revision": __standalonePrograms[8], "favorites": [7, [6, { "tableId": __standalonePrograms[19], "rowId": __standalonePrograms[20], "pinnedAt": navigationInstant }, 1], undefined, [50]], "recents": [7, [6, { "tableId": __standalonePrograms[19], "rowId": __standalonePrograms[20], "openedAt": navigationInstant }, 1], undefined, [20]] }, 1], (value, context) => {
        for (const refs of [value.favorites, value.recents])
            if (new Set(refs.map(ref => `${ref.tableId}/${ref.rowId}`)).size !== refs.length)
                context.addIssue({ code: "custom", message: "Duplicate navigation identity" });
    }]))();
export const DailySourceCasPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "review": DailyCasReviewV1, "expectedRevision": __standalonePrograms[8], "value": __ref7 }, 1]))();
export const DailyNavigationCasPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "review": DailyCasReviewV1, "expectedRevision": __standalonePrograms[8], "value": DailyNavigationStateV1 }, 1]))();
export const DailyPresentationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "authorityTarget": TargetEvidenceV1, "snapshot": __ref8, "sourceLibrary": __ref5, "navigation": __ref5 }, 1]))();
export const DailyInboxActionPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "review": DailyCasReviewV1, "item": __ref9, "action": [5, ["complete", "snooze", "dismiss"]], "untilLocalDate": [12, __ref10] }, 1], (value, context) => {
        if ((value.action === "snooze") !== (value.untilLocalDate !== undefined))
            context.addIssue({ code: "custom", message: "Only Snooze takes a reviewed local date" });
    }]))();
export const DailyInboxReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "disposition": __ref11, "previous": [13, __ref11], "batchId": [13, __standalonePrograms[20]] }, 1]))();
export const DailyInboxUndoPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "actionRequestId": __ref4, "actionPayload": DailyInboxActionPayloadV1, "authorityTarget": TargetEvidenceV1 }, 1], (value, context) => {
        if (value.actionPayload.review.authorityTarget.appInstanceId !== value.authorityTarget.appInstanceId)
            context.addIssue({ code: "custom", message: "Inbox Undo belongs to another app" });
    }]))();
export const AutomationCommandRouteV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["saveAutomationDraft", "saveAutomationRecipeDraft", "enableAutomation", "pauseAutomation", "deleteAutomation", "runAutomationNow", "runDueAutomations", "undoAutomationRun", "markNotificationRead"]]))();
export const AutomationCommandPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "authorityTarget": TargetEvidenceV1, "command": [6, { "route": AutomationCommandRouteV1, "payload": [8, [0, []], __ref5] }, 1] }, 1]))();
export const AutomationWorkspaceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "draftId": __ref4, "authorityTarget": TargetEvidenceV1, "kind": [5, ["custom", "edit", "recipe", "legacy"]], "fields": [8, [0, []], [0, [[1, 64000, true]]]], "definition": [13, [8, [0, []], __ref5]], "expectedRevision": __standalonePrograms[3], "recipeId": [13, [5, ["overdue_invoice_reminder", "weekly_checklist", "new_customer_follow_up"]]] }, 1]))();
export const IntakeCommandRouteV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["intake.saveForm", "intake.closePublication", "intake.markPublished", "intake.revokeForm", "intake.markExpired", "intake.stageSubmission", "intake.recordDeliveryFailure", "intake.authorizeDeliveryDiscard", "intake.resolveDeliveryFailure", "intake.rejectSubmission", "intake.simulateAutoAccept", "intake.enableAutoAccept", "intake.disableAutoAccept", "intake.processAutoAccept", "intake.acceptSubmission", "intake.undoReceipt"]]))();
export const IntakeCommandPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "authorityTarget": TargetEvidenceV1, "command": [6, { "route": IntakeCommandRouteV1, "payload": [8, [0, []], __ref5] }, 1] }, 1]))();
export const RecoverablePresentationRouteV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["schema.convertTextToRelation", "schema.undoRelationConversion", "daily.capture", "daily.undoCapture", "batch.apply", "batch.undo", "daily.source", "daily.navigation", "daily.inbox", "daily.undoInbox", "automation.command", "intake.command"]]))();
export const PresentationIntentV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "appInstanceId": __ref0, "slot": [5, ["relation", "capture", "conversionUndo", "captureUndo", "dailySource", "dailyNavigation", "dailyInbox", "dailyInboxUndo", "automation", "intake"]], "requestId": __ref4, "route": RecoverablePresentationRouteV1, "payload": [8, [0, []], __ref5] }, 1], (value, context) => {
        const contract = {
            relation: { route: "schema.convertTextToRelation", payload: RelationKeepPayloadV1 },
            conversionUndo: { route: "schema.undoRelationConversion", payload: RelationUndoPayloadV1 },
            capture: { route: "daily.capture", payload: DailyCapturePayloadV1 },
            captureUndo: { route: "daily.undoCapture", payload: DailyCaptureUndoPayloadV1 },
            dailySource: { route: "daily.source", payload: DailySourceCasPayloadV1 },
            dailyNavigation: { route: "daily.navigation", payload: DailyNavigationCasPayloadV1 },
            dailyInbox: { route: "daily.inbox", payload: DailyInboxActionPayloadV1 },
            dailyInboxUndo: { route: "daily.undoInbox", payload: DailyInboxUndoPayloadV1 },
            automation: { route: "automation.command", payload: AutomationCommandPayloadV1 },
            intake: { route: "intake.command", payload: IntakeCommandPayloadV1 },
        }[value.slot];
        if (value.route !== contract.route || !contract.payload.safeParse(value.payload).success) {
            context.addIssue({ code: "custom", message: "Stored retry payload or route is invalid for its slot" });
            return;
        }
        const source = value.payload.review ? value.payload.review.authorityTarget.appInstanceId
            : value.slot === "capture" ? value.payload.appInstanceId : value.payload.authorityTarget
                ? value.payload.authorityTarget.appInstanceId : value.appInstanceId;
        if (source !== value.appInstanceId)
            context.addIssue({ code: "custom", message: "Stored retry payload is bound to another app" });
    }]))();
export const PresentationMutationOutcomeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "status", [["not_invoked", [6, { "status": [4, "not_invoked"] }, 1]], ["uncertain", [6, { "status": [4, "uncertain"] }, 1]], ["cancelled", [6, { "status": [4, "cancelled"] }, 1]], ["failed", [6, { "status": [4, "failed"] }, 1]], ["recorded", [6, { "status": [4, "recorded"], "current": [2], "result": __ref5, "target": TargetEvidenceV1 }, 1]]]]))();
export const TargetAuthorityHeaderV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "appInstanceId": __ref0, "activeGenerationId": __ref1, "lineageEpoch": __ref2, "lineageEpochHighWater": __ref2, "protectionRevision": __ref2, "protectionRevisionHighWater": __ref2, "digestSchema": [4, 1] }, 1], (value, context) => {
        if (BigInt(value.lineageEpoch) > BigInt(value.lineageEpochHighWater))
            context.addIssue({ code: "custom", message: "lineage epoch exceeds its high-water mark" });
        if (BigInt(value.protectionRevision) > BigInt(value.protectionRevisionHighWater))
            context.addIssue({ code: "custom", message: "protection revision exceeds its high-water mark" });
    }]))();
export const CanonicalInstant = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[21], (value) => {
        try {
            return new Date(value).toISOString() === value;
        }
        catch {
            return false;
        }
    }, "exact UTC millisecond instant required"]))();
export const ProductionRequestReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "requestId": __ref4, "operationId": __ref12, "appInstanceId": __ref0, "activeGenerationId": __ref1, "lineageEpoch": __ref2, "expectedProtectionRevision": __ref2, "expectedStateSha256": __ref3, "requestSha256": __ref3, "state": [5, ["prepared", "invoked", "committed", "no_op", "failed"]], "resultingProtectionRevision": [13, __ref2], "resultingStateSha256": [13, __ref3], "responseSha256": [13, __ref3], "preparedAt": CanonicalInstant, "invokedAt": [13, CanonicalInstant], "completedAt": [13, CanonicalInstant] }, 1], (value, context) => {
        const terminal = value.state === "committed" || value.state === "no_op"
            || value.state === "failed";
        const hasAnyResult = value.resultingProtectionRevision !== null
            || value.resultingStateSha256 !== null || value.responseSha256 !== null
            || value.completedAt !== null;
        const hasResult = value.resultingProtectionRevision !== null
            && value.resultingStateSha256 !== null && value.responseSha256 !== null
            && value.completedAt !== null;
        if (value.state === "prepared" && (value.invokedAt !== null || hasAnyResult))
            context.addIssue({ code: "custom", message: "prepared request receipt is inconsistent" });
        if (value.state === "invoked" && (value.invokedAt === null || hasAnyResult))
            context.addIssue({ code: "custom", message: "invoked request receipt is inconsistent" });
        if (terminal && !hasResult)
            context.addIssue({ code: "custom", message: "terminal request receipt is incomplete" });
        if ((value.state === "no_op" || value.state === "failed") && hasResult
            && (value.resultingProtectionRevision !== value.expectedProtectionRevision
                || value.resultingStateSha256 !== value.expectedStateSha256))
            context.addIssue({ code: "custom", message: "non-commit receipt changed target identity" });
        if (value.state === "no_op" && value.invokedAt !== null)
            context.addIssue({ code: "custom", message: "canonical no-op must not invoke live mutation" });
        if (value.state === "committed" && (value.invokedAt === null || !hasResult
            || BigInt(value.resultingProtectionRevision) <= BigInt(value.expectedProtectionRevision)
            || value.resultingStateSha256 === value.expectedStateSha256))
            context.addIssue({ code: "custom", message: "committed request receipt is inconsistent" });
        if (value.invokedAt !== null && Date.parse(value.invokedAt) < Date.parse(value.preparedAt))
            context.addIssue({ code: "custom", message: "request invocation predates preparation" });
        if (value.completedAt !== null && Date.parse(value.completedAt) < Date.parse(value.preparedAt))
            context.addIssue({ code: "custom", message: "request completion predates preparation" });
    }]))();
export const ProvenanceId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[13], value => value === value.trim(), "canonical provenance identity required"]))();
export const ImmutableAppGenerationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "generationId": __ref1, "target": TargetEvidenceV1, "namespaceId": __ref13, "sourceArchiveSha256": [13, __ref3], "sourceProvenanceId": [13, ProvenanceId], "sealedAt": CanonicalInstant, "readBackAt": CanonicalInstant }, 1], (value, context) => {
        if (value.generationId !== value.target.activeGenerationId)
            context.addIssue({ code: "custom", message: "generation descriptor does not match target" });
    }]))();
export const WriteFenceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "authorityIncarnationId": __ref14, "writeEpoch": __ref2, "leaseId": __ref15, "releaseId": __ref16 }, 1]))();
export const CatalogDisplayName = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[6], value => value === value.trim(), "canonical display name required"]))();
export const CatalogShellId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^[a-z0-9_-]{1,64}$/, "regex"]]]))();
export const AppCatalogEntryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "appInstanceId": __ref0, "displayName": CatalogDisplayName, "shellId": CatalogShellId, "activeGenerationId": __ref1, "journalGenesisGenerationId": __ref1, "journalGenesisLineageEpoch": __ref2, "journalGenesisProtectionRevision": __ref2, "journalGenesisStateSha256": __ref3, "currentLineageEpoch": __ref2, "lineageEpochHighWater": __ref2, "currentProtectionRevision": __ref2, "revisionHighWater": __ref2, "digestSchema": [4, 1], "stateSha256": __ref3, "tombstoned": [4, false] }, 1], (value, context) => {
        if (BigInt(value.currentLineageEpoch) > BigInt(value.lineageEpochHighWater))
            context.addIssue({ code: "custom", message: "lineage epoch exceeds high-water mark" });
        if (BigInt(value.currentProtectionRevision) > BigInt(value.revisionHighWater))
            context.addIssue({ code: "custom", message: "protection revision exceeds high-water mark" });
        if (BigInt(value.journalGenesisLineageEpoch) > BigInt(value.currentLineageEpoch)
            || BigInt(value.journalGenesisProtectionRevision) > BigInt(value.currentProtectionRevision))
            context.addIssue({ code: "custom", message: "journal genesis exceeds current target" });
    }]))();
export const AppCatalogSnapshotV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "authorityIncarnationId": __ref14, "catalogGeneration": __ref2, "selectedAppInstanceId": [13, __ref0], "entries": [7, AppCatalogEntryV1], "writeEpoch": __ref2 }, 1], (value, context) => {
        const appIds = new Set();
        const generationIds = new Set();
        for (const entry of value.entries) {
            if (appIds.has(entry.appInstanceId))
                context.addIssue({ code: "custom", message: "duplicate app instance identity" });
            if (generationIds.has(entry.activeGenerationId))
                context.addIssue({ code: "custom", message: "duplicate active generation identity" });
            appIds.add(entry.appInstanceId);
            generationIds.add(entry.activeGenerationId);
        }
        if (value.selectedAppInstanceId !== null && !appIds.has(value.selectedAppInstanceId))
            context.addIssue({ code: "custom", message: "selected app is not a live catalog entry" });
    }]))();
export const LifecycleJobId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[14]))();
export const LifecycleStorageKey = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^(?:ns_[a-z2-7]{26}|[a-zA-Z0-9_][a-zA-Z0-9_-]{0,79})$/, "regex"]]]))();
export const LifecyclePhysicalTargetV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "appInstanceId": __ref0, "generationId": __ref1, "namespaceId": __ref13, "storageKey": LifecycleStorageKey, "userFile": __standalonePrograms[22], "systemFile": __standalonePrograms[22], "storageKind": [5, ["legacy", "generation"]], "displayName": CatalogDisplayName, "shellId": CatalogShellId }, 1], (value, context) => {
        const generation = value.storageKey === value.namespaceId
            && value.userFile === `/${value.namespaceId}-user.db`
            && value.systemFile === `/${value.namespaceId}-system.db`;
        const legacy = value.storageKey === "default"
            ? value.userFile === "/user.db" && value.systemFile === "/system.db"
            : value.userFile === `/app-${value.storageKey}-user.db`
                && value.systemFile === `/app-${value.storageKey}-system.db`;
        if ((value.storageKind === "generation" && !generation)
            || (value.storageKind === "legacy" && !legacy))
            context.addIssue({ code: "custom", message: "lifecycle physical target is not canonical" });
    }]))();
export const PendingTargetLifecycleJobV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "kind": [5, ["create", "fork", "cleanup"]], "jobId": LifecycleJobId, "authorityIncarnationId": __ref14, "requestId": __ref4, "operationId": __ref12, "requestSha256": __ref3, "declaredCatalogGeneration": __ref2, "expectedTarget": TargetEvidenceV1, "target": LifecyclePhysicalTargetV1, "createdAt": CanonicalInstant, "recoveryFence": [12, WriteFenceV1] }, 1], (value, context) => {
        if (value.declaredCatalogGeneration === "0")
            context.addIssue({ code: "custom", message: "lifecycle declaration generation cannot be zero" });
        if (value.kind !== "cleanup" && value.target.storageKind !== "generation")
            context.addIssue({ code: "custom", message: "new lifecycle targets must use generation storage" });
        if (value.target.appInstanceId === value.expectedTarget.appInstanceId
            || value.target.generationId === value.expectedTarget.activeGenerationId)
            context.addIssue({ code: "custom", message: "created app target must have fresh identity" });
    }]))();
export const LegacyAppLifecycleReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "kind": [5, ["create", "fork", "switch", "rename", "delete"]], "jobId": LifecycleJobId, "authorityIncarnationId": __ref14, "requestId": __ref4, "requestSha256": __ref3, "operationId": __ref12, "requestedAppInstanceId": [13, __ref0], "resultingSelectedAppInstanceId": __ref0, "completedCatalogGeneration": __ref2, "completedAt": CanonicalInstant }, 1]))();
export const AppLifecycleReceiptV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [11, "schema", [[1, LegacyAppLifecycleReceiptV1], [2, [6, { "schema": [4, 2], "kind": [5, ["create", "fork", "switch", "rename", "delete", "restore", "restore_aborted"]], "jobId": LifecycleJobId, "authorityIncarnationId": __ref14, "requestId": __ref4, "requestSha256": __ref3, "operationId": __ref12, "requestedAppInstanceId": [13, __ref0], "resultingSelectedAppInstanceId": __ref0, "completedCatalogGeneration": __ref2, "completedAt": CanonicalInstant, "resultTarget": TargetEvidenceV1, "resultDisplayName": CatalogDisplayName, "resultShellId": CatalogShellId, "initialPublication": [12, [6, { "catalogGeneration": __ref2, "target": TargetEvidenceV1, "reattestationRequestId": __ref4 }, 1]] }, 1]]]], (value, context) => {
        const explicitTarget = value.kind === "switch" || value.kind === "rename"
            || value.kind === "delete";
        if (explicitTarget !== (value.requestedAppInstanceId !== null))
            context.addIssue({ code: "custom", message: "lifecycle receipt request target is inconsistent" });
        if ((value.kind === "switch" || value.kind === "rename")
            && value.requestedAppInstanceId !== value.resultingSelectedAppInstanceId)
            context.addIssue({ code: "custom", message: "lifecycle receipt selected target is inconsistent" });
        if (value.schema === 2 && value.resultTarget.appInstanceId !== value.resultingSelectedAppInstanceId)
            context.addIssue({ code: "custom", message: "lifecycle receipt result target is inconsistent" });
        if (value.schema === 2 && value.initialPublication && value.kind !== "restore" && value.kind !== "fork")
            context.addIssue({ code: "custom", message: "only a fresh copied target may re-attest sample provenance" });
    }]))();
export const CatalogCasPublicationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "authorityIncarnationId": __ref14, "catalogGeneration": __ref2, "selectedAppInstanceId": [13, __ref0], "publishedTarget": TargetEvidenceV1 }, 1], (value, context) => {
        if (value.selectedAppInstanceId !== value.publishedTarget.appInstanceId)
            context.addIssue({
                code: "custom",
                path: ["selectedAppInstanceId"],
                message: "selected app must match the published target",
            });
    }]))();
export const CatalogGenerationEventV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "catalogGeneration": __ref2, "eventKind": [5, ["app_seed", "lease_issued", "revision_reserved", "revision_committed", "revision_abandoned", "recovery_takeover", "app_selected", "app_metadata", "backup_published"]], "appInstanceId": [13, __ref0], "operationId": [13, __ref12], "writeEpoch": __ref2, "at": CanonicalInstant, "target": [13, TargetEvidenceV1], "displayName": [13, CatalogDisplayName], "shellId": [13, CatalogShellId] }, 1], (value, context) => {
        if (value.catalogGeneration === "0")
            context.addIssue({ code: "custom", message: "catalog generation event cannot be zero" });
        const requiresOperation = value.eventKind !== "lease_issued";
        if (requiresOperation && (value.appInstanceId === null || value.operationId === null))
            context.addIssue({ code: "custom", message: "catalog event requires app and operation identity" });
        if (!requiresOperation && value.operationId !== null)
            context.addIssue({ code: "custom", message: "lease event cannot claim an operation identity" });
        if (value.eventKind === "app_seed" || value.eventKind === "app_selected") {
            if (value.target === null || value.target.appInstanceId !== value.appInstanceId)
                context.addIssue({ code: "custom", message: "app seed event requires its complete target" });
        }
        else if (value.target !== null) {
            context.addIssue({ code: "custom", message: "only app target events carry a target" });
        }
        const requiredMetadata = value.eventKind === "app_seed" || value.eventKind === "app_metadata";
        const hasMetadata = value.displayName !== null && value.shellId !== null;
        const partialMetadata = (value.displayName === null) !== (value.shellId === null);
        if (partialMetadata || (requiredMetadata && !hasMetadata)
            || (!requiredMetadata && value.eventKind !== "revision_committed" && hasMetadata))
            context.addIssue({ code: "custom", message: "catalog metadata event fields are invalid" });
    }]))();
export const CatalogRevisionReservationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "authorityIncarnationId": __ref14, "reservedCatalogGeneration": __ref2, "finalizedCatalogGeneration": [13, __ref2], "writeEpoch": __ref2, "leaseId": __ref15, "releaseId": __ref16, "finalizedWriteEpoch": [13, __ref2], "finalizedLeaseId": [13, __ref15], "finalizedReleaseId": [13, __ref16], "appInstanceId": __ref0, "activeGenerationId": __ref1, "lineageEpoch": __ref2, "revision": __ref2, "operationId": __ref12, "expectedProtectionRevision": __ref2, "expectedStateSha256": __ref3, "requestSha256": __ref3, "state": [5, ["reserved", "committed", "abandoned"]], "publishedActiveGenerationId": [13, __ref1], "publishedLineageEpoch": [13, __ref2], "stateSha256": [13, __ref3], "reservedAt": CanonicalInstant, "finalizedAt": [13, CanonicalInstant] }, 1], (value, context) => {
        if (value.revision === "0"
            || BigInt(value.expectedProtectionRevision) >= BigInt(value.revision))
            context.addIssue({ code: "custom", message: "reservation revision must advance its target" });
        if (value.state === "reserved") {
            if (value.finalizedCatalogGeneration !== null
                || value.finalizedWriteEpoch !== null
                || value.finalizedLeaseId !== null
                || value.finalizedReleaseId !== null
                || value.publishedActiveGenerationId !== null
                || value.publishedLineageEpoch !== null
                || value.stateSha256 !== null || value.finalizedAt !== null)
                context.addIssue({ code: "custom", message: "reserved catalog revision cannot be finalized" });
            return;
        }
        if (value.finalizedCatalogGeneration === null || value.finalizedAt === null
            || value.finalizedWriteEpoch === null
            || value.finalizedLeaseId === null
            || value.finalizedReleaseId === null
            || BigInt(value.finalizedCatalogGeneration) !== BigInt(value.reservedCatalogGeneration) + 1n
            || value.finalizedAt < value.reservedAt)
            context.addIssue({ code: "custom", message: "catalog reservation finalization is invalid" });
        if ((value.state === "committed"
            && (value.publishedActiveGenerationId === null
                || value.publishedLineageEpoch === null
                || value.stateSha256 === null || value.stateSha256 === value.expectedStateSha256))
            || (value.state === "abandoned"
                && (value.publishedActiveGenerationId !== null
                    || value.publishedLineageEpoch !== null || value.stateSha256 !== null)))
            context.addIssue({ code: "custom", message: "catalog reservation outcome is invalid" });
    }]))();
export const CatalogReservationRecoveryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "catalogGeneration": __ref2, "fence": WriteFenceV1, "abandonedReservation": CatalogRevisionReservationV1 }, 1], (value, context) => {
        const reservation = value.abandonedReservation;
        if (reservation.state !== "abandoned"
            || reservation.authorityIncarnationId !== value.fence.authorityIncarnationId
            || reservation.finalizedCatalogGeneration !== value.catalogGeneration
            || reservation.finalizedWriteEpoch !== value.fence.writeEpoch
            || reservation.finalizedLeaseId !== value.fence.leaseId
            || reservation.finalizedReleaseId !== value.fence.releaseId)
            context.addIssue({ code: "custom", message: "catalog recovery authority is inconsistent" });
    }]))();
