import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 0f30520414b4e8a9bdcd153eee4f4c62db5e3be0634e486f5644c6f2324f92e4; closed parse program v1.
import { standalone } from './runtime.mjs';
export const safeCount = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[8]))();
const UINT64_MAX = 18446744073709551615n;
function isUInt64Decimal(value) {
    if (!/^(?:0|[1-9][0-9]{0,19})$/.test(value))
        return false;
    try {
        return BigInt(value) <= UINT64_MAX;
    }
    catch {
        return false;
    }
}
function isCanonicalUtcInstant(value) {
    if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value))
        return false;
    const parsed = new Date(value);
    return Number.isFinite(parsed.getTime()) && parsed.toISOString() === value;
}
function isCanonicalDate(value) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(value))
        return false;
    const parsed = new Date(`${value}T00:00:00.000Z`);
    return Number.isFinite(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value;
}
function isSupportedTimeZone(value) {
    if (value.startsWith("+") || value.startsWith("-"))
        return false;
    try {
        new Intl.DateTimeFormat("en-US", { timeZone: value });
        return true;
    }
    catch {
        return false;
    }
}
function hasUniqueStrings(values) {
    return new Set(values).size === values.length;
}
function compareCanonicalStrings(left, right) {
    return left < right ? -1 : left > right ? 1 : 0;
}
function isCanonicallySorted(values) {
    return values.every((value, index) => index === 0
        || compareCanonicalStrings(values[index - 1], value) < 0);
}
export const DAILY_HOME_SOURCE_IDS_V1 = [
    "automation_notification",
    "due_record",
    "favorite_record",
    "recently_changed_record",
    "recently_opened_record",
    "recovery_notice",
    "saved_view",
];
export const DailyHomeSourceIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["automation_notification", "due_record", "favorite_record", "recently_changed_record", "recently_opened_record", "recovery_notice", "saved_view"]]))();
export const DAILY_HOME_SECTION_IDS_V1 = [
    "needs_attention",
    "due_today",
    "continue",
    "pinned",
    "recently_opened",
];
export const DailyHomeSectionIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["needs_attention", "due_today", "continue", "pinned", "recently_opened"]]))();
export const CompletenessGapV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "sourceId": DailyHomeSourceIdV1, "reason": [5, ["unavailable", "timeout", "invalid_source", "limit"]], "retryable": [2] }, 1]))();
export const ExactCompletenessV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "kind": [4, "exact"], "total": safeCount }, 1]))();
export const PartialCompletenessV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "kind": [4, "partial"], "knownMinimum": safeCount, "gaps": [7, CompletenessGapV1, [1], [7]] }, 1], (value, ctx) => {
        const ids = value.gaps.map(gap => gap.sourceId);
        if (!hasUniqueStrings(ids)) {
            ctx.addIssue({ code: "custom", path: ["gaps"], message: "completeness gaps must name unique sources" });
        }
    }]))();
export const CompletenessV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [ExactCompletenessV1, PartialCompletenessV1]]))();
export const DailyHomeCursorStringV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[1, 4096, true], [3, /^dcur_[A-Za-z0-9_-]{16,4026}\.[0-9a-f]{64}$/, "regex"]]]))();
export const ContinuationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "kind", [["end", [6, { "kind": [4, "end"] }, 1]], ["cursor", [6, { "kind": [4, "cursor"], "cursor": DailyHomeCursorStringV1 }, 1]]]]))();
export const CountSetV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "sourceOccurrences": CompletenessV1, "renderedUnique": CompletenessV1 }, 1], (value, ctx) => {
        const sourceMinimum = value.sourceOccurrences.kind === "exact"
            ? value.sourceOccurrences.total : value.sourceOccurrences.knownMinimum;
        const renderedMinimum = value.renderedUnique.kind === "exact"
            ? value.renderedUnique.total : value.renderedUnique.knownMinimum;
        if (renderedMinimum > sourceMinimum) {
            ctx.addIssue({
                code: "custom",
                path: ["renderedUnique"],
                message: "rendered unique count cannot exceed source occurrence count",
            });
        }
    }]))();
export const TableSemanticIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[23]))();
export const FieldSemanticIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[24]))();
export const RowIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[5]))();
export const AutomationIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^auto_[0-9a-f]{32}$/, "regex"]]]))();
export const SavedViewIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^view_[0-9a-f]{32}$/, "regex"]]]))();
export const DailySourceProfileIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^dsp_[a-z2-7]{26}$/, "regex"]]]))();
export const InboxSourceKeyV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^inb_[a-z2-7]{26}$/, "regex"]]]))();
export const SourceGenerationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[2]))();
export const AppInstanceIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[1]))();
export const Sha256V1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^sha256:[0-9a-f]{64}$/, "regex"]]]))();
export const CanonicalUtcInstantV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, []], isCanonicalUtcInstant, "canonical UTC millisecond instant required"]))();
export const CanonicalLocalDateV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, []], isCanonicalDate, "canonical local date required"]))();
export const CanonicalTimeZoneV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[22], isSupportedTimeZone, "recognized IANA timezone required"]))();
export const CompletionRuleV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [[6, { "kind": [4, "none"] }, 1], [6, { "kind": [4, "boolean"], "fieldId": FieldSemanticIdV1, "completeValue": [4, true] }, 1], [15, [6, { "kind": [4, "enum"], "fieldId": FieldSemanticIdV1, "completeValue": __standalonePrograms[6], "terminalValues": __standalonePrograms[25] }, 1], (value, ctx) => {
                if (!hasUniqueStrings(value.terminalValues)) {
                    ctx.addIssue({ code: "custom", path: ["terminalValues"], message: "terminal values must be unique" });
                }
                if (!value.terminalValues.includes(value.completeValue)) {
                    ctx.addIssue({
                        code: "custom",
                        path: ["completeValue"],
                        message: "complete value must be one declared terminal value",
                    });
                }
            }]]]))();
export const DailySourceProfileV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "profileId": DailySourceProfileIdV1, "tableId": TableSemanticIdV1, "labelFieldId": FieldSemanticIdV1, "dueFieldId": FieldSemanticIdV1, "completion": CompletionRuleV1, "enabled": [2], "labelSnapshot": [12, __standalonePrograms[26]], "dueLabelSnapshot": [12, __standalonePrograms[26]] }, 1]))();
export const DailySourceLibraryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "revision": safeCount, "profiles": [7, DailySourceProfileV1, undefined, [32]] }, 1], (value, ctx) => {
        const profileIds = value.profiles.map(profile => profile.profileId);
        if (!hasUniqueStrings(profileIds)) {
            ctx.addIssue({ code: "custom", path: ["profiles"], message: "profile IDs must be unique" });
        }
        const enabledTables = value.profiles.filter(profile => profile.enabled).map(profile => profile.tableId);
        if (!hasUniqueStrings(enabledTables)) {
            ctx.addIssue({
                code: "custom",
                path: ["profiles"],
                message: "only one enabled primary profile is allowed per table",
            });
        }
    }]))();
export const SourceStatusV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["ready", "partial", "unavailable"]]))();
export const DailyHomeProfileResolutionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "readyProfileIds": [7, DailySourceProfileIdV1, undefined, [32]], "issueProfileIds": [7, DailySourceProfileIdV1, undefined, [32]] }, 1], (value, ctx) => {
        const ready = value.readyProfileIds;
        const issues = value.issueProfileIds;
        if (!isCanonicallySorted(ready) || !isCanonicallySorted(issues)
            || ready.some(id => issues.includes(id))) {
            ctx.addIssue({
                code: "custom",
                message: "profile resolution must be a disjoint canonical partition",
            });
        }
    }]))();
export const SourceWatermarkV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "sourceId": DailyHomeSourceIdV1, "watermark": __standalonePrograms[27], "status": SourceStatusV1, "statusEpoch": __standalonePrograms[13] }, 1], (value, ctx) => {
        if (value.status === "unavailable" && value.watermark !== null) {
            ctx.addIssue({ code: "custom", path: ["watermark"], message: "unavailable source has no watermark" });
        }
        if (value.status === "ready" && value.watermark === null) {
            ctx.addIssue({ code: "custom", path: ["watermark"], message: "ready source requires a watermark" });
        }
        if (value.sourceId === "recovery_notice" && value.status !== "unavailable") {
            ctx.addIssue({
                code: "custom", path: ["status"],
                message: "D0 recovery source remains unavailable until the Recovery contract is integrated",
            });
        }
    }]))();
export const SnapshotBasisV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "appInstanceId": AppInstanceIdV1, "activeGenerationId": SourceGenerationV1, "schemaHead": __standalonePrograms[13], "profileRevision": safeCount, "profileDigest": Sha256V1, "profileResolution": DailyHomeProfileResolutionV1, "libraryRevision": safeCount, "dispositionWatermark": __standalonePrograms[22], "sourceWatermarks": [7, SourceWatermarkV1, undefined, undefined, [7]], "localDate": CanonicalLocalDateV1, "timeZone": CanonicalTimeZoneV1, "rankingVersion": [4, "daily-rank-v1"], "projectionValidUntil": CanonicalUtcInstantV1 }, 1], (value, ctx) => {
        const ids = value.sourceWatermarks.map(source => source.sourceId);
        if (!hasUniqueStrings(ids)) {
            ctx.addIssue({ code: "custom", path: ["sourceWatermarks"], message: "source basis must be unique" });
        }
        const sorted = [...ids].sort(compareCanonicalStrings);
        if (ids.some((id, index) => id !== sorted[index])) {
            ctx.addIssue({ code: "custom", path: ["sourceWatermarks"], message: "source basis must be sorted" });
        }
        if (ids.some((id, index) => id !== DAILY_HOME_SOURCE_IDS_V1[index])) {
            ctx.addIssue({ code: "custom", path: ["sourceWatermarks"], message: "source basis must contain every source" });
        }
    }]))();
export const DailyHomeAdapterContinuationsV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [7, [6, { "sourceId": DailyHomeSourceIdV1, "continuation": __standalonePrograms[27] }, 1], undefined, undefined, [7]], (value, ctx) => {
        if (value.some((entry, index) => entry.sourceId !== DAILY_HOME_SOURCE_IDS_V1[index])) {
            ctx.addIssue({
                code: "custom",
                message: "cursor must bind every adapter continuation in canonical source order",
            });
        }
    }]))();
export const DailyHomePageScopeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "kind", [["source", [6, { "kind": [4, "source"], "sourceId": DailyHomeSourceIdV1, "pageSize": __standalonePrograms[28] }, 1]], ["section", [6, { "kind": [4, "section"], "sectionId": DailyHomeSectionIdV1, "pageSize": __standalonePrograms[28] }, 1]]]]))();
export const DailyHomeCursorStateV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "adapterContinuations": DailyHomeAdapterContinuationsV1, "pageScope": DailyHomePageScopeV1 }, 1]))();
export const DailyHomeCursorPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "appInstanceId": AppInstanceIdV1, "activeGenerationId": SourceGenerationV1, "basisDigest": Sha256V1, "adapterContinuations": DailyHomeAdapterContinuationsV1, "pageScope": DailyHomePageScopeV1, "rankingVersion": [4, "daily-rank-v1"], "localDate": CanonicalLocalDateV1, "timeZone": CanonicalTimeZoneV1, "projectionValidUntil": CanonicalUtcInstantV1 }, 1]))();
export const DailyHomeProjectionAuthorityV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "appInstanceId": AppInstanceIdV1, "activeGenerationId": SourceGenerationV1, "schemaHead": __standalonePrograms[13], "sourceLibrary": DailySourceLibraryV1, "profileResolution": DailyHomeProfileResolutionV1, "dispositionWatermark": __standalonePrograms[22], "sourceWatermarks": [7, SourceWatermarkV1, undefined, undefined, [7]], "localDate": CanonicalLocalDateV1, "timeZone": CanonicalTimeZoneV1, "projectionValidUntil": CanonicalUtcInstantV1 }, 1], (value, ctx) => {
        const ready = value.profileResolution.readyProfileIds;
        const issues = value.profileResolution.issueProfileIds;
        const enabled = value.sourceLibrary.profiles
            .filter(profile => profile.enabled).map(profile => profile.profileId).sort(compareCanonicalStrings);
        const resolved = [...ready, ...issues].sort(compareCanonicalStrings);
        if (enabled.length !== resolved.length || enabled.some((id, index) => id !== resolved[index])) {
            ctx.addIssue({ code: "custom", path: ["profileResolution"], message: "profile resolution must cover every enabled profile" });
        }
        const sourceIds = value.sourceWatermarks.map(source => source.sourceId);
        if (sourceIds.some((id, index) => id !== DAILY_HOME_SOURCE_IDS_V1[index])) {
            ctx.addIssue({ code: "custom", path: ["sourceWatermarks"], message: "authority must contain every source in canonical order" });
        }
        const due = value.sourceWatermarks.find(source => source.sourceId === "due_record");
        if ((ready.length === 0 || issues.length > 0) && due?.status === "ready") {
            ctx.addIssue({ code: "custom", path: ["sourceWatermarks"], message: "due source readiness contradicts profile resolution" });
        }
    }]))();
export const TrustedRouteV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "kind", [["record", [6, { "kind": [4, "record"], "tableId": TableSemanticIdV1, "rowId": RowIdV1 }, 1]], ["automation", [6, { "kind": [4, "automation"], "automationId": AutomationIdV1 }, 1]], ["saved_view", [6, { "kind": [4, "saved_view"], "savedViewId": SavedViewIdV1 }, 1]], ["setup", [6, { "kind": [4, "setup"], "area": [5, ["daily_sources", "automations"]] }, 1]], ["inbox", [6, { "kind": [4, "inbox"] }, 1]]]]))();
export const InboxActionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["open", "setup", "fix", "complete", "snooze", "dismiss"]]))();
export const InboxItemV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "sourceKey": InboxSourceKeyV1, "sourceGeneration": SourceGenerationV1, "kind": [5, ["due_record", "automation_notification"]], "title": __standalonePrograms[29], "summary": [12, [0, [[0, 1, true], [1, 500, true]]]], "severity": [5, ["critical", "high", "normal", "low"]], "attentionAt": CanonicalUtcInstantV1, "dueAt": [12, CanonicalUtcInstantV1], "expectedCanonicalRevision": [12, [14, [0, []], isUInt64Decimal, "canonical uint64 revision required"]], "dispositionRevision": safeCount, "route": TrustedRouteV1, "actions": [7, InboxActionV1, [1], [4]] }, 1], (value, ctx) => {
        if (!hasUniqueStrings(value.actions)) {
            ctx.addIssue({ code: "custom", path: ["actions"], message: "Inbox actions must be unique" });
        }
        const setupRoute = value.route.kind === "setup";
        if (setupRoute !== value.actions.every(action => action === "setup" || action === "fix")) {
            ctx.addIssue({ code: "custom", path: ["actions"], message: "actions must match setup navigation" });
        }
        if (setupRoute) {
            const expectedArea = value.kind === "due_record" ? "daily_sources" : "automations";
            if (value.route.kind === "setup" && value.route.area !== expectedArea) {
                ctx.addIssue({ code: "custom", path: ["route"], message: "setup route must match source kind" });
            }
        }
        if (!setupRoute && (value.actions[0] !== "open" || value.actions.includes("setup") || value.actions.includes("fix")
            || (value.kind !== "due_record" && value.actions.includes("complete")))) {
            ctx.addIssue({ code: "custom", path: ["actions"], message: "actions must match the canonical source capability" });
        }
        const expectedRoute = value.kind === "due_record" ? "record" : "automation";
        if (!setupRoute && value.route.kind !== expectedRoute) {
            ctx.addIssue({ code: "custom", path: ["route"], message: "route must match source kind" });
        }
    }]))();
export const InboxDispositionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "sourceKey": InboxSourceKeyV1, "sourceGeneration": SourceGenerationV1, "revision": [1, [[5], [0, 0, true], __standalonePrograms[7], [1, 9007199254740991, true], [0, 0, false]]], "requestId": [0, [[3, /^req_[a-z2-7]{26}$/, "regex"]]], "state": [5, ["active", "snoozed", "dismissed"]], "until": [13, CanonicalUtcInstantV1], "localDate": [13, CanonicalLocalDateV1], "timeZone": [13, CanonicalTimeZoneV1] }, 1], (value, context) => {
        const snoozed = value.state === "snoozed";
        if (snoozed !== (value.until !== null) || snoozed !== (value.localDate !== null) || snoozed !== (value.timeZone !== null))
            context.addIssue({ code: "custom", message: "Snooze requires an exact local-calendar boundary; other dispositions have none" });
    }]))();
export const DailyHomeRecordProjectionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "kind": [4, "record_projection"], "sourceId": [5, ["favorite_record", "recently_changed_record", "recently_opened_record"]], "sourceKey": InboxSourceKeyV1, "sourceGeneration": SourceGenerationV1, "tableId": TableSemanticIdV1, "rowId": RowIdV1, "title": __standalonePrograms[29], "updatedAt": CanonicalUtcInstantV1, "openedAt": [12, CanonicalUtcInstantV1], "favoriteOrder": [12, safeCount], "route": [6, { "kind": [4, "record"], "tableId": TableSemanticIdV1, "rowId": RowIdV1 }, 1] }, 1], (value, ctx) => {
        if (value.route.tableId !== value.tableId || value.route.rowId !== value.rowId) {
            ctx.addIssue({ code: "custom", path: ["route"], message: "record route must bind the projected record" });
        }
        if ((value.sourceId === "recently_opened_record") !== (value.openedAt !== undefined)) {
            ctx.addIssue({ code: "custom", path: ["openedAt"], message: "opened time must match recent-open source" });
        }
        if ((value.sourceId === "favorite_record") !== (value.favoriteOrder !== undefined)) {
            ctx.addIssue({ code: "custom", path: ["favoriteOrder"], message: "favorite order must match favorite source" });
        }
    }]))();
export const DailyHomeSavedViewProjectionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "kind": [4, "saved_view_projection"], "sourceId": [4, "saved_view"], "sourceKey": InboxSourceKeyV1, "sourceGeneration": SourceGenerationV1, "savedViewId": SavedViewIdV1, "title": __standalonePrograms[29], "route": [6, { "kind": [4, "saved_view"], "savedViewId": SavedViewIdV1 }, 1] }, 1], (value, ctx) => {
        if (value.route.savedViewId !== value.savedViewId) {
            ctx.addIssue({ code: "custom", path: ["route"], message: "view route must bind the projected view" });
        }
    }]))();
export const DailyHomeItemV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [InboxItemV1, DailyHomeRecordProjectionV1, DailyHomeSavedViewProjectionV1]]))();
function renderedIdentity(item) {
    if (item.kind === "record_projection")
        return `record:${item.tableId}:${item.rowId}`;
    if (item.kind === "saved_view_projection")
        return `view:${item.savedViewId}`;
    if (item.route.kind === "record")
        return `record:${item.route.tableId}:${item.route.rowId}`;
    if (item.route.kind === "automation")
        return `automation:${item.route.automationId}`;
    return `occurrence:${item.sourceKey}\u0000${item.sourceGeneration}`;
}
export const DailyItemPageV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "items": [7, DailyHomeItemV1, undefined, [20]], "returned": [1, [[5], [0, 0, true], [1, 20, true], __standalonePrograms[7], [1, 9007199254740991, true]]], "counts": CountSetV1, "continuation": ContinuationV1 }, 1], (value, ctx) => {
        if (value.returned !== value.items.length) {
            ctx.addIssue({ code: "custom", path: ["returned"], message: "returned must equal items length" });
        }
        const sourceMinimum = value.counts.sourceOccurrences.kind === "exact"
            ? value.counts.sourceOccurrences.total : value.counts.sourceOccurrences.knownMinimum;
        if (value.returned > sourceMinimum) {
            ctx.addIssue({ code: "custom", path: ["returned"], message: "returned exceeds declared counts" });
        }
    }]))();
export const DailyHomeSourceSnapshotV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "sourceId": DailyHomeSourceIdV1, "watermark": __standalonePrograms[27], "status": SourceStatusV1, "statusEpoch": __standalonePrograms[13], "page": DailyItemPageV1 }, 1], (value, ctx) => {
        const sourceCounts = value.page.counts.sourceOccurrences;
        const renderedCounts = value.page.counts.renderedUnique;
        const bothExact = sourceCounts.kind === "exact" && renderedCounts.kind === "exact";
        const bothPartial = sourceCounts.kind === "partial" && renderedCounts.kind === "partial";
        const gapsMatchSource = bothPartial
            && sourceCounts.gaps.every(gap => gap.sourceId === value.sourceId)
            && renderedCounts.gaps.every(gap => gap.sourceId === value.sourceId);
        const gapsMatchEachOther = bothPartial
            && sourceCounts.gaps.length === renderedCounts.gaps.length
            && sourceCounts.gaps.every((gap, index) => {
                const other = renderedCounts.gaps[index];
                return other !== undefined && other.sourceId === gap.sourceId
                    && other.reason === gap.reason && other.retryable === gap.retryable;
            });
        const gapPolicyValid = bothPartial && sourceCounts.gaps.every(gap => gap.reason === "invalid_source" ? !gap.retryable : gap.retryable);
        const unavailableReasonValid = bothPartial && sourceCounts.gaps.length === 1
            && (sourceCounts.gaps[0].reason === "unavailable"
                || sourceCounts.gaps[0].reason === "invalid_source");
        if (value.status === "ready" && (!bothExact || value.watermark === null)) {
            ctx.addIssue({
                code: "custom", path: ["status"],
                message: "ready source requires exact counts and a watermark",
            });
        }
        if (value.status === "partial"
            && (!bothPartial || !gapsMatchSource || !gapsMatchEachOther || !gapPolicyValid)) {
            ctx.addIssue({
                code: "custom", path: ["status"],
                message: "partial source requires source-local partial completeness",
            });
        }
        if (value.status === "unavailable" && (!bothPartial || !gapsMatchSource || !gapsMatchEachOther
            || !gapPolicyValid || !unavailableReasonValid
            || sourceCounts.kind !== "partial" || sourceCounts.knownMinimum !== 0
            || renderedCounts.kind !== "partial" || renderedCounts.knownMinimum !== 0
            || value.watermark !== null || value.page.returned !== 0
            || value.page.items.length !== 0 || value.page.continuation.kind !== "end")) {
            ctx.addIssue({
                code: "custom", path: ["status"],
                message: "unavailable source requires an empty source-local partial page",
            });
        }
        const occurrenceKeys = value.page.items.map(item => `${item.sourceKey}\u0000${item.sourceGeneration}`);
        const renderedKeys = new Set(value.page.items.map(renderedIdentity));
        if (!hasUniqueStrings(occurrenceKeys)) {
            ctx.addIssue({
                code: "custom", path: ["page", "items"],
                message: "source page occurrence identities must be unique",
            });
        }
        if (value.page.continuation.kind === "end" && bothExact
            && (sourceCounts.total !== value.page.items.length
                || renderedCounts.total !== renderedKeys.size)) {
            ctx.addIssue({
                code: "custom", path: ["page", "counts"],
                message: "complete source-page counts must match returned identities",
            });
        }
        for (let index = 0; index < value.page.items.length; index++) {
            const item = value.page.items[index];
            const itemSource = item.kind === "record_projection" || item.kind === "saved_view_projection"
                ? item.sourceId
                : item.kind;
            if (itemSource !== value.sourceId) {
                ctx.addIssue({
                    code: "custom",
                    path: ["page", "items", index],
                    message: "source page item must match source ID",
                });
            }
        }
    }]))();
const SECTION_ORDER = DAILY_HOME_SECTION_IDS_V1;
export const DailyHomeSectionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "sectionId": DailyHomeSectionIdV1, "page": DailyItemPageV1 }, 1]))();
export const DailyHomeSnapshotV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "generatedAt": CanonicalUtcInstantV1, "basis": SnapshotBasisV1, "snapshotDigest": Sha256V1, "configurationStatus": [5, ["ready", "needs_setup", "partial"]], "sources": [7, DailyHomeSourceSnapshotV1, undefined, undefined, [7]], "sections": [7, DailyHomeSectionV1, undefined, undefined, [5]], "aggregateCounts": CountSetV1 }, 1], (value, ctx) => {
        const sourceIds = value.sources.map(source => source.sourceId);
        if (!hasUniqueStrings(sourceIds)) {
            ctx.addIssue({ code: "custom", path: ["sources"], message: "snapshot sources must be unique" });
        }
        if (sourceIds.some((id, index) => id !== DAILY_HOME_SOURCE_IDS_V1[index])) {
            ctx.addIssue({ code: "custom", path: ["sources"], message: "snapshot must contain every source in canonical order" });
        }
        const basisBySource = new Map(value.basis.sourceWatermarks.map(source => [source.sourceId, source]));
        if (basisBySource.size !== value.sources.length || value.sources.some(source => {
            const basis = basisBySource.get(source.sourceId);
            return !basis || basis.watermark !== source.watermark
                || basis.status !== source.status || basis.statusEpoch !== source.statusEpoch;
        })) {
            ctx.addIssue({
                code: "custom", path: ["sources"],
                message: "snapshot sources must match the complete basis vector",
            });
        }
        if (value.configurationStatus === "ready"
            && value.sources.some(source => source.status !== "ready")) {
            ctx.addIssue({
                code: "custom", path: ["configurationStatus"],
                message: "ready configuration cannot contain partial sources",
            });
        }
        const sectionIds = value.sections.map(section => section.sectionId);
        if (!hasUniqueStrings(sectionIds)) {
            ctx.addIssue({ code: "custom", path: ["sections"], message: "snapshot sections must be unique" });
        }
        if (sectionIds.some((id, index) => id !== SECTION_ORDER[index])) {
            ctx.addIssue({ code: "custom", path: ["sections"], message: "snapshot must contain every section" });
        }
        const order = sectionIds.map(id => SECTION_ORDER.indexOf(id));
        if (order.some((position, index) => index > 0 && position <= order[index - 1])) {
            ctx.addIssue({ code: "custom", path: ["sections"], message: "snapshot sections must use canonical order" });
        }
        if (new Date(value.generatedAt).getTime() >= new Date(value.basis.projectionValidUntil).getTime()) {
            ctx.addIssue({
                code: "custom",
                path: ["basis", "projectionValidUntil"],
                message: "projection validity must be after generation",
            });
        }
    }]))();
export const __hook0 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "kind": [4, "enum"], "fieldId": FieldSemanticIdV1, "completeValue": __standalonePrograms[6], "terminalValues": __standalonePrograms[25] }, 1], (value, ctx) => {
        if (!hasUniqueStrings(value.terminalValues)) {
            ctx.addIssue({ code: "custom", path: ["terminalValues"], message: "terminal values must be unique" });
        }
        if (!value.terminalValues.includes(value.completeValue)) {
            ctx.addIssue({
                code: "custom",
                path: ["completeValue"],
                message: "complete value must be one declared terminal value",
            });
        }
    }]))();
export const __hook1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, []], isUInt64Decimal, "canonical uint64 revision required"]))();
