import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: ddbd4842f59c2cd432c7ff5f16054fba4898e163b85c72a02dfc600fd49f4aa3; closed parse program v1.
import { standalone } from './runtime.mjs';
import { AppInstanceId as __ref0 } from './index.mjs';
import { Sha256 as __ref1 } from './index.mjs';
export const ImportAcquisitionLimitsSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "maxDataRows": [4, 5000], "maxMappedColumns": [4, 20], "maxDecodedCellBytes": [4, 16384], "maxDecodedCellsBytes": [4, 33554432], "maxDelimitedSourceBytes": [4, 16777216], "maxPasteSourceBytes": [4, 8388608], "maxCompressedXlsxBytes": [4, 26214400], "maxExpandedXlsxBytes": [4, 104857600], "maxXlsxEntries": [4, 2000], "maxParseMilliseconds": [4, 8000], "maxChunkRows": [4, 250], "maxChunkBytes": [4, 1048576] }, 1]))();
export const IMPORT_ACQUISITION_LIMITS = Object.freeze({
    maxDataRows: 5_000,
    maxMappedColumns: 20,
    maxDecodedCellBytes: 16 * 1024,
    maxDecodedCellsBytes: 32 * 1024 * 1024,
    maxDelimitedSourceBytes: 16 * 1024 * 1024,
    maxPasteSourceBytes: 8 * 1024 * 1024,
    maxCompressedXlsxBytes: 25 * 1024 * 1024,
    maxExpandedXlsxBytes: 100 * 1024 * 1024,
    maxXlsxEntries: 2_000,
    maxParseMilliseconds: 8_000,
    maxChunkRows: 250,
    maxChunkBytes: 1024 * 1024,
});
export const ImportSessionIdSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^import_[a-z2-7]{26}$/, "regex"]]]))();
export const ImportSheetIdSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^[a-z][a-z0-9_-]{0,63}$/, "regex"]]]))();
export const ImportSourceKindSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["csv", "xlsx", "paste", "tsv_compat", "json_compat"]]))();
export const ImportSourceRangeSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "rows": [1, [[5], [0, 0, true], [1, 5001, true]]], "columns": [1, [[5], [0, 0, true], [1, 20, true]]] }, 1]))();
export const ImportSheetDescriptorSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "sheetId": ImportSheetIdSchema, "label": __standalonePrograms[9], "visibility": [5, ["visible", "hidden", "very_hidden"]], "range": ImportSourceRangeSchema }, 1]))();
export const ImportSourceDescriptorSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "version": [4, 1], "sessionId": ImportSessionIdSchema, "appInstanceId": __ref0, "kind": ImportSourceKindSchema, "sourceDigest": __ref1, "sheets": [7, ImportSheetDescriptorSchema, [1], [2000]], "limits": ImportAcquisitionLimitsSchema }, 1], (source, ctx) => {
        if ((source.kind === "csv" || source.kind === "paste") && source.sheets.length !== 1)
            ctx.addIssue({ code: "custom", message: "delimited sources expose one synthetic range" });
        if ((source.kind === "csv" || source.kind === "paste")
            && source.sheets[0]?.visibility !== "visible")
            ctx.addIssue({ code: "custom", message: "a synthetic range must be visible" });
        if (new Set(source.sheets.map(sheet => sheet.sheetId)).size !== source.sheets.length)
            ctx.addIssue({ code: "custom", message: "sheet identifiers must be unique" });
    }]))();
export const ImportRawCellSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[1, 16384, true]]]))();
export const ImportParserChunkSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "sessionId": ImportSessionIdSchema, "cursor": __standalonePrograms[18], "startRow": __standalonePrograms[52], "rows": [7, [7, ImportRawCellSchema, [1], [20]], [1], [250]], "nextCursor": [13, [1, [[5], [0, 0, false], [1, 5000, true]]]], "serializedBytes": [1, [[5], [0, 0, false], [1, 1048576, true]]] }, 1]))();
export const ImportWarningCountSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[18]))();
export const ImportWarningTotalsSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "warnings": ImportWarningCountSchema, "warningReasons": [6, { "trimmed_whitespace": ImportWarningCountSchema, "leading_zero_identifier": ImportWarningCountSchema, "enum_case_normalized": ImportWarningCountSchema }, 1] }, 1], (totals, ctx) => {
        const classified = Object.values(totals.warningReasons)
            .reduce((sum, count) => sum + count, 0);
        if (classified !== totals.warnings)
            ctx.addIssue({ code: "custom", message: "warning reason totals do not balance" });
    }]))();
