// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: ddbd4842f59c2cd432c7ff5f16054fba4898e163b85c72a02dfc600fd49f4aa3; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../import-staging';
export declare const ImportAcquisitionLimitsSchema: Compiled<typeof import("../import-staging").ImportAcquisitionLimitsSchema>;
export type ImportAcquisitionLimits=import("../import-staging").ImportAcquisitionLimits;
export declare const IMPORT_ACQUISITION_LIMITS: typeof import("../import-staging").IMPORT_ACQUISITION_LIMITS;
export declare const ImportSessionIdSchema: Compiled<typeof import("../import-staging").ImportSessionIdSchema>;
export declare const ImportSheetIdSchema: Compiled<typeof import("../import-staging").ImportSheetIdSchema>;
export declare const ImportSourceKindSchema: Compiled<typeof import("../import-staging").ImportSourceKindSchema>;
export declare const ImportSourceRangeSchema: Compiled<typeof import("../import-staging").ImportSourceRangeSchema>;
export declare const ImportSheetDescriptorSchema: Compiled<typeof import("../import-staging").ImportSheetDescriptorSchema>;
export declare const ImportSourceDescriptorSchema: Compiled<typeof import("../import-staging").ImportSourceDescriptorSchema>;
export type ImportHeaderChoice=import("../import-staging").ImportHeaderChoice;
export type ImportDateRule=import("../import-staging").ImportDateRule;
export type ImportNumberRule=import("../import-staging").ImportNumberRule;
export type ExistingTableImportMapping=import("../import-staging").ExistingTableImportMapping;
export type ExistingTableImportMode=import("../import-staging").ExistingTableImportMode;
export type ConfigureExistingTableImport=import("../import-staging").ConfigureExistingTableImport;
export declare const ImportRawCellSchema: Parser<unknown>;
export declare const ImportParserChunkSchema: Compiled<typeof import("../import-staging").ImportParserChunkSchema>;
export declare const ImportWarningCountSchema: Parser<unknown>;
export declare const ImportWarningTotalsSchema: Compiled<typeof import("../import-staging").ImportWarningTotalsSchema>;
export type ImportSessionId=import("../import-staging").ImportSessionId;
export type ImportSourceKind=import("../import-staging").ImportSourceKind;
export type ImportSourceDescriptor=import("../import-staging").ImportSourceDescriptor;
export type ImportParserChunk=import("../import-staging").ImportParserChunk;
