import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: c0c17def6eae046e4d969bbe455a49a3384660055cceffa3ebf67b8babca8abc; closed parse program v1.
import { standalone } from './runtime.mjs';
import { ImportSheetIdSchema as __ref0 } from './import-staging.mjs';
import { Sha256 as __ref1 } from './index.mjs';
import { AppInstanceId as __ref2 } from './index.mjs';
import { ImportSessionIdSchema as __ref3 } from './import-staging.mjs';
import { ImportSourceDescriptorSchema as __ref4 } from './import-staging.mjs';
import { ImportParserChunkSchema as __ref5 } from './import-staging.mjs';
export * from "./import-staging.mjs";
export const ImportSheetChoiceSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "sheetId": __ref0 }, 1]))();
export const ImportRangeChoiceSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "sheetId": __ref0, "startRow": __standalonePrograms[52], "endRow": __standalonePrograms[52], "startColumn": __standalonePrograms[53], "endColumn": __standalonePrograms[53] }, 1], (range, ctx) => {
        if (range.endRow < range.startRow)
            ctx.addIssue({ code: "custom", message: "range rows must be ordered" });
        if (range.endColumn < range.startColumn)
            ctx.addIssue({ code: "custom", message: "range columns must be ordered" });
        if (range.endRow - range.startRow + 1 > 5_001)
            ctx.addIssue({ code: "custom", message: "range exceeds the source-row ceiling" });
        if (range.endColumn - range.startColumn + 1 > 20)
            ctx.addIssue({ code: "custom", message: "range exceeds the mapped-column ceiling" });
    }]))();
export const ImportHeaderChoiceSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "mode", [["header", [6, { "mode": [4, "header"], "sourceRow": __standalonePrograms[52] }, 1]], ["no_header", [6, { "mode": [4, "no_header"] }, 1]]]]))();
export const ImportDateRuleSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "kind", [["iso", [6, { "kind": [4, "iso"] }, 1]], ["ordered", [6, { "kind": [4, "ordered"], "order": [5, ["mdy", "dmy"]], "separator": [5, ["/", "-"]] }, 1]]]]))();
export const ImportNumberRuleSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "grammar": [5, ["ungrouped_dot_decimal", "comma_grouped_dot_decimal", "dot_grouped_comma_decimal"]], "affix": [10, [[3], [6, { "symbol": [5, ["$", "€", "£", "¥"]], "position": [5, ["prefix", "suffix"]] }, 1]]], "percentScale": [5, ["none", "zero_to_one", "zero_to_hundred"]] }, 1]))();
export const HeaderCandidateReasonSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["no_non_blank_row", "first_non_blank_row", "all_labels_present", "contains_blank_label", "labels_unique", "duplicate_labels", "labels_textual", "contains_non_text_label", "data_shape_contrast", "no_data_shape_contrast", "no_following_data"]]))();
export const HeaderCandidateSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "recommendedRow": [13, [1, [[5], [0, 0, false], [1, 10, true]]]], "confidence": [5, ["high", "low", "none"]], "reasons": [7, HeaderCandidateReasonSchema, [1], [5]] }, 1], (candidate, ctx) => {
        if ((candidate.recommendedRow === null) !== (candidate.confidence === "none"))
            ctx.addIssue({ code: "custom", message: "empty header candidates use none confidence" });
        if (new Set(candidate.reasons).size !== candidate.reasons.length)
            ctx.addIssue({ code: "custom", message: "header candidate reasons must be unique" });
    }]))();
export const ImportSkipCodeSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["above_header", "blank_row", "user_skipped", "duplicate_combined", "duplicate_skipped", "no_change", "unmapped_row"]]))();
export const SourceRowOrdinalSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[52]))();
export const ImportIssueIdSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^issue_[a-zA-Z0-9_-]{1,64}$/, "regex"]]]))();
export const SourceRowDispositionSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "kind", [["create", [6, { "sourceRow": SourceRowOrdinalSchema, "kind": [4, "create"] }, 1]], ["update", [6, { "sourceRow": SourceRowOrdinalSchema, "kind": [4, "update"] }, 1]], ["skip", [6, { "sourceRow": SourceRowOrdinalSchema, "kind": [4, "skip"], "reasonCode": ImportSkipCodeSchema }, 1]], ["blocked", [6, { "sourceRow": SourceRowOrdinalSchema, "kind": [4, "blocked"], "issueIds": [7, ImportIssueIdSchema, [1], [100]] }, 1]]]]))();
export const ImportSourceDispositionLedgerSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [7, SourceRowDispositionSchema, undefined, [5000]], (rows, ctx) => {
        if (new Set(rows.map(row => row.sourceRow)).size !== rows.length)
            ctx.addIssue({ code: "custom", message: "each source row needs exactly one disposition" });
    }]))();
export const BoundedImportCountSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[18]))();
export const ImportSkipReasonCountsSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "above_header": BoundedImportCountSchema, "blank_row": BoundedImportCountSchema, "user_skipped": BoundedImportCountSchema, "duplicate_combined": BoundedImportCountSchema, "duplicate_skipped": BoundedImportCountSchema, "no_change": BoundedImportCountSchema, "unmapped_row": BoundedImportCountSchema }, 1]))();
export const SourceDispositionTotalsSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "sourceRows": BoundedImportCountSchema, "createRows": BoundedImportCountSchema, "updateRows": BoundedImportCountSchema, "skipRows": BoundedImportCountSchema, "blockedRows": BoundedImportCountSchema, "skipReasons": ImportSkipReasonCountsSchema }, 1], (totals, ctx) => {
        if (totals.sourceRows !== totals.createRows + totals.updateRows
            + totals.skipRows + totals.blockedRows)
            ctx.addIssue({ code: "custom", message: "source disposition totals do not balance" });
        const classifiedSkips = Object.values(totals.skipReasons)
            .reduce((sum, count) => sum + count, 0);
        if (classifiedSkips !== totals.skipRows)
            ctx.addIssue({ code: "custom", message: "skip reason totals do not balance" });
    }]))();
export const MutationTotalsSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "primaryTargetCreates": BoundedImportCountSchema, "primaryTargetUpdates": BoundedImportCountSchema, "auxiliaryRelatedCreates": BoundedImportCountSchema, "changedCount": BoundedImportCountSchema }, 1], (totals, ctx) => {
        if (totals.changedCount !== totals.primaryTargetCreates
            + totals.primaryTargetUpdates + totals.auxiliaryRelatedCreates)
            ctx.addIssue({ code: "custom", message: "canonical mutation totals do not balance" });
    }]))();
export const ImportMutationIdSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^mutation_[a-z2-7]{26}$/, "regex"]]]))();
export const ImportTableIdSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^tbl_[a-z2-7]{26}$/, "regex"]]]))();
export const ImportRowIdSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[5]))();
export const OriginSourceRowsSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [7, SourceRowOrdinalSchema, [1], [5000]], (rows, ctx) => {
        if (new Set(rows).size !== rows.length)
            ctx.addIssue({ code: "custom", message: "mutation origins must be unique" });
        if (rows.some((row, index) => index > 0 && row <= rows[index - 1]))
            ctx.addIssue({ code: "custom", message: "mutation origins must be ordered" });
    }]))();
const PreparedMutationBase = { "mutationId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(ImportMutationIdSchema))(), "tableId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(ImportTableIdSchema))(), "rowId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(ImportRowIdSchema))(), "originSourceRows": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(OriginSourceRowsSchema))(), "payloadDigest": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__ref1))() };
export const PreparedImportMutationSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "role", [["primary_target", [6, { "mutationId": ImportMutationIdSchema, "tableId": ImportTableIdSchema, "rowId": ImportRowIdSchema, "originSourceRows": OriginSourceRowsSchema, "payloadDigest": __ref1, "role": [4, "primary_target"], "kind": [5, ["create", "update"]] }, 1]], ["auxiliary_related", [6, { "mutationId": ImportMutationIdSchema, "tableId": ImportTableIdSchema, "rowId": ImportRowIdSchema, "originSourceRows": OriginSourceRowsSchema, "payloadDigest": __ref1, "role": [4, "auxiliary_related"], "kind": [4, "create"] }, 1]]]]))();
export const SourceRowMutationMapSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "sourceRow": SourceRowOrdinalSchema, "primaryMutationId": [13, ImportMutationIdSchema], "auxiliaryRelatedMutationIds": [7, ImportMutationIdSchema, undefined, [100]] }, 1], (mapping, ctx) => {
        if (new Set(mapping.auxiliaryRelatedMutationIds).size
            !== mapping.auxiliaryRelatedMutationIds.length)
            ctx.addIssue({ code: "custom", message: "auxiliary mutation references must be unique" });
    }]))();
export const ImportPreparedLedgerSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "dispositions": ImportSourceDispositionLedgerSchema, "rowMutationMap": [7, SourceRowMutationMapSchema, undefined, [5000]], "mutations": [7, PreparedImportMutationSchema, undefined, [5000]], "mutationTotals": MutationTotalsSchema }, 1], (ledger, ctx) => {
        const fail = (message) => ctx.addIssue({ code: "custom", message });
        const mutationById = new Map(ledger.mutations.map(mutation => [mutation.mutationId, mutation]));
        if (mutationById.size !== ledger.mutations.length)
            fail("mutation identifiers must be unique");
        if (new Set(ledger.mutations.map(mutation => `${mutation.tableId}\u0000${mutation.rowId}`)).size
            !== ledger.mutations.length)
            fail("canonical table/row transitions must be unique");
        const mappingByRow = new Map(ledger.rowMutationMap.map(mapping => [mapping.sourceRow, mapping]));
        if (mappingByRow.size !== ledger.rowMutationMap.length)
            fail("row mappings must be unique");
        if (mappingByRow.size !== ledger.dispositions.length)
            fail("every disposition needs one row map");
        const referencedOrigins = new Map();
        const noteReference = (mutationId, sourceRow) => {
            const origins = referencedOrigins.get(mutationId) ?? [];
            origins.push(sourceRow);
            referencedOrigins.set(mutationId, origins);
        };
        for (const disposition of ledger.dispositions) {
            const mapping = mappingByRow.get(disposition.sourceRow);
            if (!mapping) {
                fail("every disposition needs one row map");
                continue;
            }
            if (disposition.kind === "create" || disposition.kind === "update") {
                if (mapping.primaryMutationId === null) {
                    fail("create/update dispositions require a primary mutation");
                }
                else {
                    const primary = mutationById.get(mapping.primaryMutationId);
                    if (!primary || primary.role !== "primary_target" || primary.kind !== disposition.kind)
                        fail("primary mutation role/kind must match its disposition");
                    noteReference(mapping.primaryMutationId, disposition.sourceRow);
                }
                for (const mutationId of mapping.auxiliaryRelatedMutationIds) {
                    const auxiliary = mutationById.get(mutationId);
                    if (!auxiliary || auxiliary.role !== "auxiliary_related")
                        fail("auxiliary references require auxiliary creates");
                    noteReference(mutationId, disposition.sourceRow);
                }
            }
            else if (mapping.primaryMutationId !== null
                || mapping.auxiliaryRelatedMutationIds.length !== 0) {
                fail("skip/blocked dispositions cannot map mutations");
            }
        }
        for (const mutation of ledger.mutations) {
            const origins = referencedOrigins.get(mutation.mutationId) ?? [];
            if (origins.length === 0)
                fail("unreferenced mutations are forbidden");
            const orderedOrigins = [...origins].sort((left, right) => left - right);
            if (orderedOrigins.length !== mutation.originSourceRows.length
                || orderedOrigins.some((row, index) => row !== mutation.originSourceRows[index]))
                fail("mutation origins must equal row-map references");
        }
        const actualTotals = {
            primaryTargetCreates: ledger.mutations.filter(mutation => mutation.role === "primary_target" && mutation.kind === "create").length,
            primaryTargetUpdates: ledger.mutations.filter(mutation => mutation.role === "primary_target" && mutation.kind === "update").length,
            auxiliaryRelatedCreates: ledger.mutations.filter(mutation => mutation.role === "auxiliary_related").length,
        };
        if (actualTotals.primaryTargetCreates !== ledger.mutationTotals.primaryTargetCreates
            || actualTotals.primaryTargetUpdates !== ledger.mutationTotals.primaryTargetUpdates
            || actualTotals.auxiliaryRelatedCreates !== ledger.mutationTotals.auxiliaryRelatedCreates)
            fail("mutation totals must count the unique canonical ledger");
    }]))();
export const ImportParserErrorCodeSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["E_IMPORT_SOURCE_LIMIT", "E_IMPORT_UTF8", "E_IMPORT_CONTROL_CHARACTER", "E_IMPORT_CSV_SYNTAX", "E_IMPORT_RAGGED_ROW", "E_IMPORT_ROW_LIMIT", "E_IMPORT_COLUMN_LIMIT", "E_IMPORT_CELL_LIMIT", "E_IMPORT_DECODED_LIMIT", "E_IMPORT_TIME_LIMIT", "E_IMPORT_EMPTY_SOURCE", "E_IMPORT_XLSX_UNAVAILABLE", "E_IMPORT_XLSX_INVALID", "E_IMPORT_XLSX_UNSAFE", "E_IMPORT_XLSX_UNSUPPORTED", "E_IMPORT_XLSX_FORMULA", "E_IMPORT_CHUNK_LIMIT", "E_IMPORT_SESSION_UNKNOWN", "E_IMPORT_PROTOCOL"]]))();
export const ImportParserStageSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["acquire", "decode", "parse", "chunk", "session", "protocol"]]))();
export const ImportParserRpcIdSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([1, [[5], [0, 0, false], __standalonePrograms[7], [1, 9007199254740991, true]]]))();
export const ArrayBufferSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([19, value => Object.prototype.toString.call(value) === "[object ArrayBuffer]", "ArrayBuffer required"]))();
export const OpenImportSourceRequestSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "version": [4, 1], "id": ImportParserRpcIdSchema, "op": [4, "openImportSource"], "payload": [6, { "appInstanceId": __ref2, "kind": [5, ["csv", "paste", "xlsx"]], "bytes": ArrayBufferSchema }, 1] }, 1]))();
export const ReadImportChunkRequestSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "version": [4, 1], "id": ImportParserRpcIdSchema, "op": [4, "readImportChunk"], "payload": [6, { "appInstanceId": __ref2, "sessionId": __ref3, "sheetId": [12, __ref0], "cursor": __standalonePrograms[18] }, 1] }, 1]))();
export const CloseImportSourceRequestSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "version": [4, 1], "id": ImportParserRpcIdSchema, "op": [4, "closeImportSource"], "payload": [6, { "appInstanceId": __ref2, "sessionId": __ref3, "reason": [5, ["cancel", "commit", "restart", "app_switch", "timeout"]] }, 1] }, 1]))();
export const ImportParserRequestSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "op", [["openImportSource", OpenImportSourceRequestSchema], ["readImportChunk", ReadImportChunkRequestSchema], ["closeImportSource", CloseImportSourceRequestSchema]]]))();
export const CloseImportSourceResultSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "disposed": [4, true] }, 1]))();
export const ImportParserSafeErrorSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "code": ImportParserErrorCodeSchema, "stage": ImportParserStageSchema, "message": [4, "The import source could not be read safely."], "row": [12, __standalonePrograms[52]], "column": [12, __standalonePrograms[53]], "limit": __standalonePrograms[54], "actual": __standalonePrograms[54] }, 1]))();
export const ImportParserResponseSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [[6, { "version": [4, 1], "id": ImportParserRpcIdSchema, "ok": [4, true], "result": [10, [__ref4, __ref5, CloseImportSourceResultSchema]] }, 1], [6, { "version": [4, 1], "id": ImportParserRpcIdSchema, "ok": [4, false], "error": ImportParserSafeErrorSchema }, 1]]]))();
