import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 8ef1bfbf5b392cf6638a68a768921ebdbb935928b7d736698eb263ff3201f28a; closed parse program v1.
import { standalone } from './runtime.mjs';
export const Ident = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[0]))();
export const PanelId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^[a-z][a-z0-9_]{2,40}$/, "regex"]]]))();
export const ColumnType = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["text", "number", "integer", "boolean", "date", "enum", "json", "computed", "relation", "lookup", "rollup", "rich_text", "attachment"]]))();
export const RelationSpec = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "target_table": Ident, "cardinality": [5, ["one", "many"]], "unique_targets": [16, [2], false], "display_field": [12, Ident] }, 1]))();
export const LookupSpec = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "relation_field": Ident, "target_field": Ident }, 1]))();
export const RollupSpec = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "relation_field": Ident, "target_field": [12, Ident], "operation": [5, ["count", "sum", "avg", "min", "max"]] }, 1]))();
export const JsonValue = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([17, () => [10, [[0, []], [1, []], [2], [3], [7, JsonValue], [8, [0, []], JsonValue]]]]))();
export const JsonScalar = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [[0, []], [1, []], [2]]]))();
const UINT64_MAX = 18446744073709551615n;
function isUInt64Decimal(value) {
    if (!/^(?:0|[1-9][0-9]{0,19})$/.test(value))
        return false;
    try {
        return BigInt(value) <= UINT64_MAX;
    }
    catch {
        return false;
    }
}
export const UInt64Decimal = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, []], isUInt64Decimal, "canonical uint64 decimal required"]))();
export const AppInstanceId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[1]))();
export const GenerationId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[2]))();
export const AuthorityIncarnationId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^auth_[a-z2-7]{26}$/, "regex"]]]))();
export const NamespaceId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^ns_[a-z2-7]{26}$/, "regex"]]]))();
export const LeaseId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^lease_[a-z2-7]{26}$/, "regex"]]]))();
export const OperationId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^op_[a-z2-7]{26}$/, "regex"]]]))();
export const RequestId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^req_[a-z2-7]{26}$/, "regex"]]]))();
export const ReleaseId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^rel_[a-z2-7]{26}$/, "regex"]]]))();
export const Sha256 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^sha256:[0-9a-f]{64}$/, "regex"]]]))();
export const TargetIdentityV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "appInstanceId": AppInstanceId, "activeGenerationId": GenerationId, "lineageEpoch": UInt64Decimal, "stateRevision": UInt64Decimal, "stateDigest": Sha256 }, 1]))();
export const TemporaryUserChoice = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([13, [4, "accepted_temporary_after_loss_boundary"]]))();
export const TemporaryEligibilityV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "catalogReadable": [4, true], "catalogAppCount": [4, 0], "namespaceInventoryReadable": [4, true], "durableNamespaceCount": [4, 0], "jobInventoryReadable": [4, true], "pendingOperationCount": [4, 0], "capability": [5, ["unsupported", "non_persistent"]], "userChoice": TemporaryUserChoice }, 1]))();
export const DeviceState = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["checking", "temporary_choice_required", "temporary", "needs_protection", "checkpointing", "protected_on_device", "locked_or_unknown"]]))();
export const DurableStoreCapability = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["supported", "unsupported", "non_persistent", "unknown"]]))();
export const ExpectedStoreFailure = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["restricted", "denied", "thrown", "locked", "corrupt", "quota", "attach", "unclassified"]]))();
export const ProtectionReasonCode = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["catalog_unavailable", "inventory_unavailable", "transaction_uncertified", "store_unavailable", "expected_store_failure", "temporary_ineligible", "temporary_choice_required", "persistence_unconfirmed", "checkpoint_missing", "checkpoint_stale", "checkpoint_invalid", "generation_not_selected", "adapter_uncertified", "target_unconfigured", "permission_required", "target_unreachable", "backup_stale", "backup_invalid", "stale_write_epoch"]]))();
export const NeedsProtectionReason = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["persistence_unconfirmed", "checkpoint_missing", "checkpoint_stale", "checkpoint_invalid", "generation_not_selected"]]))();
export const LockedOrUnknownReason = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["catalog_unavailable", "inventory_unavailable", "store_unavailable", "expected_store_failure", "temporary_ineligible", "transaction_uncertified"]]))();
export const DeviceStateResultV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "state", [["checking", [6, { "state": [4, "checking"], "reasonCode": [3] }, 1]], ["temporary_choice_required", [6, { "state": [4, "temporary_choice_required"], "reasonCode": [4, "temporary_choice_required"] }, 1]], ["temporary", [6, { "state": [4, "temporary"], "reasonCode": [3] }, 1]], ["needs_protection", [6, { "state": [4, "needs_protection"], "reasonCode": NeedsProtectionReason }, 1]], ["checkpointing", [6, { "state": [4, "checkpointing"], "reasonCode": [3] }, 1]], ["protected_on_device", [6, { "state": [4, "protected_on_device"], "reasonCode": [3] }, 1]], ["locked_or_unknown", [6, { "state": [4, "locked_or_unknown"], "reasonCode": LockedOrUnknownReason }, 1]]]]))();
export const InventoryCount = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[3]))();
export const CheckpointObservationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "state", [["none", [6, { "state": [4, "none"], "target": [3] }, 1]], ["in_progress", [6, { "state": [4, "in_progress"], "target": TargetIdentityV1 }, 1]], ["valid", [6, { "state": [4, "valid"], "target": TargetIdentityV1 }, 1]], ["stale", [6, { "state": [4, "stale"], "target": [13, TargetIdentityV1] }, 1]], ["invalid", [6, { "state": [4, "invalid"], "target": [13, TargetIdentityV1] }, 1]], ["generation_not_selected", [6, { "state": [4, "generation_not_selected"], "target": [13, TargetIdentityV1] }, 1]]]]))();
export const DeviceProtectionInputV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "checksComplete": [2], "expectedStoreFailure": [13, ExpectedStoreFailure], "catalogReadable": [2], "catalogAppCount": InventoryCount, "namespaceInventoryReadable": [2], "durableNamespaceCount": InventoryCount, "jobInventoryReadable": [2], "pendingOperationCount": InventoryCount, "capability": DurableStoreCapability, "userChoice": TemporaryUserChoice, "storeOpen": [5, ["yes", "no", "unknown"]], "transactionCertified": [2], "persisted": [5, ["yes", "no", "unknown"]], "target": [13, TargetIdentityV1], "checkpoint": CheckpointObservationV1 }, 1], (value, ctx) => {
        const inventories = [
            ["catalog", value.catalogReadable, value.catalogAppCount],
            ["namespace", value.namespaceInventoryReadable, value.durableNamespaceCount],
            ["job", value.jobInventoryReadable, value.pendingOperationCount],
        ];
        for (const [name, readable, count] of inventories) {
            if (readable !== (count !== null))
                ctx.addIssue({ code: "custom", message: `${name} readability/count mismatch` });
        }
        if (value.target !== null && value.catalogReadable && value.namespaceInventoryReadable
            && ((value.catalogAppCount ?? 0) < 1 || (value.durableNamespaceCount ?? 0) < 1))
            ctx.addIssue({ code: "custom", message: "selected target requires catalog app and namespace" });
        if (value.target === null && value.checkpoint.target !== null)
            ctx.addIssue({ code: "custom", message: "checkpoint target requires selected target" });
    }]))();
export const ColumnSpec = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "name": Ident, "label": [12, [0, [[0, 1, true], [1, 60, true]]]], "type": ColumnType, "required": [16, [2], false], "values": [12, [7, [0, [[1, 40, true]]], undefined, [24]]], "expr": [12, [0, [[1, 500, true]]]], "relation": [12, RelationSpec], "lookup": [12, LookupSpec], "rollup": [12, RollupSpec], "pk": [12, [2]] }, 1], (c, ctx) => {
        if (c.type === "enum" && (c.values?.length ?? 0) === 0)
            ctx.addIssue({ code: "custom", message: "enum needs values" });
        if (c.type !== "enum" && c.values !== undefined)
            ctx.addIssue({ code: "custom", message: "values belong only to enum fields" });
        if (c.type === "computed" && !c.expr)
            ctx.addIssue({ code: "custom", message: "computed needs expr" });
        if (c.type !== "computed" && c.expr !== undefined)
            ctx.addIssue({ code: "custom", message: "expr belongs only to computed fields" });
        if ((c.type === "relation") !== (c.relation !== undefined))
            ctx.addIssue({ code: "custom", message: "relation metadata must match relation type" });
        if ((c.type === "lookup") !== (c.lookup !== undefined))
            ctx.addIssue({ code: "custom", message: "lookup metadata must match lookup type" });
        if ((c.type === "rollup") !== (c.rollup !== undefined))
            ctx.addIssue({ code: "custom", message: "rollup metadata must match rollup type" });
        if (c.rollup && c.rollup.operation !== "count" && !c.rollup.target_field)
            ctx.addIssue({ code: "custom", message: "non-count rollup needs target_field" });
        if ((c.type === "lookup" || c.type === "rollup" || c.type === "attachment") && c.required)
            ctx.addIssue({ code: "custom", message: `${c.type} fields cannot be required` });
    }]))();
export const CondOp = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["eq", "neq", "gt", "gte", "lt", "lte", "contains", "in", "is_null", "not_null", "within_days", "older_than_days"]]))();
export const Condition = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "field": Ident, "op": CondOp, "value": [12, [10, [[0, []], [1, []], [2], [7, [10, [[0, []], [1, []]]], undefined, [50]], [6, { "$var": [4, true] }, 0]]]] }, 0]))();
export const Query = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "from": Ident, "select": [12, [7, Ident, undefined, [30]]], "where": [12, [7, Condition, undefined, [10]]], "orWhere": [12, [7, [7, Condition, undefined, [6]], undefined, [4]]], "orderBy": [12, [7, [6, { "field": Ident, "dir": [5, ["asc", "desc"]] }, 0], undefined, [3]]], "groupBy": [12, [7, Ident, undefined, [2]]], "aggregate": [12, [7, [6, { "fn": [5, ["count", "sum", "avg", "min", "max"]], "field": Ident, "as": Ident }, 0], undefined, [5]]], "limit": [12, [1, [[5], [0, 0, false], [1, 5000, true]]]], "includeDeleted": [12, [2]] }, 0]))();
export const ForwardOp = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "op", [["create_table", [6, { "op": [4, "create_table"], "table": Ident, "columns": [7, ColumnSpec, [1], [20]] }, 0]], ["add_column", [6, { "op": [4, "add_column"], "table": Ident, "column": ColumnSpec }, 0]], ["rename_column", [6, { "op": [4, "rename_column"], "table": Ident, "from": Ident, "to": Ident }, 0]], ["add_enum_value", [6, { "op": [4, "add_enum_value"], "table": Ident, "column": Ident, "value": [0, [[1, 40, true]]] }, 0]], ["add_index", [6, { "op": [4, "add_index"], "table": Ident, "column": Ident }, 0]], ["backfill", [6, { "op": [4, "backfill"], "table": Ident, "column": Ident, "value": [12, JsonScalar], "expr": [12, [0, [[1, 500, true]]]] }, 0]], ["create_computed", [6, { "op": [4, "create_computed"], "table": Ident, "column": Ident, "expr": [0, [[1, 500, true]]] }, 0]], ["update_computed", [6, { "op": [4, "update_computed"], "table": Ident, "column": Ident, "expr": [0, [[1, 500, true]]] }, 0]], ["hide_column", [6, { "op": [4, "hide_column"], "table": Ident, "column": Ident }, 0]], ["set_required", [6, { "op": [4, "set_required"], "table": Ident, "column": Ident, "required": [2], "default_for_existing": [12, JsonScalar] }, 0]]]]))();
export const InverseOp = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "op", [["drop_table_if_created_by_this", [6, { "op": [4, "drop_table_if_created_by_this"], "table": Ident }, 0]], ["drop_column_if_added_by_this", [6, { "op": [4, "drop_column_if_added_by_this"], "table": Ident, "column": Ident }, 0]], ["remove_enum_value_if_unused", [6, { "op": [4, "remove_enum_value_if_unused"], "table": Ident, "column": Ident, "value": [0, []] }, 0]], ["unhide_column", [6, { "op": [4, "unhide_column"], "table": Ident, "column": Ident }, 0]], ["drop_index", [6, { "op": [4, "drop_index"], "table": Ident, "column": Ident }, 0]], ["restore_expr", [6, { "op": [4, "restore_expr"], "table": Ident, "column": Ident, "expr": [0, []] }, 0]], ["unset_required", [6, { "op": [4, "unset_required"], "table": Ident, "column": Ident }, 0]], ["rename_column", [6, { "op": [4, "rename_column"], "table": Ident, "from": Ident, "to": Ident }, 0]]]]))();
export const MigrationPlan = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "operations": [7, ForwardOp, [1], [12]], "inverse": [7, InverseOp, [1], [12]] }, 0], (m, ctx) => {
        if (new Set(m.operations.map(o => o.table)).size > 3)
            ctx.addIssue({ code: "custom", message: "I5: <=3 tables per plan" });
        for (const op of m.operations)
            if (op.op === "backfill" && (op.value === undefined) === (op.expr === undefined))
                ctx.addIssue({ code: "custom",
                    message: "G23: backfill takes exactly one of value|expr" });
    }]))();
export const DiffKind = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["add_field", "change_field", "add_panel", "change_panel", "remove_panel", "add_status", "add_computed", "add_chart", "add_relation", "add_automation", "add_attachment"]]))();
export const PanelArtifact = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "panel_id": PanelId, "title": [0, [[0, 1, true], [1, 60, true]]], "placement": [6, { "region": [5, ["top", "main", "side"]], "order": [1, [[5], [0, 0, true], [1, 50, true]]], "w": [12, [1, [[5], [0, 1, true], [1, 4, true]]]], "h": __standalonePrograms[4], "col": [12, [1, [[5], [0, 0, true], [1, 3, true]]]] }, 0], "code": [0, [[1, 65536, true]]], "declared_queries": [7, Query, undefined, [8]], "declared_writes": [16, [7, Ident, undefined, [4]], []] }, 0]))();
export const MutationPlan = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "api": [4, 1], "summary": [0, [[1, 200, true]]], "user_facing_diff": [7, [6, { "kind": DiffKind, "detail": [0, [[1, 120, true]]] }, 0], undefined, [12]], "clarifying_question": [13, [0, [[1, 200, true]]]], "assumptions": [7, [0, [[1, 150, true]]], undefined, [5]], "migration": [13, MigrationPlan], "panels": [7, PanelArtifact, undefined, [8]], "remove_panels": [7, PanelId, undefined, [8]], "confidence": [1, [[0, 0, true], [1, 1, true]]] }, 0], (p, ctx) => {
        const hasPlan = !!p.migration || p.panels.length > 0 || p.remove_panels.length > 0;
        if (p.clarifying_question && hasPlan)
            ctx.addIssue({ code: "custom", message: "R1: question XOR plan" });
        if (!p.clarifying_question && !hasPlan)
            ctx.addIssue({ code: "custom", message: "empty plan" });
        if (!p.clarifying_question && p.confidence < 0.5)
            ctx.addIssue({ code: "custom", message: "R5: low confidence must clarify" });
        if (!p.clarifying_question && p.summary.trim().length === 0)
            ctx.addIssue({ code: "custom", message: "G18: summary required unless clarifying" });
    }]))();
export const BridgeCall = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "v": [4, 1], "panel": PanelId, "seq": [1, [[5], [0, 0, true]]], "call": [5, ["db.query", "db.watch", "db.unwatch", "db.insert", "db.update", "db.softDelete", "ui.toast", "ui.confirm", "ui.openRecord", "events.emit", "events.on", "events.off"]], "args": [7, JsonValue, undefined, [4]] }, 0]))();
export const BridgeUserGesture = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "v": [4, 1], "kind": [4, "user_gesture"] }, 0]))();
export const BridgeOpenRecord = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "v": [4, 1], "kind": [4, "open_record"], "table": Ident, "id": __standalonePrograms[5] }, 0]))();
export const BridgeReply = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "v": [4, 1], "seq": [1, [[5]]], "ok": [2], "result": [12, JsonValue], "error": [12, [6, { "code": [0, []], "message": [0, []] }, 0]] }, 0]))();
export const BridgePanelError = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "v": [4, 1], "kind": [4, "panel_error"], "code": [0, [[1, 40, true]]], "message": [0, [[1, 500, true]]] }, 0]))();
export const BridgePush = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([11, "kind", [["watch", [6, { "v": [4, 1], "kind": [4, "watch"], "watchId": [0, []], "rows": [7, [8, [0, []], JsonValue]] }, 0]], ["event", [6, { "v": [4, 1], "kind": [4, "event"], "name": Ident, "payload": JsonValue }, 0]], ["boot", [6, { "v": [4, 1], "kind": [4, "boot"], "code": [0, []], "panelId": PanelId, "apiVersion": [4, 1], "meta": [6, { "schema": JsonValue, "appVersion": [1, [[5], [0, 0, true]]], "placement": [6, { "region": [5, ["top", "main", "side"]], "order": [1, [[5]]], "w": [12, [1, [[5], [0, 1, true], [1, 4, true]]]], "h": __standalonePrograms[4], "col": [12, [1, [[5], [0, 0, true], [1, 3, true]]]] }, 0] }, 0], "tokens": [8, [0, []], [0, []]] }, 0]]]]))();
export * from "./intake.mjs";
export const __hook0 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([16, [2], false]))();
export const __hook1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([16, [2], false]))();
export const __hook2 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([16, [7, Ident, undefined, [4]], []]))();
