// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 2ca07cade1b18fc5dc7069e4c0accba6d1a79de93582949551fd00498ff583d0; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../intake-state';
export declare const FileReviewSchema: Compiled<typeof import("../intake-state").FileReviewSchema>;
export declare const StoredUploadedFileSchema: Compiled<typeof import("../intake-state").StoredUploadedFileSchema>;
export declare const StoredSubmissionBodySchema: Compiled<typeof import("../intake-state").StoredSubmissionBodySchema>;
export declare const QuarantinedFileSchema: Compiled<typeof import("../intake-state").QuarantinedFileSchema>;
export declare const StoredSubmissionSchema: Compiled<typeof import("../intake-state").StoredSubmissionSchema>;
export declare const ReceiptSchema: Compiled<typeof import("../intake-state").ReceiptSchema>;
export declare const SimulationSchema: Compiled<typeof import("../intake-state").SimulationSchema>;
export declare const DeliveryFailureSchema: Compiled<typeof import("../intake-state").DeliveryFailureSchema>;
export declare const LocalStateSchema: Compiled<typeof import("../intake-state").LocalStateSchema>;
export declare const __hook0: Parser<unknown>;
