import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 9b0e1bd928125fb5649ef275c228aed0a2e166144fba78a20e21658b3247e5f4; closed parse program v1.
import { standalone } from './runtime.mjs';
const UUID_V7 = "[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}";
export const IntakeFormId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[30]))();
export const IntakeSubmissionId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[31]))();
export const IntakeReceiptId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[32]))();
export const IntakeTableId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[23]))();
export const IntakeFieldId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[24]))();
export const IntakeToken = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[33]))();
export const IntakeSha256 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[34]))();
export const IntakeCanonicalInstant = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[21], value => {
        try {
            return new Date(value).toISOString() === value;
        }
        catch {
            return false;
        }
    }, "exact UTC millisecond instant required"]))();
export const IntakeRelayFormRegistrationResultV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "formId": IntakeFormId, "expiresAt": IntakeCanonicalInstant }, 1]))();
export const IntakeRelayTerminalResultV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "formId": IntakeFormId, "expiresAt": IntakeCanonicalInstant, "requestSha256": IntakeSha256, "terminal": [4, true] }, 1]))();
export const IntakeMimeType = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["application/pdf", "image/png", "image/jpeg", "text/plain"]]))();
export const IntakeScalarType = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["text", "rich_text", "number", "integer", "boolean", "date", "enum"]]))();
export const PublicIntakeFieldV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "fieldId": IntakeFieldId, "label": __standalonePrograms[35], "type": IntakeScalarType, "required": [2], "maxLength": [13, [1, [[5], [0, 1, true], [1, 20000, true]]]], "options": [7, __standalonePrograms[35], undefined, [24]] }, 1], (field, context) => {
        const textual = field.type === "text" || field.type === "rich_text";
        if (textual !== (field.maxLength !== null))
            context.addIssue({
                code: "custom", path: ["maxLength"], message: "only text fields require maxLength",
            });
        if ((field.type === "enum") !== (field.options.length > 0))
            context.addIssue({
                code: "custom", path: ["options"], message: "only enum fields require options",
            });
        if (new Set(field.options).size !== field.options.length)
            context.addIssue({
                code: "custom", path: ["options"], message: "field options must be unique",
            });
    }]))();
export const PublicFileRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "requestId": __standalonePrograms[0], "fieldId": IntakeFieldId, "label": __standalonePrograms[35], "required": [2], "maxFiles": [1, [[5], [0, 1, true], [1, 3, true]]], "maxBytes": __standalonePrograms[36], "allowedMimeTypes": [7, IntakeMimeType, [1], [4]] }, 1], (request, context) => {
        if (new Set(request.allowedMimeTypes).size !== request.allowedMimeTypes.length)
            context.addIssue({ code: "custom", path: ["allowedMimeTypes"], message: "file types must be unique" });
    }]))();
export const PublicIntakeFormShapeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "formId": IntakeFormId, "revision": __standalonePrograms[37], "title": __standalonePrograms[38], "description": [0, [[7], [1, 1000, true]]], "target": [6, { "tableId": IntakeTableId, "expectedSchemaVersion": __standalonePrograms[39] }, 1], "fields": [7, PublicIntakeFieldV1, [1], [30]], "fileRequests": [7, PublicFileRequestV1, undefined, [5]], "encryption": __standalonePrograms[40], "delivery": [6, { "submitToken": IntakeToken, "expiresAt": IntakeCanonicalInstant }, 1] }, 1]))();
function validateIntakeFields(form, context) {
    const fieldIds = form.fields.map(field => field.fieldId);
    const fileFieldIds = form.fileRequests.map(request => request.fieldId);
    const requestIds = form.fileRequests.map(request => request.requestId);
    if (new Set(fieldIds).size !== fieldIds.length)
        context.addIssue({ code: "custom", path: ["fields"], message: "form field ids must be unique" });
    if (new Set(fileFieldIds).size !== fileFieldIds.length)
        context.addIssue({ code: "custom", path: ["fileRequests"], message: "file field ids must be unique" });
    if (new Set(requestIds).size !== requestIds.length)
        context.addIssue({ code: "custom", path: ["fileRequests"], message: "file request ids must be unique" });
    if (fileFieldIds.some(id => fieldIds.includes(id)))
        context.addIssue({ code: "custom", path: ["fileRequests"], message: "file and value fields cannot overlap" });
}
export const PublicIntakeFormV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, PublicIntakeFormShapeV1, validateIntakeFields]))();
export const IntakeFormDefinitionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "formId": IntakeFormId, "revision": __standalonePrograms[37], "title": __standalonePrograms[38], "description": [0, [[7], [1, 1000, true]]], "target": [6, { "tableId": IntakeTableId, "expectedSchemaVersion": __standalonePrograms[39] }, 1], "fields": [7, PublicIntakeFieldV1, [1], [30]], "fileRequests": [7, PublicFileRequestV1, undefined, [5]], "encryption": __standalonePrograms[40], "delivery": [6, { "expiresAt": IntakeCanonicalInstant }, 1] }, 1], validateIntakeFields]))();
export const IntakePublicationProposalV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "title": __standalonePrograms[38], "description": [0, [[7], [1, 1000, true]]], "target": [6, { "tableId": IntakeTableId, "expectedSchemaVersion": __standalonePrograms[39] }, 1], "fields": [7, PublicIntakeFieldV1, [1], [30]], "fileRequests": [7, PublicFileRequestV1, undefined, [5]], "expiresAt": IntakeCanonicalInstant }, 1], validateIntakeFields]))();
export const MAX_INTAKE_CIPHERTEXT_BYTES = 12 * 1024 * 1024;
const MAX_INTAKE_CIPHERTEXT_BASE64URL = Math.ceil(MAX_INTAKE_CIPHERTEXT_BYTES * 4 / 3);
export const Base64Url = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [__standalonePrograms[41]]]))();
export const IntakeScalarValue = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [[0, [[1, 20000, true]]], [1, [[6]]], [2]]]))();
export const IntakeSubmissionValueV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "fieldId": IntakeFieldId, "value": IntakeScalarValue }, 1]))();
export const IntakeUploadedFileV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "requestId": __standalonePrograms[0], "uploadId": __standalonePrograms[42], "name": [14, __standalonePrograms[9], value => value === value.trim() && !/[\\/\u0000-\u001f\u007f]/.test(value), "canonical leaf filename required"], "mime": IntakeMimeType, "size": __standalonePrograms[36], "sha256": IntakeSha256, "bytes": __standalonePrograms[43] }, 1]))();
export const IntakeSubmissionPlaintextV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "formId": IntakeFormId, "formRevision": __standalonePrograms[37], "submissionId": IntakeSubmissionId, "submittedAt": IntakeCanonicalInstant, "values": [7, IntakeSubmissionValueV1, undefined, [30]], "files": [7, IntakeUploadedFileV1, undefined, [15]] }, 1], (submission, context) => {
        const fields = submission.values.map(value => value.fieldId);
        const uploads = submission.files.map(file => file.uploadId);
        if (new Set(fields).size !== fields.length)
            context.addIssue({ code: "custom", path: ["values"], message: "submission field ids must be unique" });
        if (new Set(uploads).size !== uploads.length)
            context.addIssue({ code: "custom", path: ["files"], message: "upload ids must be unique" });
        const totalBytes = submission.files.reduce((sum, file) => sum + file.size, 0);
        if (!Number.isSafeInteger(totalBytes) || totalBytes > 8 * 1024 * 1024)
            context.addIssue({ code: "custom", path: ["files"], message: "submission files exceed the 8 MB limit" });
    }]))();
export const IntakeCiphertextEnvelopeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "algorithm": __standalonePrograms[44], "ephemeralPublicKey": __standalonePrograms[45], "salt": [0, [[3, /^[A-Za-z0-9_-]{22}$/, "regex"]]], "iv": [0, [[3, /^[A-Za-z0-9_-]{16}$/, "regex"]]], "ciphertext": [0, [__standalonePrograms[41], [1, 16777216, true]]] }, 1]))();
export const IntakeRelaySubmissionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "submissionId": IntakeSubmissionId, "envelope": IntakeCiphertextEnvelopeV1 }, 1]))();
export const IntakeAutoAcceptConditionV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "fieldId": IntakeFieldId, "op": [5, ["equals", "is_present"]], "value": [13, IntakeScalarValue] }, 1], (condition, context) => {
        if ((condition.op === "equals") !== (condition.value !== null))
            context.addIssue({
                code: "custom", path: ["value"],
                message: condition.op === "equals" ? "equals needs a value" : "is_present takes no value",
            });
    }]))();
export const IntakeAutoAcceptDraftV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "formId": IntakeFormId, "formRevision": __standalonePrograms[37], "expectedSchemaVersion": __standalonePrograms[39], "conditions": [7, IntakeAutoAcceptConditionV1, [1], [5]] }, 1], (rule, context) => {
        const fields = rule.conditions.map(condition => condition.fieldId);
        if (new Set(fields).size !== fields.length)
            context.addIssue({ code: "custom", path: ["conditions"], message: "rule fields must be unique" });
    }]))();
export const IntakeRelayFormRegistrationV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "formId": IntakeFormId, "ownerToken": IntakeToken, "submitToken": IntakeToken, "expiresAt": IntakeCanonicalInstant, "maxCiphertextBytes": [1, [[5], [0, 1024, true], [1, 12582912, true]]] }, 1], (registration, context) => {
        if (registration.ownerToken === registration.submitToken)
            context.addIssue({ code: "custom", path: ["submitToken"], message: "submit and owner tokens must differ" });
    }]))();
export const IntakeRelayDeliveryItemV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "formId": IntakeFormId, "submissionId": IntakeSubmissionId, "receivedAt": IntakeCanonicalInstant, "expiresAt": IntakeCanonicalInstant, "ciphertextBytes": [1, [[5], [0, 1, true], [1, 12582912, true]]], "envelope": IntakeCiphertextEnvelopeV1 }, 1], (item, context) => {
        if (Date.parse(item.expiresAt) <= Date.parse(item.receivedAt))
            context.addIssue({
                code: "custom", path: ["expiresAt"], message: "delivery expiry must follow receipt",
            });
    }]))();
export const RelayBaseUrl = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, [[1, 2048, true]]], value => {
        try {
            const url = new URL(value);
            if (url.username || url.password || url.search || url.hash || url.pathname !== "/")
                return false;
            return url.protocol === "https:" || (url.protocol === "http:"
                && (url.hostname === "localhost" || url.hostname === "127.0.0.1" || url.hostname === "[::1]"));
        }
        catch {
            return false;
        }
    }, "relay URL must be HTTPS (or loopback HTTP) without credentials, query, fragment, or path"]))();
export const PublicIntakeLinkPayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "relayBaseUrl": RelayBaseUrl, "form": PublicIntakeFormV1 }, 1]))();
export const LocalIntakeFormV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "publicForm": PublicIntakeFormV1, "ownerPrivateKey": [0, [[3, /^[A-Za-z0-9_-]{184}$/, "regex"]]], "ownerToken": IntakeToken, "relayBaseUrl": RelayBaseUrl, "publishedAt": [13, IntakeCanonicalInstant], "revokedAt": [13, IntakeCanonicalInstant], "terminalReason": [12, [13, [5, ["revoked", "expired"]]]] }, 1], (form, context) => {
        if (form.ownerToken === form.publicForm.delivery.submitToken)
            context.addIssue({ code: "custom", path: ["ownerToken"], message: "owner and submit tokens must differ" });
        if (form.publishedAt !== null && Date.parse(form.publishedAt) >= Date.parse(form.publicForm.delivery.expiresAt))
            context.addIssue({ code: "custom", path: ["publishedAt"], message: "publication must precede form expiry" });
        if (form.revokedAt !== null && form.publishedAt === null)
            context.addIssue({ code: "custom", path: ["revokedAt"], message: "an unpublished form cannot be revoked" });
        if (form.terminalReason !== undefined && form.terminalReason !== null && form.revokedAt === null)
            context.addIssue({ code: "custom", path: ["terminalReason"], message: "terminal reason requires a terminal time" });
    }]))();
export const IntakeOwnerSourceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "appInstanceId": __standalonePrograms[1], "activeGenerationId": __standalonePrograms[2], "lineageEpoch": [14, __standalonePrograms[46], value => /^(0|[1-9][0-9]*)$/.test(value) && BigInt(value) <= 18446744073709551615n] }, 1]))();
export const LocalIntakeFormV2 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 2], "publicForm": IntakeFormDefinitionV1, "ownerSource": IntakeOwnerSourceV1, "relayBaseUrl": RelayBaseUrl, "publishedAt": [13, IntakeCanonicalInstant], "revokedAt": [13, IntakeCanonicalInstant], "terminalReason": [13, [5, ["revoked", "expired"]]] }, 1], (form, context) => {
        if (form.publishedAt !== null && Date.parse(form.publishedAt) >= Date.parse(form.publicForm.delivery.expiresAt))
            context.addIssue({ code: "custom", message: "Publication must precede form expiry" });
        if ((form.revokedAt !== null && form.publishedAt === null) || ((form.terminalReason !== null) !== (form.revokedAt !== null)))
            context.addIssue({ code: "custom", message: "Terminal form state is inconsistent" });
    }]))();
export const IntakePublicationClosureV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "form": LocalIntakeFormV2, "closedAt": __standalonePrograms[21], "terminal": [4, true] }, 1]))();
export const IntakeAutoAcceptRuleV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "formId": IntakeFormId, "formRevision": __standalonePrograms[37], "expectedSchemaVersion": __standalonePrograms[39], "conditions": [7, IntakeAutoAcceptConditionV1, [1], [5]], "enabled": [4, true], "simulationFingerprint": IntakeSha256, "simulatedAt": IntakeCanonicalInstant, "enabledAt": IntakeCanonicalInstant }, 1], (rule, context) => {
        const fields = rule.conditions.map(condition => condition.fieldId);
        if (new Set(fields).size !== fields.length)
            context.addIssue({ code: "custom", path: ["conditions"], message: "rule fields must be unique" });
        if (Date.parse(rule.enabledAt) < Date.parse(rule.simulatedAt))
            context.addIssue({ code: "custom", path: ["enabledAt"], message: "enablement cannot predate simulation" });
    }]))();
export const __hook0 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[9], value => value === value.trim() && !/[\\/\u0000-\u001f\u007f]/.test(value), "canonical leaf filename required"]))();
export const __hook1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, __standalonePrograms[46], value => /^(0|[1-9][0-9]*)$/.test(value) && BigInt(value) <= 18446744073709551615n]))();
