import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 2ca07cade1b18fc5dc7069e4c0accba6d1a79de93582949551fd00498ff583d0; closed parse program v1.
import { standalone } from './runtime.mjs';
import { __hook0 as __ref0 } from './intake.mjs';
import { IntakeMimeType as __ref1 } from './intake.mjs';
import { IntakeSha256 as __ref2 } from './intake.mjs';
import { IntakeSubmissionValueV1 as __ref3 } from './intake.mjs';
import { LocalIntakeFormV2 as __ref4 } from './intake.mjs';
import { IntakeAutoAcceptRuleV1 as __ref5 } from './intake.mjs';
import { IntakePublicationClosureV1 as __ref6 } from './intake.mjs';
export const FileReviewSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "uploadId": __standalonePrograms[42], "requestId": __standalonePrograms[0], "name": __standalonePrograms[9], "mime": __standalonePrograms[49], "size": __standalonePrograms[36], "sha256": __standalonePrograms[34], "status": [5, ["quarantined", "rejected", "activated"]], "reason": [13, [0, [[0, 1, true], [1, 300, true]]]], "attachmentId": [13, __standalonePrograms[50]] }, 1], (file, context) => {
        if ((file.status === "activated") !== (file.attachmentId !== null))
            context.addIssue({ code: "custom", message: "file activation metadata is inconsistent" });
        if ((file.status === "rejected") !== (file.reason !== null))
            context.addIssue({ code: "custom", message: "file rejection metadata is inconsistent" });
    }]))();
export const StoredUploadedFileSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "requestId": __standalonePrograms[0], "uploadId": __standalonePrograms[42], "name": __ref0, "mime": __ref1, "size": __standalonePrograms[36], "sha256": __ref2 }, 1]))();
export const StoredSubmissionBodySchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "formId": __standalonePrograms[30], "formRevision": __standalonePrograms[37], "submissionId": __standalonePrograms[31], "submittedAt": __standalonePrograms[21], "values": [7, __ref3, undefined, [30]], "files": [7, StoredUploadedFileSchema, undefined, [15]] }, 1], (submission, context) => {
        if (new Set(submission.values.map(value => value.fieldId)).size !== submission.values.length)
            context.addIssue({ code: "custom", path: ["values"], message: "submission field ids must be unique" });
        if (new Set(submission.files.map(file => file.uploadId)).size !== submission.files.length)
            context.addIssue({ code: "custom", path: ["files"], message: "upload ids must be unique" });
    }]))();
export const QuarantinedFileSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "uploadId": __standalonePrograms[42], "bytes": __standalonePrograms[43] }, 1]))();
export const StoredSubmissionSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "submission": StoredSubmissionBodySchema, "quarantinedFiles": [7, QuarantinedFileSchema, undefined, [15]], "stagedAt": __standalonePrograms[21], "terminalAt": __standalonePrograms[55], "status": [5, ["pending", "blocked", "accepted", "rejected"]], "validationErrors": [7, [0, [[0, 1, true], [1, 300, true]]], undefined, [30]], "files": [7, FileReviewSchema, undefined, [15]], "receiptId": [13, __standalonePrograms[32]] }, 1], (submission, context) => {
        if ((submission.status === "accepted") !== (submission.receiptId !== null))
            context.addIssue({ code: "custom", message: "submission receipt state is inconsistent" });
        if ((submission.status === "blocked") !== (submission.validationErrors.length > 0))
            context.addIssue({ code: "custom", message: "submission validation state is inconsistent" });
        const terminal = submission.status === "accepted" || submission.status === "rejected";
        if (terminal !== (submission.terminalAt !== null))
            context.addIssue({ code: "custom", message: "submission terminal time is inconsistent" });
        if (terminal && submission.quarantinedFiles.length > 0)
            context.addIssue({ code: "custom", message: "terminal submission retained quarantine bytes" });
        const byteIds = submission.quarantinedFiles.map(file => file.uploadId);
        if (new Set(byteIds).size !== byteIds.length)
            context.addIssue({ code: "custom", message: "quarantine byte identities must be unique" });
        const quarantinedIds = new Set(submission.files
            .filter(file => file.status === "quarantined").map(file => file.uploadId));
        if (byteIds.some(id => !quarantinedIds.has(id))
            || [...quarantinedIds].some(id => !byteIds.includes(id)))
            context.addIssue({ code: "custom", message: "quarantine bytes and review state differ" });
    }]))();
export const ReceiptSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "id": __standalonePrograms[32], "submissionId": __standalonePrograms[31], "formId": __standalonePrograms[30], "mode": [5, ["manual", "auto"]], "batchId": __standalonePrograms[56], "table": __standalonePrograms[0], "rowId": __standalonePrograms[56], "attachmentIds": [7, __standalonePrograms[50], undefined, [15]], "acceptedAt": __standalonePrograms[21], "undoneAt": __standalonePrograms[55], "undone": [2] }, 1], (receipt, context) => {
        if (receipt.undone !== (receipt.undoneAt !== null))
            context.addIssue({ code: "custom", message: "receipt undo state is inconsistent" });
    }]))();
export const SimulationSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "formId": __standalonePrograms[30], "fingerprint": __standalonePrograms[34], "simulatedAt": __standalonePrograms[21], "pendingCount": [1, [[5], [0, 0, true], [1, 100, true]]], "matchedSubmissionIds": [7, __standalonePrograms[31], undefined, [100]] }, 1]))();
export const DeliveryFailureSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "formId": __standalonePrograms[30], "submissionId": __standalonePrograms[31], "envelopeSha256": __standalonePrograms[34], "status": [5, ["failed", "discard_authorized", "discarded", "staged"]], "failedAt": __standalonePrograms[21], "updatedAt": __standalonePrograms[21] }, 1]))();
export const LocalStateSchema = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 2], "forms": [7, __ref4, undefined, [100]], "submissions": [7, StoredSubmissionSchema, undefined, [500]], "deliveryFailures": [16, [7, DeliveryFailureSchema, undefined, [500]], []], "rules": [7, __ref5, undefined, [100]], "simulations": [7, SimulationSchema, undefined, [100]], "receipts": [7, ReceiptSchema, undefined, [1000]], "publicationClosures": [12, [7, __ref6, undefined, [100]]] }, 1], (state, context) => {
        for (const [path, values] of [
            ["forms", state.forms.map(form => form.publicForm.formId)],
            ["submissions", state.submissions.map(item => item.submission.submissionId)],
            ["deliveryFailures", state.deliveryFailures.map(item => `${item.formId}/${item.submissionId}`)],
            ["rules", state.rules.map(rule => rule.formId)],
            ["simulations", state.simulations.map(item => item.formId)],
            ["receipts", state.receipts.map(receipt => receipt.id)],
            ["publicationClosures", (state.publicationClosures ?? []).map(row => row.form.publicForm.formId)],
        ]) {
            if (new Set(values).size !== values.length)
                context.addIssue({ code: "custom", path: [path], message: `${path} identities must be unique` });
        }
    }]))();
export const __hook0 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([16, [7, DeliveryFailureSchema, undefined, [500]], []]))();
