// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 3771675049cf3821dfb5483bfc62b2f11ca5bf4a58e42745749a39e9cba3f572; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../intake-workflow';
export declare const IntakePublicationJobV1: Compiled<typeof import("../intake-workflow").IntakePublicationJobV1>;
export type IntakePublicationJobV1=import("../intake-workflow").IntakePublicationJobV1;
export declare const IntakeRevocationJobV1: Compiled<typeof import("../intake-workflow").IntakeRevocationJobV1>;
export type IntakeRevocationJobV1=import("../intake-workflow").IntakeRevocationJobV1;
