import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: f671f5a622d8f62e844e1f9462b46043964d5582c73fe3684fd8f466599ef2bb; closed parse program v1.
import { standalone } from './runtime.mjs';
import { AuthorityIncarnationId as __ref0 } from './index.mjs';
import { TargetEvidenceV1 as __ref1 } from './catalog.mjs';
import { ProductionRequestReceiptV1 as __ref2 } from './catalog.mjs';
import { LocalIntakeFormV2 as __ref3 } from './intake.mjs';
import { RequestId as __ref4 } from './index.mjs';
export const LegacyOwnerRouteV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["intake.saveForm", "intake.markPublished", "intake.revokeForm", "intake.markExpired", "intake.command"]]))();
export const LegacyOwnerCandidateV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "authorityIncarnationId": __ref0, "route": LegacyOwnerRouteV1, "source": __ref1, "receipt": __ref2 }, 1], (value, context) => {
        const s = value.source, r = value.receipt;
        if (r.state !== "committed" || r.appInstanceId !== s.appInstanceId || r.activeGenerationId !== s.activeGenerationId || r.lineageEpoch !== s.lineageEpoch
            || r.expectedProtectionRevision !== s.protectionRevision || r.expectedStateSha256 !== s.stateSha256)
            context.addIssue({ code: "custom", message: "Original committed owner evidence required" });
    }]))();
export const LegacyOwnerProofV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "authorityIncarnationId": __ref0, "route": LegacyOwnerRouteV1, "source": __ref1, "receipt": __ref2, "kind": [5, ["intake_private", "intake_public"]], "form": __ref3, "activation": [5, ["original_metadata", "custody_only"]] }, 1], (value, context) => {
        if (!LegacyOwnerCandidateV1.safeParse({ schema: value.schema, authorityIncarnationId: value.authorityIncarnationId, route: value.route, source: value.source, receipt: value.receipt }).success
            || value.form.ownerSource.appInstanceId !== value.source.appInstanceId || value.form.ownerSource.activeGenerationId !== value.source.activeGenerationId
            || value.form.ownerSource.lineageEpoch !== value.source.lineageEpoch)
            context.addIssue({ code: "custom", message: "Original owner proof differs" });
    }]))();
export const LegacyOwnerInventoryV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "target": __ref1, "legacyState": [2], "candidates": [7, LegacyOwnerCandidateV1, undefined, [16]], "next": [13, __ref4], "unproven": __standalonePrograms[17] }, 1]))();
