// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: f671f5a622d8f62e844e1f9462b46043964d5582c73fe3684fd8f466599ef2bb; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../legacy-owner';
export declare const LegacyOwnerRouteV1: Compiled<typeof import("../legacy-owner").LegacyOwnerRouteV1>;
export declare const LegacyOwnerCandidateV1: Compiled<typeof import("../legacy-owner").LegacyOwnerCandidateV1>;
export type LegacyOwnerCandidateV1=import("../legacy-owner").LegacyOwnerCandidateV1;
export declare const LegacyOwnerProofV1: Compiled<typeof import("../legacy-owner").LegacyOwnerProofV1>;
export type LegacyOwnerProofV1=import("../legacy-owner").LegacyOwnerProofV1;
export declare const LegacyOwnerInventoryV1: Compiled<typeof import("../legacy-owner").LegacyOwnerInventoryV1>;
export type LegacyOwnerInventoryV1=import("../legacy-owner").LegacyOwnerInventoryV1;
