// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: c29a8de07dad9ee69c34c405a29ea9cfb90d645ef5cbbe57e53cfe738f0c4794; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../owner-witness';
export declare const IntakeOwnerClaimV1: Compiled<typeof import("../owner-witness").IntakeOwnerClaimV1>;
export type IntakeOwnerClaimV1=import("../owner-witness").IntakeOwnerClaimV1;
export declare const IntakeOwnerWitnessV1: Compiled<typeof import("../owner-witness").IntakeOwnerWitnessV1>;
export type IntakeOwnerWitnessV1=import("../owner-witness").IntakeOwnerWitnessV1;
