// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: c29a8de07dad9ee69c34c405a29ea9cfb90d645ef5cbbe57e53cfe738f0c4794; closed parse program v1.
import { standalone } from './runtime.mjs';
import { RequestId as __ref0 } from './index.mjs';
import { TargetEvidenceV1 as __ref1 } from './catalog.mjs';
import { LocalIntakeFormV2 as __ref2 } from './intake.mjs';
import { AuthorityIncarnationId as __ref3 } from './index.mjs';
import { UInt64Decimal as __ref4 } from './index.mjs';
import { ProductionRequestReceiptV1 as __ref5 } from './catalog.mjs';
import { AppLifecycleReceiptV1 as __ref6 } from './catalog.mjs';
export const IntakeOwnerClaimV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "requestId": __ref0, "source": __ref1, "form": __ref2 }, 1], (value, context) => {
        const source = value.form.ownerSource;
        if (source.appInstanceId !== value.source.appInstanceId || source.activeGenerationId !== value.source.activeGenerationId
            || source.lineageEpoch !== value.source.lineageEpoch || value.form.publishedAt !== null || value.form.revokedAt !== null || value.form.terminalReason !== null)
            context.addIssue({ code: "custom", message: "Original owner creation invocation required" });
    }]))();
export const IntakeOwnerWitnessV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "status": [5, ["live", "history_only", "deleted"]], "authorityIncarnationId": __ref3, "catalogGeneration": __ref4, "claim": IntakeOwnerClaimV1, "receipt": __ref5, "retirement": [12, __ref6] }, 1], (value, context) => {
        const receipt = value.receipt, source = value.claim.source;
        if (receipt.state !== "committed" || receipt.requestId !== value.claim.requestId || receipt.appInstanceId !== source.appInstanceId
            || receipt.activeGenerationId !== source.activeGenerationId || receipt.lineageEpoch !== source.lineageEpoch
            || receipt.expectedProtectionRevision !== source.protectionRevision || receipt.expectedStateSha256 !== source.stateSha256)
            context.addIssue({ code: "custom", message: "Exact original owner creation receipt required" });
        if ((value.status === "deleted") !== !!value.retirement || (value.retirement && (value.retirement.schema !== 2 || value.retirement.kind !== "delete"
            || value.retirement.requestedAppInstanceId !== value.claim.source.appInstanceId || value.retirement.authorityIncarnationId !== value.authorityIncarnationId
            || BigInt(value.retirement.completedCatalogGeneration) > BigInt(value.catalogGeneration))))
            context.addIssue({ code: "custom", message: "Exact original app retirement proof required" });
    }]))();
