// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 41edfe212a943dd8f637efe349b41dfba24308bc0320d9e45160585715295b87; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../private-metrics';
export declare const DurationBucketSchema: Compiled<typeof import("../private-metrics").DurationBucketSchema>;
export declare const SafeDiffKindSchema: Compiled<typeof import("../private-metrics").SafeDiffKindSchema>;
export declare const PrivateMetricEventSchema: Compiled<typeof import("../private-metrics").PrivateMetricEventSchema>;
export type SafeDiffKind=import("../private-metrics").SafeDiffKind;
export type DurationBucket=import("../private-metrics").DurationBucket;
export type PrivateMetricEvent=import("../private-metrics").PrivateMetricEvent;
