import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 23c210964015f19e4572a7f2dff1e79d402d06dff3ed5fda42a167aeaa874223; closed parse program v1.
import { standalone } from './runtime.mjs';
export const ProjectionIdent = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[0]))();
export const ProjectionCondOp = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["eq", "neq", "gt", "gte", "lt", "lte", "contains", "in", "is_null", "not_null", "within_days", "older_than_days"]]))();
export const ProjectionTableId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[23]))();
export const ProjectionFieldId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[24]))();
export const ProjectionRecordId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[47]))();
export const ProjectionFilterValueV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([10, [[0, []], [1, [[6]]], [2], [7, [10, [[0, []], [1, [[6]]]]], undefined, [50]]]]))();
export const ProjectionFilterRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "fieldId": ProjectionFieldId, "op": ProjectionCondOp, "value": [12, ProjectionFilterValueV1] }, 1], (filter, ctx) => {
        const valueFree = filter.op === "is_null" || filter.op === "not_null";
        if (valueFree === (filter.value !== undefined))
            ctx.addIssue({
                code: "custom",
                message: valueFree ? `${filter.op} does not take a value` : `${filter.op} requires a value`,
            });
    }]))();
const ProjectionRequestBaseV1 = { "schema": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([4, 1]))(), "expectedSchemaVersion": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([1, [[5], [0, 0, true]]]))(), "tableId": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(ProjectionTableId))(), "fieldIds": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([7, ProjectionFieldId, [1], [30]]))(), "options": /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "includeRecordIds": [2], "redactedFieldIds": [7, ProjectionFieldId, undefined, [30]] }, 1]))() };
export const ProjectionCurrentViewRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "expectedSchemaVersion": [1, [[5], [0, 0, true]]], "tableId": ProjectionTableId, "fieldIds": [7, ProjectionFieldId, [1], [30]], "options": [6, { "includeRecordIds": [2], "redactedFieldIds": [7, ProjectionFieldId, undefined, [30]] }, 1], "kind": [4, "current_view"], "view": [6, { "search": [0, [[1, 512, true]]], "filter": [13, ProjectionFilterRequestV1], "sort": [13, [6, { "fieldId": ProjectionFieldId, "dir": [5, ["asc", "desc"]] }, 1]], "dateAnchor": [0, [[3, /^\d{4}-\d{2}-\d{2}$/, "regex"]]] }, 1] }, 1]))();
export const ProjectionRecordRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "expectedSchemaVersion": [1, [[5], [0, 0, true]]], "tableId": ProjectionTableId, "fieldIds": [7, ProjectionFieldId, [1], [30]], "options": [6, { "includeRecordIds": [2], "redactedFieldIds": [7, ProjectionFieldId, undefined, [30]] }, 1], "kind": [4, "record"], "recordId": ProjectionRecordId }, 1]))();
export const ProjectionRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [11, "kind", [["current_view", ProjectionCurrentViewRequestV1], ["record", ProjectionRecordRequestV1]]], (request, ctx) => {
        if (new Set(request.fieldIds).size !== request.fieldIds.length)
            ctx.addIssue({ code: "custom", message: "projection field ids must be unique" });
        if (new Set(request.options.redactedFieldIds).size !== request.options.redactedFieldIds.length)
            ctx.addIssue({ code: "custom", message: "redacted field ids must be unique" });
    }]))();
export const ProjectionOutputFieldV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "label": __standalonePrograms[48], "name": __standalonePrograms[49], "redacted": [2], "source": [5, ["field", "record_id", "relation_id"]], "type": [5, ["text", "number", "integer", "boolean", "date", "enum", "computed", "relation", "rich_text"]] }, 1]))();
export const ProjectionManifestFilterV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "field": __standalonePrograms[49], "label": __standalonePrograms[48], "op": ProjectionCondOp, "value": [12, ProjectionFilterValueV1] }, 1]))();
export const ProjectionManifestViewV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "dateAnchor": [0, [[3, /^\d{4}-\d{2}-\d{2}$/, "regex"]]], "filter": [13, ProjectionManifestFilterV1], "search": [0, [[1, 512, true]]], "sort": [13, [6, { "dir": [5, ["asc", "desc"]], "field": __standalonePrograms[49], "label": __standalonePrograms[48] }, 1]] }, 1]))();
export const ProjectionDependencyV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "fields": [7, [6, { "field": ProjectionIdent, "label": __standalonePrograms[48], "table": ProjectionIdent }, 1], undefined, [30]], "kind": [5, ["computed", "relation"]], "output": ProjectionIdent }, 1], (dependency, ctx) => {
        if (dependency.kind === "relation" && dependency.fields.length !== 1)
            ctx.addIssue({
                code: "custom", path: ["fields"], message: "relation output needs one display dependency",
            });
    }]))();
export const ProjectionManifestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "completeness": [6, { "reason": [3], "truncated": [4, false] }, 1], "csv": [6, { "byteCount": [1, [[5], [0, 0, true], [1, 8388608, true]]], "formulaNeutralizedCells": [1, [[5], [0, 0, true]]] }, 1], "dependencies": [7, ProjectionDependencyV1, undefined, [30]], "fieldCount": [1, [[5], [0, 1, true], [1, 30, true]]], "fields": [7, ProjectionOutputFieldV1, [1], [30]], "kind": [5, ["record", "current_view"]], "limits": [6, { "fields": [4, 30], "plaintextBytes": [4, 8388608], "rows": [4, 5000], "sourceRows": [4, 20000] }, 1], "policies": [6, { "attachments": [4, "excluded"], "blankValues": [4, "empty_string"], "csvFormula": [4, "prefix_apostrophe"], "dates": [4, "stored_value_no_timezone_conversion"], "hiddenFields": [4, "excluded"], "inactiveFields": [4, "excluded"], "recordIds": [5, ["excluded", "included"]], "relations": [5, ["friendly_labels", "friendly_labels_with_record_ids"]], "unselectedFields": [4, "excluded"] }, 1], "redactions": [7, __standalonePrograms[48], undefined, [30]], "renderer": [6, { "id": [4, "clay-semantic-table"], "version": [4, 1] }, 1], "rowCount": __standalonePrograms[18], "schema": [4, "ProjectionManifestV1"], "schemaVersion": [1, [[5], [0, 0, true]]], "table": ProjectionIdent, "title": __standalonePrograms[48], "view": [13, ProjectionManifestViewV1] }, 1], (manifest, ctx) => {
        if ((manifest.kind === "current_view") !== (manifest.view !== null))
            ctx.addIssue({
                code: "custom", path: ["view"], message: "projection kind and view must agree",
            });
        const outputs = new Map();
        manifest.dependencies.forEach((dependency, index) => {
            if (outputs.has(dependency.output))
                ctx.addIssue({
                    code: "custom", path: ["dependencies", index], message: "duplicate output dependency",
                });
            outputs.set(dependency.output, dependency);
        });
        for (const field of manifest.fields) {
            const expected = field.source === "field"
                && (field.type === "relation" || field.type === "computed") ? field.type : null;
            const dependency = outputs.get(field.name);
            if (expected !== (dependency?.kind ?? null))
                ctx.addIssue({
                    code: "custom", path: ["dependencies"],
                    message: `dependency entry does not match output ${field.name}`,
                });
            outputs.delete(field.name);
        }
        if (outputs.size > 0)
            ctx.addIssue({
                code: "custom", path: ["dependencies"], message: "dependency refers to a missing output",
            });
    }]))();
export const ProjectionPlaintextV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "manifest": ProjectionManifestV1, "rows": [7, [7, [0, []], undefined, [30]], undefined, [5000]], "schema": [4, "ProjectionPlaintextV1"] }, 1], (plaintext, ctx) => {
        if (plaintext.manifest.rowCount !== plaintext.rows.length)
            ctx.addIssue({ code: "custom", message: "projection row count does not match rows" });
        if (plaintext.manifest.fieldCount !== plaintext.manifest.fields.length)
            ctx.addIssue({ code: "custom", message: "projection field count does not match fields" });
        plaintext.rows.forEach((row, index) => {
            if (row.length !== plaintext.manifest.fieldCount)
                ctx.addIssue({
                    code: "custom", path: ["rows", index], message: "projection row width does not match fields",
                });
        });
    }]))();
