// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 23c210964015f19e4572a7f2dff1e79d402d06dff3ed5fda42a167aeaa874223; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../projection';
export declare const ProjectionIdent: Parser<unknown>;
export declare const ProjectionCondOp: Parser<unknown>;
export declare const ProjectionTableId: Parser<unknown>;
export declare const ProjectionFieldId: Parser<unknown>;
export declare const ProjectionRecordId: Parser<unknown>;
export declare const ProjectionFilterValueV1: Parser<unknown>;
export declare const ProjectionFilterRequestV1: Parser<unknown>;
export declare const ProjectionCurrentViewRequestV1: Parser<unknown>;
export declare const ProjectionRecordRequestV1: Parser<unknown>;
export declare const ProjectionRequestV1: Compiled<typeof import("../projection").ProjectionRequestV1>;
export type ProjectionRequestV1=import("../projection").ProjectionRequestV1;
export declare const ProjectionOutputFieldV1: Compiled<typeof import("../projection").ProjectionOutputFieldV1>;
export declare const ProjectionManifestFilterV1: Parser<unknown>;
export declare const ProjectionManifestViewV1: Parser<unknown>;
export declare const ProjectionDependencyV1: Parser<unknown>;
export declare const ProjectionManifestV1: Compiled<typeof import("../projection").ProjectionManifestV1>;
export type ProjectionManifestV1=import("../projection").ProjectionManifestV1;
export declare const ProjectionPlaintextV1: Compiled<typeof import("../projection").ProjectionPlaintextV1>;
export type ProjectionPlaintextV1=import("../projection").ProjectionPlaintextV1;
