// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: f10f35fc64c82e43dc9e953f4b362005dcbcbec825e2915a42fbd065df4dc057; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../pure-compute';
export declare const StarterIdV1: Compiled<typeof import("../pure-compute").StarterIdV1>;
export declare const ComputeSourceV1: Compiled<typeof import("../pure-compute").ComputeSourceV1>;
export type ComputeSourceV1=import("../pure-compute").ComputeSourceV1;
export declare const ComputeRequestV1: Compiled<typeof import("../pure-compute").ComputeRequestV1>;
export type ComputeRequestV1=import("../pure-compute").ComputeRequestV1;
export declare const ComputeReplyV1: Compiled<typeof import("../pure-compute").ComputeReplyV1>;
export type ComputeReplyV1=import("../pure-compute").ComputeReplyV1;
