import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: f10f35fc64c82e43dc9e953f4b362005dcbcbec825e2915a42fbd065df4dc057; closed parse program v1.
import { standalone } from './runtime.mjs';
import { UInt64Decimal as __ref0 } from './index.mjs';
import { TargetEvidenceV1 as __ref1 } from './catalog.mjs';
export const StarterIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["blank", "tracker", "log", "dashboard", "small_business", "crm", "financials", "staff", "habits", "inventory", "approvals", "jobs", "content", "okrs", "events", "library"]]))();
export const ComputeSourceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "catalogGeneration": __ref0, "target": __ref1 }, 1]))();
export const ComputeRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "v": [4, 1], "kind": [4, "starter"], "nonce": __standalonePrograms[34], "starter": StarterIdV1, "source": ComputeSourceV1 }, 1]))();
export const ComputeReplyV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "v": [4, 1], "kind": [4, "starter"], "nonce": __standalonePrograms[34], "starter": StarterIdV1, "source": ComputeSourceV1, "fragment": [0, [[0, 1, true], [1, 900000, true]]] }, 1]))();
