// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 2d7c3cb9d6acb63648eb29e9b15216dcafe4b777ee80a6d1631be48825544ad7; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../restore';
export declare const RestoreValidationId: Parser<unknown>;
export declare const AuthenticatedFormat5RestoreGrantV1: Compiled<typeof import("../restore").AuthenticatedFormat5RestoreGrantV1>;
export type AuthenticatedFormat5RestoreGrantV1=import("../restore").AuthenticatedFormat5RestoreGrantV1;
