import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 2d7c3cb9d6acb63648eb29e9b15216dcafe4b777ee80a6d1631be48825544ad7; closed parse program v1.
import { standalone } from './runtime.mjs';
import { BackupAuthenticationV1 as __ref0 } from './backup.mjs';
import { Sha256 as __ref1 } from './index.mjs';
import { TargetEvidenceV1 as __ref2 } from './catalog.mjs';
import { AppInstanceId as __ref3 } from './index.mjs';
import { CanonicalInstant as __ref4 } from './catalog.mjs';
export const RestoreValidationId = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[16]))();
export const AuthenticatedFormat5RestoreGrantV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, 1], "kind": [4, "authenticated_format5_restore_as_new"], "validationId": RestoreValidationId, "archiveFormat": [4, 5], "cryptographicallyAuthenticated": [4, true], "authentication": __ref0, "freshness": [5, ["current", "unknown"]], "archiveSha256": __ref1, "archiveTarget": __ref2, "preservedAppInstanceId": __ref3, "destinationAppInstanceId": __ref3, "installMode": [4, "new_app_only"], "validatedAt": __ref4 }, 1], (value, context) => {
        if (value.destinationAppInstanceId === value.preservedAppInstanceId)
            context.addIssue({
                code: "custom",
                path: ["destinationAppInstanceId"],
                message: "restore-as-new destination must differ from the preserved app",
            });
    }]))();
