// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 9eefc38ecd188e9a09adf033005f1ac37b5df77c0b86269570772560d102bd06; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../saved-views';
export declare const VIEW_ID: typeof import("../saved-views").VIEW_ID;
export declare const FIELD_NAME: typeof import("../saved-views").FIELD_NAME;
export declare const TABLE_ID: typeof import("../saved-views").TABLE_ID;
export declare const FIELD_ID: typeof import("../saved-views").FIELD_ID;
export declare const ROW_ID: typeof import("../saved-views").ROW_ID;
export declare const FILTER_OPS: typeof import("../saved-views").FILTER_OPS;
export declare const OperationalCondition: Compiled<typeof import("../saved-views").OperationalCondition>;
export declare const OperationalView: Compiled<typeof import("../saved-views").OperationalView>;
export declare const OperationalViewLibrary: Compiled<typeof import("../saved-views").OperationalViewLibrary>;
export declare const __hook0: Parser<unknown>;
export declare const __hook1: Parser<unknown>;
