import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 9eefc38ecd188e9a09adf033005f1ac37b5df77c0b86269570772560d102bd06; closed parse program v1.
import { standalone } from './runtime.mjs';
export const VIEW_ID = /^view_[0-9a-f]{32}$/;
export const FIELD_NAME = /^[a-z][a-z0-9_]{0,40}$/;
export const TABLE_ID = /^tbl_[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
export const FIELD_ID = /^fld_[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
export const ROW_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const FILTER_OPS = [
    "eq", "neq", "gt", "gte", "lt", "lte", "contains", "in", "is_null",
    "not_null", "within_days", "older_than_days",
];
export const OperationalCondition = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "field": __standalonePrograms[0], "op": [5, ["eq", "neq", "gt", "gte", "lt", "lte", "contains", "in", "is_null", "not_null", "within_days", "older_than_days"]], "value": [12, [18]] }, 1], (value, context) => {
        const hasValue = Object.prototype.hasOwnProperty.call(value, "value");
        if (value.op === "is_null" || value.op === "not_null") {
            if (hasValue)
                context.addIssue({ code: "custom", message: "null filters have no value" });
            return;
        }
        const valid = value.op === "in"
            ? Array.isArray(value.value) && value.value.length <= 50
                && value.value.every(item => typeof item === "string" || typeof item === "number")
            : value.op === "within_days" || value.op === "older_than_days"
                ? typeof value.value === "number" && Number.isFinite(value.value) && value.value >= 0
                : value.op === "contains" ? typeof value.value === "string"
                    : typeof value.value === "string" || typeof value.value === "number"
                        || typeof value.value === "boolean";
        if (!hasValue || !valid)
            context.addIssue({ code: "custom", message: "invalid filter value" });
    }]))();
export const OperationalView = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "id": [0, [[3, /^view_[0-9a-f]{32}$/, "regex"]]], "name": __standalonePrograms[26], "table": __standalonePrograms[0], "search": [0, [[1, 120, true]]], "filters": [7, OperationalCondition, undefined, [8]], "orderBy": [7, [6, { "field": __standalonePrograms[0], "dir": [5, ["asc", "desc"]] }, 1], undefined, [4]], "visibleFields": [7, __standalonePrograms[0], undefined, [64]], "identity": [12, [6, { "tableId": __standalonePrograms[23], "filterFieldIds": [7, __standalonePrograms[24], undefined, [8]], "orderFieldIds": [7, __standalonePrograms[24], undefined, [4]], "visibleFieldIds": [7, __standalonePrograms[24], undefined, [64]] }, 1]], "createdAt": [14, [0, [[1, 64, true]]], value => Number.isFinite(Date.parse(value))], "updatedAt": [14, [0, [[1, 64, true]]], value => Number.isFinite(Date.parse(value))] }, 1], (value, context) => {
        if (value.identity && (value.identity.filterFieldIds.length !== value.filters.length
            || value.identity.orderFieldIds.length !== value.orderBy.length
            || value.identity.visibleFieldIds.length !== value.visibleFields.length)) {
            context.addIssue({ code: "custom", message: "saved view semantic bindings are incomplete" });
        }
    }]))();
export const OperationalViewLibrary = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "format": [4, 1], "revision": __standalonePrograms[8], "views": [7, OperationalView, undefined, [50]] }, 1], (value, context) => {
        if (new Set(value.views.map(view => view.id)).size !== value.views.length)
            context.addIssue({ code: "custom", path: ["views"], message: "saved view ids must be unique" });
    }]))();
export const __hook0 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, [[1, 64, true]]], value => Number.isFinite(Date.parse(value))]))();
export const __hook1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, [[1, 64, true]]], value => Number.isFinite(Date.parse(value))]))();
