import {programs as __standalonePrograms} from './programs.mjs';
// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 8d7b036f6258beed7efcde05592ed52cd4b06a18da43c4d67bf0fbf1b991ff8a; closed parse program v1.
import { standalone } from './runtime.mjs';
import { ProjectionRequestV1 as __ref0 } from './projection.mjs';
import { ProjectionPlaintextV1 as __ref1 } from './projection.mjs';
export const SHARE_MAX_CIPHERTEXT_BYTES_V1 = 8 * 1024 * 1024 + 16;
export const SHARE_MAX_ATTACHMENTS_V1 = 20;
export const SHARE_MAX_LIFETIME_MS_V1 = 30 * 24 * 60 * 60 * 1000;
export const SHARE_CREATE_BODY_BYTES_V1 = 12 * 1024 * 1024;
export const ShareIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [[3, /^shr_[a-z2-7]{26}$/, "regex"]]]))();
export const ShareRevokeTokenV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[33]))();
export const ShareRevokeTokenHashV1 = ShareRevokeTokenV1;
export const ShareKeyV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[33]))();
export const ShareFileIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[50]))();
export const ShareTableIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[23]))();
export const ShareFieldIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[24]))();
export const ShareRecordIdV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[47]))();
export const DigestBase64UrlV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[33]))();
export const Base64UrlV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([0, [__standalonePrograms[41]]]))();
export const IsoInstantV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone(__standalonePrograms[21]))();
export const ShareCiphertextEnvelopeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "algorithm": [4, "A256GCM"], "iv": [0, [[3, /^[A-Za-z0-9_-]{16}$/, "regex"]]], "ciphertext": [0, [__standalonePrograms[41], [0, 22, true], [1, 11184832, true]]] }, 1]))();
export const ShareCreateRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "shareId": ShareIdV1, "expiresAt": IsoInstantV1, "revokeTokenHash": ShareRevokeTokenHashV1, "envelope": ShareCiphertextEnvelopeV1 }, 1]))();
export const ShareCreateResponseV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "shareId": ShareIdV1, "expiresAt": IsoInstantV1 }, 1]))();
export const ShareTerminalRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "request": ShareCreateRequestV1, "revokeToken": ShareRevokeTokenHashV1 }, 1]))();
export const ShareTerminalResponseV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "shareId": ShareIdV1, "expiresAt": IsoInstantV1, "requestSha256": __standalonePrograms[34], "terminal": [4, true] }, 1]))();
export const ShareRelaySnapshotV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "shareId": ShareIdV1, "expiresAt": IsoInstantV1, "envelope": ShareCiphertextEnvelopeV1 }, 1]))();
export const ShareRevokeRequestV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "revokeToken": ShareRevokeTokenHashV1 }, 1]))();
export const ShareRevokeResponseV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "shareId": ShareIdV1, "revoked": [4, true] }, 1]))();
export const ShareRelayErrorV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "schema": [4, 1], "error": [5, ["bad_request", "unauthorized", "not_found", "expired", "revoked", "conflict", "capacity", "forbidden"]] }, 1]))();
export const ShareFieldBindingV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "fieldId": ShareFieldIdV1, "outputName": __standalonePrograms[0] }, 1]))();
export const ShareAttachmentSourceV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "tableId": ShareTableIdV1, "fieldId": ShareFieldIdV1, "recordId": ShareRecordIdV1 }, 1]))();
export const ShareAttachmentBindingV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "id": ShareFileIdV1, "size": __standalonePrograms[51], "sha256": __standalonePrograms[34], "source": ShareAttachmentSourceV1 }, 1]))();
export const ShareApprovedScopeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, "ShareApprovedScopeV1"], "projectionRequest": __ref0, "fieldBindings": [7, ShareFieldBindingV1, [1], [30]], "attachmentIds": [7, ShareFileIdV1, undefined, [20]], "attachmentBindings": [7, ShareAttachmentBindingV1, undefined, [20]], "approvedAt": IsoInstantV1, "projectionDigest": DigestBase64UrlV1, "fingerprint": DigestBase64UrlV1 }, 1], (scope, ctx) => {
        if (scope.fieldBindings.length !== scope.projectionRequest.fieldIds.length
            || scope.fieldBindings.some((binding, index) => binding.fieldId !== scope.projectionRequest.fieldIds[index]))
            ctx.addIssue({ code: "custom", path: ["fieldBindings"],
                message: "field bindings must match the ordered stable field allowlist" });
        if (new Set(scope.attachmentIds).size !== scope.attachmentIds.length)
            ctx.addIssue({ code: "custom", path: ["attachmentIds"], message: "attachment ids must be unique" });
        if (scope.attachmentBindings.length !== scope.attachmentIds.length
            || scope.attachmentBindings.some((binding, index) => binding.id !== scope.attachmentIds[index]))
            ctx.addIssue({ code: "custom", path: ["attachmentBindings"],
                message: "attachment bindings must match the ordered attachment allowlist" });
        if (scope.attachmentIds.some((id, index) => index > 0 && id < scope.attachmentIds[index - 1]))
            ctx.addIssue({ code: "custom", path: ["attachmentIds"], message: "attachment ids must be sorted" });
        const approvedRecordId = scope.projectionRequest.kind === "record"
            ? scope.projectionRequest.recordId : null;
        if (approvedRecordId === null && scope.attachmentBindings.length > 0)
            ctx.addIssue({ code: "custom", path: ["attachmentBindings"],
                message: "attachments require an exact single-record projection" });
        if (scope.attachmentBindings.some(binding => binding.source.tableId !== scope.projectionRequest.tableId
            || (approvedRecordId !== null && binding.source.recordId !== approvedRecordId)))
            ctx.addIssue({ code: "custom", path: ["attachmentBindings"],
                message: "attachment sources must match the approved projection authority" });
    }]))();
export const ShareSafeMimeV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([5, ["image/png", "image/jpeg", "image/gif", "image/webp", "application/pdf", "text/plain", "text/csv", "application/json", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]]))();
export const ShareAttachmentV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([6, { "id": ShareFileIdV1, "name": [14, [0, [[0, 1, true], [1, 255, true]]], name => !/[\\/\u0000-\u001f]/.test(name), "safe file name required"], "mime": ShareSafeMimeV1, "size": __standalonePrograms[51], "sha256": __standalonePrograms[34], "source": ShareAttachmentSourceV1, "bytes": [0, [__standalonePrograms[41], [1, 13981016, true]]] }, 1]))();
export const SharePayloadV1 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([15, [6, { "schema": [4, "SharePayloadV1"], "scope": ShareApprovedScopeV1, "projection": __ref1, "attachments": [7, ShareAttachmentV1, undefined, [20]] }, 1], (payload, ctx) => {
        const request = payload.scope.projectionRequest;
        const manifest = payload.projection.manifest;
        if (request.kind !== manifest.kind)
            ctx.addIssue({ code: "custom", path: ["projection"], message: "projection kind is outside approved scope" });
        if (request.expectedSchemaVersion !== manifest.schemaVersion)
            ctx.addIssue({ code: "custom", path: ["projection"], message: "projection schema version is outside approved scope" });
        const projectedFields = manifest.fields.filter(field => field.source === "field");
        if (projectedFields.length !== request.fieldIds.length)
            ctx.addIssue({ code: "custom", path: ["projection", "manifest", "fields"],
                message: "projection fields do not match stable-id allowlist" });
        if (projectedFields.length !== payload.scope.fieldBindings.length
            || projectedFields.some((field, index) => field.name !== payload.scope.fieldBindings[index]?.outputName))
            ctx.addIssue({ code: "custom", path: ["projection", "manifest", "fields"],
                message: "projection output identities do not match approved stable field bindings" });
        const actualIds = payload.attachments.map(file => file.id);
        if (actualIds.length !== payload.scope.attachmentIds.length
            || actualIds.some((id, index) => id !== payload.scope.attachmentIds[index]))
            ctx.addIssue({ code: "custom", path: ["attachments"],
                message: "attachments do not match approved stable-id allowlist" });
        if (payload.attachments.length !== payload.scope.attachmentBindings.length
            || payload.attachments.some((file, index) => {
                const binding = payload.scope.attachmentBindings[index];
                return !binding || file.id !== binding.id || file.size !== binding.size
                    || file.sha256 !== binding.sha256
                    || file.source.tableId !== binding.source.tableId
                    || file.source.fieldId !== binding.source.fieldId
                    || file.source.recordId !== binding.source.recordId;
            }))
            ctx.addIssue({ code: "custom", path: ["attachments"],
                message: "attachments do not match approved digest and source bindings" });
    }]))();
export const __hook0 = /*#__PURE__*/ /*#__PURE__*/ (()=>standalone([14, [0, [[0, 1, true], [1, 255, true]]], name => !/[\\/\u0000-\u001f]/.test(name), "safe file name required"]))();
