// Generated by packages/schema/scripts/generate-standalone.mjs. DO NOT EDIT.
// Source SHA-256: 53f86eac06c3725e4a7e9aba3636824a8ff824d2c5044c192a67602fae74faed; closed parse program v1.
import type { Compiled, Parser } from './runtime.mjs';
export type * from '../worker-contracts';
export declare const name: Compiled<typeof import("../worker-contracts").name>;
export declare const tableId: Compiled<typeof import("../worker-contracts").tableId>;
export declare const rowId: Compiled<typeof import("../worker-contracts").rowId>;
export declare const captureLedger: Compiled<typeof import("../worker-contracts").captureLedger>;
export declare const dailyRequest: Compiled<typeof import("../worker-contracts").dailyRequest>;
export declare const count: Compiled<typeof import("../worker-contracts").count>;
export declare const ledger: Compiled<typeof import("../worker-contracts").ledger>;
export declare const InboxDispositionWriteV1: Compiled<typeof import("../worker-contracts").InboxDispositionWriteV1>;
export declare const ConversionResultV1: Compiled<typeof import("../worker-contracts").ConversionResultV1>;
export type DailyCommand=import("../worker-contracts").DailyCommand;
export declare const ForwardOpListV1: Compiled<typeof import("../worker-contracts").ForwardOpListV1>;
export declare const CaptureResultV1: Compiled<typeof import("../worker-contracts").CaptureResultV1>;
