/**
 * Closed, machine-readable classification of every production DB-worker,
 * Store RPC, Bridge, and public ClayStore route which can reach durable state.
 *
 * `authority` routes must enter the worker-owned ProductionStoreAuthority.
 * `unavailable` routes are deliberately disabled until their complete state
 * transition can be represented by that authority.  They must never fall back
 * to a raw Store or driver write.
 */
export type MutationRouteEnforcement =
  | "read"
  | "ephemeral"
  | "shadow"
  | "boot"
  | "lifecycle-control"
  | "lifecycle-authority"
  | "authority"
  | "planner-authority"
  | "authority-store-port"
  | "unavailable";

export type MutationRouteClassification = {
  enforcement: MutationRouteEnforcement;
  mutates: "none" | "shadow" | "live" | "lifecycle";
};

const route = (
  enforcement: MutationRouteEnforcement,
  mutates: MutationRouteClassification["mutates"],
): MutationRouteClassification => ({ enforcement, mutates });

export const DB_WORKER_ROUTE_CENSUS = Object.freeze({
  boot: route("boot", "lifecycle"),
  shutdown: route("lifecycle-control", "lifecycle"),
  createApp: route("lifecycle-authority", "lifecycle"),
  switchApp: route("lifecycle-authority", "lifecycle"),
  renameApp: route("lifecycle-authority", "lifecycle"),
  forkApp: route("lifecycle-authority", "lifecycle"),
  deleteApp: route("lifecycle-authority", "lifecycle"),
  importNewApp: route("lifecycle-authority", "live"),
  undoNewAppImport: route("lifecycle-authority", "live"),
  seed: route("authority", "live"),
  firstRunEvidence: route("read", "none"),
  firstEverydayActionTarget: route("read", "none"),
  completeEverydayAction: route("authority", "live"),
  deviceProtection: route("read", "none"),
  importTable: route("unavailable", "live"),
  beginImport: route("ephemeral", "none"),
  stageImportChunk: route("ephemeral", "none"),
  importStructure: route("read", "none"),
  configureImport: route("ephemeral", "none"),
  previewImport: route("read", "none"),
  commitImport: route("authority", "live"),
  cancelImport: route("ephemeral", "none"),
  undoImport: route("authority", "live"),
  panels: route("read", "none"),
  panelProvenance: route("read", "none"),
  semanticTrace: route("read", "none"),
  fieldProvenance: route("read", "none"),
  recordPrivateMetric: route("authority", "live"),
  privateMetricsSummary: route("read", "none"),
  setPrivateMetricsEnabled: route("authority", "live"),
  clearPrivateMetrics: route("authority", "live"),
  commitLayout: route("authority", "live"),
  history: route("read", "none"),
  setCheckpoint: route("authority", "live"),
  panelsAt: route("read", "none"),
  makeLatest: route("authority", "live"),
  registryTables: route("read", "none"),
  projectPlaintextV1: route("read", "none"),
  cancelProjectionV1: route("ephemeral", "none"),
  dailyHome: route("read", "none"),
  dailyHomeResolveDate: route("read", "none"),
  dailyHomeSourceCompareAndSet: route("authority", "live"),
  dailyHomeNavigationCompareAndSet: route("authority", "live"),
  dailyHomeInitializeTimeZone: route("authority", "live"),
  dailyHomeQuickCapture: route("authority", "live"),
  dailyHomeUndoCapture: route("authority", "live"),
  storePort: route("authority-store-port", "live"),
  intent: route("planner-authority", "live"),
  repairPanel: route("planner-authority", "live"),
  revertPanel: route("authority", "live"),
  renamePanel: route("authority", "live"),
  addAttachment: route("authority", "live"),
  attachmentsForRecord: route("read", "none"),
  readAttachment: route("read", "none"),
  removeAttachment: route("authority", "live"),
  attachmentStorage: route("read", "none"),
  purgeDeletedAttachments: route("authority", "live"),
  listIntakeForms: route("read", "none"),
  intakeInbox: route("read", "none"),
  intakeDeliveryFailures: route("read", "none"),
  intakeReceipts: route("read", "none"),
  saveIntakeForm: route("authority", "live"),
  markIntakeFormPublished: route("authority", "live"),
  revokeIntakeForm: route("authority", "live"),
  markIntakeFormExpired: route("authority", "live"),
  stageIntakeSubmission: route("authority", "live"),
  recordIntakeDeliveryFailure: route("authority", "live"),
  authorizeIntakeDeliveryDiscard: route("authority", "live"),
  resolveIntakeDeliveryFailure: route("authority", "live"),
  rejectIntakeSubmission: route("authority", "live"),
  simulateIntakeAutoAccept: route("authority", "live"),
  enableIntakeAutoAccept: route("authority", "live"),
  disableIntakeAutoAccept: route("authority", "live"),
  processIntakeAutoAccept: route("authority", "live"),
  acceptIntakeSubmission: route("authority", "live"),
  undoIntakeReceipt: route("authority", "live"),
  automationRecipes: route("read", "none"),
  automationRuntimeOverview: route("read", "none"),
  automationRuntimeStatus: route("read", "none"),
  listAutomations: route("read", "none"),
  upsertAutomation: route("authority", "live"),
  saveAutomationDraft: route("authority", "live"),
  saveAutomationRecipeDraft: route("authority", "live"),
  enableAutomation: route("authority", "live"),
  pauseAutomation: route("authority", "live"),
  deleteAutomation: route("authority", "live"),
  simulateAutomation: route("read", "none"),
  runAutomations: route("authority", "live"),
  runAutomationNow: route("authority", "live"),
  automationRuns: route("read", "none"),
  undoAutomationRun: route("authority", "live"),
  notifications: route("read", "none"),
  markNotificationRead: route("authority", "live"),
  globalSearch: route("read", "none"),
  applyBatch: route("authority", "live"),
  operationBatches: route("read", "none"),
  undoBatch: route("authority", "live"),
  rowHistory: route("read", "none"),
  previewRelationConversion: route("read", "none"),
  convertTextToRelation: route("authority", "live"),
  addColumn: route("authority", "live"),
  addRelationColumn: route("authority", "live"),
  renameColumn: route("authority", "live"),
  removeColumn: route("authority", "live"),
  removePanel: route("authority", "live"),
  keep: route("planner-authority", "live"),
  discard: route("planner-authority", "live"),
  removeSamples: route("authority", "live"),
  fillSamples: route("authority", "live"),
  sampleCount: route("read", "none"),
  restoreRow: route("authority", "live"),
  restorableRows: route("read", "none"),
  suggestions: route("read", "none"),
  recordFilter: route("authority", "live"),
  dismissSuggestion: route("authority", "live"),
  acceptSuggestion: route("authority", "live"),
  reset: route("unavailable", "lifecycle"),
  exportArchive: route("unavailable", "live"),
  collectArchiveSnapshot: route("read", "none"),
  importArchive: route("unavailable", "lifecycle"),
  backupSelection: route("authority", "lifecycle"),
  backupRecords: route("read", "none"),
  manualBackupDownloads: route("read", "none"),
  recordManualBackupDownload: route("authority", "live"),
  prepareAutomaticBackup: route("unavailable", "live"),
  validateBackupStage: route("read", "none"),
  publishBackup: route("authority", "lifecycle"),
  backupTrustStatus: route("unavailable", "none"),
  beginBackupTrustEnrollment: route("unavailable", "live"),
  confirmBackupTrustEnrollment: route("unavailable", "live"),
  importRecoveryKit: route("unavailable", "live"),
  activateImportedBackupSeries: route("unavailable", "live"),
  recoveryCandidates: route("read", "none"),
  validateRestoreArchive: route("ephemeral", "none"),
  restoreAsNew: route("lifecycle-authority", "lifecycle"),
  status: route("read", "none"),
  requestPersist: route("ephemeral", "none"),
  debugLog: route("read", "none"),
  getSetting: route("read", "none"),
  setSetting: route("authority", "live"),
  deleteSetting: route("authority", "live"),
  compareAndSetSetting: route("authority", "live"),
} as const satisfies Record<string, MutationRouteClassification>);

/** No current WorkerClient caller. These old DB commands intentionally remain
 * closed, including commands that would transport secret Recovery Kit bytes. */
export const RETIRED_DB_WORKER_ROUTES = Object.freeze({
  reset: "Start over opens authority-backed new-app setup and preserves existing apps.",
  importTable: "Use bounded begin/stage/configure/preview/commitImport, or importNewApp.",
  importArchive: "Replacement import retired; only authenticated restore-as-new is intended.",
  exportArchive: "Trusted-shell authenticated export uses collectArchiveSnapshot plus private-channel readback.",
  prepareAutomaticBackup: "Trusted-shell coordinator prepares; worker owns snapshots, validation and publication.",
  backupTrustStatus: "Trust vault status is read in the trusted shell; no keys enter the worker.",
  beginBackupTrustEnrollment: "Recovery Kit creation is a trusted-shell key-vault operation.",
  confirmBackupTrustEnrollment: "Recovery Kit confirmation is a trusted-shell key-vault operation.",
  importRecoveryKit: "Recovery Kit bytes stay in the trusted-shell key vault.",
  activateImportedBackupSeries: "Explicit trust rotation runs in the trusted-shell key vault.",
} as const);

export function productionWorkerRouteAvailable(name: keyof typeof DB_WORKER_ROUTE_CENSUS): boolean {
  return DB_WORKER_ROUTE_CENSUS[name].enforcement !== "unavailable";
}

export const STORE_RPC_ROUTE_CENSUS = Object.freeze({
  query: route("read", "none"),
  insert: route("authority", "live"),
  update: route("authority", "live"),
  softDelete: route("authority", "live"),
  registryTables: route("read", "none"),
} as const satisfies Record<string, MutationRouteClassification>);

export const BRIDGE_WRITE_ROUTE_CENSUS = Object.freeze({
  "db.query": route("read", "none"),
  "db.watch": route("read", "none"),
  "db.unwatch": route("ephemeral", "none"),
  "db.insert": route("authority", "live"),
  "db.update": route("authority", "live"),
  "db.softDelete": route("authority", "live"),
} as const satisfies Record<string, MutationRouteClassification>);

/** Public Store methods with durable write reachability. */
export const CLAY_STORE_WRITER_CENSUS = Object.freeze({
  openMemory: "boot",
  fromDriver: "boot",
  recordPrivateMetric: "authority",
  setPrivateMetricsEnabled: "authority",
  clearPrivateMetrics: "authority",
  setSetting: "authority",
  recordSampleRowProvenance: "authority",
  deleteSetting: "authority",
  scrubLegacyCredentialSettings: "unavailable",
  commit: "unavailable",
  commitPreparedMutation: "unavailable",
  commitImport: "authority",
  undoImport: "authority",
  commitLayout: "authority",
  renamePanel: "authority",
  removePanel: "authority",
  setCheckpoint: "authority",
  beginAttempt: "unavailable",
  finishAttempt: "unavailable",
  rollbackTo: "unavailable",
  rollForwardTo: "unavailable",
  convertTextToRelation: "authority",
  insert: "authority",
  recordUsage: "authority",
  markSuggestionShown: "unavailable",
  dismissSuggestion: "authority",
  acceptSuggestion: "authority",
  addAttachment: "authority",
  removeAttachment: "authority",
  purgeDeletedAttachments: "authority",
  upsertAutomation: "authority",
  saveAutomationDraft: "authority",
  saveAutomationRecipeDraft: "authority",
  enableAutomation: "authority",
  pauseAutomation: "authority",
  deleteAutomation: "authority",
  runAutomationNow: "authority",
  runDueAutomations: "authority",
  undoAutomationRun: "authority",
  markNotificationRead: "authority",
  applyBatch: "authority",
  undoBatch: "authority",
  restoreRow: "authority",
  saveIntakeForm: "authority",
  markIntakeFormPublished: "authority",
  revokeIntakeForm: "authority",
  markIntakeFormExpired: "authority",
  stageIntakeSubmission: "authority",
  recordIntakeDeliveryFailure: "authority",
  authorizeIntakeDeliveryDiscard: "authority",
  resolveIntakeDeliveryFailure: "authority",
  rejectIntakeSubmission: "authority",
  simulateIntakeAutoAccept: "authority",
  enableIntakeAutoAccept: "authority",
  disableIntakeAutoAccept: "authority",
  processIntakeAutoAccept: "authority",
  acceptIntakeSubmission: "authority",
  undoIntakeReceipt: "authority",
  update: "authority",
  softDelete: "authority",
  revertPanel: "authority",
  exportArchive: "unavailable",
  replaceFromArchive: "unavailable",
  importArchive: "unavailable",
} as const satisfies Record<string, "boot" | "authority" | "unavailable">);
