export {
  AutomaticBackupFileName,
  BackupAdapterArtifactBindingV1,
  BackupFailureReasonCodeV1,
  BackupId,
  BackupGenerationId,
  BackupPublicationReceiptV1,
  BackupPublicationRequestV1,
  BackupRecordV1,
  BackupResultV1,
  BackupRunV1,
  BackupRuntimeBindingV1,
  BackupSelectedTargetV1,
  BackupStageValidationV1,
  BackupTargetAdapterCertificationId,
  BackupTargetAdapterCertificationV1,
  BackupTargetId,
  BackupTargetV1,
  ManualBackupDownloadV1,
  MAX_BACKUP_ARCHIVE_BYTES,
  MAX_BACKUP_ROTATION_RECORDS,
  ValidatedBackupArtifactV1,
  type AutomaticBackupFileName as AutomaticBackupFileNameValue,
  type BackupAdapterArtifactBindingV1 as BackupAdapterArtifactBinding,
  type BackupFailureReasonCodeV1 as BackupFailureReasonCode,
  type BackupGenerationId as BackupGenerationIdValue,
  type BackupId as BackupIdValue,
  type BackupPublicationReceiptV1 as BackupPublicationReceipt,
  type BackupPublicationRequestV1 as BackupPublicationRequest,
  type BackupRecordV1 as BackupRecord,
  type BackupResultV1 as BackupResult,
  type BackupRunV1 as BackupRun,
  type BackupRuntimeBindingV1 as BackupRuntimeBinding,
  type BackupSelectedTargetV1 as BackupSelectedTarget,
  type BackupSnapshotV1 as BackupSnapshot,
  type BackupStageValidationV1 as BackupStageValidation,
  type BackupTargetAdapterCertificationId as BackupTargetAdapterCertificationIdValue,
  type BackupTargetAdapterCertificationV1 as BackupTargetAdapterCertification,
  type BackupTargetId as BackupTargetIdValue,
  type BackupTargetV1 as BackupTarget,
  type ManualBackupDownloadV1 as ManualBackupDownload,
  type ValidatedBackupArtifactV1 as ValidatedBackupArtifact,
} from "@clay/schema/backup";
export {
  buildAutomaticBackupFileName,
  runExternalBackup,
  type ExternalBackupAuthority,
  type ExternalBackupDependencies,
  type ExternalBackupDirectory,
  type ExternalBackupWriter,
  type IsolatedArchiveStageValidator,
} from "./external-backup";
